### ISSUE TITLE
Build: make sure that we fix version of Pandas only for PPC64le build, not for rest

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#1003]

**Comment by abal5** [comment]
Assign a specific version of pandas for the PPC64Ie builds in the requirements file?

**Comment by st-pasha** [comment]
We decided to remove pandas from the requirements file altogether. Instead it would be either installed or not installed in different environments depending on platform / test scenario.

**Comment by mmalohlava** [comment]
Fix version to 0.20.0 and we will upgrade LLVM to version 6: https://github.com/h2oai/datatable/pull/1010
