### ISSUE TITLE
helper function to update to latest dev version

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#1069]
Would be useful to have extra technical helper function just to install latest dev version of datatable (ideally the one that pass tests). In R data.table we have `update.dev.pkg()`.

**Comment by st-pasha** [comment]
"Latest dev version that passes tests" is the `master` branch. This can be installed via `git checkout master && make` (or if you want to skip tests, `make build && make install`).

There is also the latest released version which can be installed either via `pip install datatable`, or checking out the branch corresponding to that release (e.g. `rel-0.5`) and then doing `make`.

Reloading the module from python is possible but complicated for extension modules (e.g. those that contain compiled C/C++ code). See https://stackoverflow.com/questions/8295555/how-to-reload-a-python3-c-extension-module. We might also need to implement the [multi-phase module initialization protocol](https://docs.python.org/3/c-api/module.html#multi-phase-initialization) (this part isn't too hard).

**Comment by jangorecki** [comment]
OK, didn't know it is not that straightforward as in R.
