### ISSUE TITLE
make build could detect llvm6/clang from apt-get

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#1092]
In apt-get repo for Ubuntu 18.04 there is llvm6 already, after installing it is located in `/usr/lib/llvm-6.0/`.
`make build` could check that path before raising error about not set LLVM6 env var. This simplifies installation of dependencies for build process.

**Comment by jangorecki** [comment]
@st-pasha any updates on this?

**Comment by st-pasha** [comment]
It's not as simple as I hoped it would be, since Ubuntu18 LLVM package doesn't include Clang or OpenMP library. I'll investigate this further...

**Comment by st-pasha** [comment]
After PR #1362 `datatable` can be built on Ubuntu18.04 using the default `gcc` compiler.
Closing as resolved, but please reopen if there are any remaining issues.
