### ISSUE TITLE
New binary format: Jay

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1109]
This proposal suggests switching from the current "NFF" binary format for saving datatable Frames on disk, to a new format codenamed `Jay`. The new format saves the data into a single file (not folder) and keeps meta information in `Cap'n Proto` format (not CSV).

It is believed that the new format will be an improvement over NFF in several respects:
1. Single file is easier to pass around from one machine to another.
2. For a dataset containing multiple columns (10s or 100s of thousands), the operating system becomes very sluggish with any file-related operation.
3. Frames containing many columns but few rows waste a lot of disk space in NFF format due to each file having a minimum size of 4096 bytes.
4. A frame containing `n` columns requires between `n` and `2n` open file handles or memmapped regions, which becomes difficult on systems where those resources are limited. This becomes especially problematic in row-by-row operations on the frame.
5. The architecture that forces us to keep many memmap regions opened at the same time is prone to sporadic memory errors.
6. Cap'n Proto storage of meta information is more flexible and can be parsed faster than CSV.

The NFF format has the following advantages over Jay:
1. Multi-file storage is advantageous over single-file for gigantic datasets (100s of GB)
2. One file per column allows an administrator to control permissions for each column.
3. Having one file per column allows extending the dataset with new data more easily.

In short, NFF has several purely theoretical advantages, whereas Jay has many practical ones.

## Jay format
```
  "Jay1\0\0\0\0"       -- 8 bytes
  [data section]       -- ...
  [meta section]       -- <meta size>
  <meta size>          -- 8 bytes
  "\0\0\0\0Jay1"       -- 8 bytes
```
* The size of the file must be a multiple of 8 bytes, and all sections are aligned at 8-byte boundaries.
* The file begins and ends with `"Jay1"` string padded with 4 NUL bytes (`\0`). 
* Eight bytes before the last contain the size of the meta section (as an `int64` written in little-endian format). 
* The "meta section" is at the offset `16 + meta_size` from the end of the file, and it contains all meta information about the frame (including all column descriptors) serialized in Cap'n Proto format. 
* The portion of the file starting at offset 8 and ending at the beginning of the meta section is considered the data section. This section contains data buffers for each column. The exact location of each data buffer within the data section is stored in the meta section. The data buffers need not be adjacent to each other and are not necessarily stored in the same order as the columns themselves. However, each data buffer must be aligned at the 8-byte boundary.

## Saving a frame into a Jay file
* Create a "meta info" Cap'n Proto object
* For each column in the frame, write its buffers into the file, and its meta information into the meta object (including the locations of each buffer).
* Once all columns are written, write the meta object into the file
* Write the size of the meta, and the final signature.

## Opening a Jay file
* Open the file and verify its "Jay1" signatures at the beginning/end
* Read the meta size at the end of the file.
* Read the meta object with the information about the frame and all columns.
* At this point there are 2 choices: we can either memmap the entire file, and create each Column object as a subview into the large memmapped region, or memmap each portion of the file into a separate lazy column (similar how we do with NFF).

## Additional remarks
* This proposal does not yet specify the exact structure of the meta information, but generally it will follow the internal representation of the `DataTable` object.
* #1054 is a pre-requisite.
* #958 seeks to change the internal representation of string columns, and is better to do together with the switch to Jay, so as to avoid supporting too many different formats at the same time.
* New functionality will be exposed via standard `dt.open()` / `Frame.save()`. Ability to open NFF format will still be available for some time with `dt.open_nff()`.
* Issue #112 will become irrelevant.

**Comment by mmalohlava** [comment]
Questions:
  - Will a single file cause bottleneck? For example, if you are storing columns (data-section) in sequence, mmap the file and  start accessing all of them in parallel, that will cause lot of page-misses. 
  - Did you think about vertical splitting (having blocks per set of rows,  each block ended by a meta-section)?
  - What file sizes are you targeting?

**Comment by st-pasha** [comment]
@mmalohlava 
1. Indeed, if there are many columns and all of them are accessed at once, then we will have many memory page misses. However this would be true for the old NFF format too: if every column is in a separate file, and you access all those columns at once, then each of those files will also be a page miss. If anything, the Jay format has a benefit here: if the number of rows is small then several columns have a chance of residing in the same memory page, whereas NFF does not have this advantage.

2. Vertical splitting is an approach used in Arrow and Parquet and other formats. However, I don't see what the advantages would be, and how they can outweigh the costs of such approach. The cost will be that we no longer have a `Column` as a contiguous region of memory, but instead it will be a chunked structure. This means that in order to access any element of the array, it has to be located within the chunk index first.
In theory, we could have data chunked on disk, and then reconstructed back into a contiguous range through careful memory-mapping, but this again brings back the problem of having too many memory-mapped regions at once, which we know causes problems...

3. Any. We are not going to support FAT32, so there is really no upper limit on a file size. In fact Jay file will take less space on disk compared to NFF, because the latter has many files each possibly wasting some disk space due to real file sizes being usually greater than the visible file size.

**Comment by mmalohlava** [comment]
@st-pasha 

1. good point - so what will be your file-access pattern for Jay file - mmap full file, random access in parallel? I am just curious.

2. makes sense. Regarding vertical blocks - vertical splitting supports addition + you can apply cheap (from CPU perspective) compression schemas per partition if necessary. On the other hand, most of systems avoid addition, instead they generate a new file.

3. there is always a limit :) - but ok, no file size expectations

**Comment by mattdowle** [comment]
One advantage of NFF (one file per column) is that columns can be added and deleted very easily and robustly. It's easy and robust because there is no file format to navigate, hence the name NFF. Sharding by directory enables historical data to be locked down read-only while a new directory is added safely for each new day of data (50GB/day in my experience). Such datasets are not moved around from machine to machine; it's not whether it's multiple files or one big file that prevents people from transferring the data, but the shear size of the data.   For small datasets, a tar file is no different from one big file.

What seems to be driving this change is data with very large number of columns (>10,000). Points 2-5 are the same point about that. But really, are very very wide datasets like this needed to be out-of-memory?  I'm more used to database storage where data is stored in normal format : tall and skinny.  I doubt you would ever see a (reasonable) SQL database containing a table of more than 1000 columns.  It's more common to add or remove columns from an existing very large database (many billions of rows, under 10,000 columns) and at risky times like that it's really advantageous to have no-format.

If it's going to be one-big-file, why (to predict comments from community) "yet another different proprietary format from a startup that might disappear one day, and not Arrow or Parquet"?

**Comment by jangorecki** [comment]
> One advantage of NFF (one file per column) is that columns can be added and deleted very easily and robustly.

This kind of model is even used in databases and is called 6NF (6th normal form). Ability to add/delete columns without altering table object is called _non destructive schema evolution_ and is crucial feature of Anchor Modeling (6NF design technique). A quote from wikipedia:
> Anchor modeling is an agile database modeling technique suited for information that changes over time both in structure and content.

When switching to single file model we are losing this ability.
@stephlocke is expert on that :)

---

I also agree that thousands of columns are not that common cases in SQL RDBMS, from my experience in big warehouses I was having 200-1000 columns. When having more then better to melt your data and transform columns into rows to process by group.
I can imaging there are use cases in ML where you need to have as _flat_ data as possible, like _one-hot encoding_. This justify to implement efficient backend for big amounts of columns, but at the same time I don't think it make sense to drop existing __"no format"__ model.

---

Before making decisions it will be best to see benchmark of both.

**Comment by st-pasha** [comment]
Adding columns to a Jay file is very easy: just append the content at the tail of the file, and write the new metadata. (In NFF format, you'd also need to create a new file, and then write the new metadata file).
Removing a column is more complicated unless you're ok with having gaps in the file - in which case you can simply delete the column from the metadata and possibly 0-out the content.

**Comment by st-pasha** [comment]
@mattdowle 
> why (to predict comments from community) "yet another different proprietary format from a startup that might disappear one day, and not Arrow or Parquet"

The main requirement to our format (both NFF and Jay) is that the data was stored on disk in exactly same format as it exists in memory.

As such, we cannot use Parquet, which chunks and compresses its data -- loading data from such format would involve a decompression step. (And we don't want to store compressed data in memory either, since it would slow down and complicate most algorithms).

Arrow is ideologically right for us, however the format does not (yet) have features that we absolutely require: (1) 64-bit strings, and (2) inline NA values (Arrow stores all NAs as separate bitmask arrays). In datatable we have decided since the beginning that NAs will be stored in the same format as in R's data.table, and I still believe that was the right design choice. Perhaps one day Arrow will evolve sufficiently to support our needs -- however until then it's best to have our own format. I must note that Arrow does move in the right direction generally -- for example they added string columns (`Utf8`) not too long ago, which was peeve (3) in my list.

**Comment by pseudotensor** [comment]
My question would be what evidence is there that NFF is insufficient?   

https://github.com/h2oai/datatable/issues/1130 is an example of where there's nothing wrong with NFF, just its use of it.

Is there an actual practical case where dt is currently slow and one can justify and estimate that the overhead is a problem?  The ncols>>nrows case with row data size of <4096 bytes each column is one, but highly unusual.

For ncols~10,000 (let's say that's goal), too many files is maybe a problem, maybe not.  If there is a performance measurement of how the OS is sluggish, it would be good to see.  I would expect a cached OS file op should be no slower than a fork at 1E-6s or so, so isn't normally a problem.

**Comment by st-pasha** [comment]
@pseudotensor 
Here's an attempt to measure the effect, creating a 3x10000 Frame and then saving it either as CSV or as NFF:
```
>>> from time import time
>>> import datatable as dt
>>> d0 = dt.Frame([[1, 2, 3]] * 10000)
>>> d0.shape
(3, 10000)

>>> t0 = time(); d0.save("tmp1"); print(time() - t0)
1.5782227516174316
>>> t0 = time(); d0.to_csv("tmp1.csv"); print(time() - t0)
0.007846832275390625

>>> t0 = time(); d1 = dt.open("tmp1"); print(time() - t0)
0.06298303604125977
>>> t0 = time(); d2 = dt.fread("tmp1.csv"); print(time() - t0)
0.05060100555419922

>>> t0 = time(); d1s = d1.sum(); print(time() - t0)
0.298875093460083
>>> t0 = time(); d2s = d2.sum(); print(time() - t0)
0.07732033729553223
```
As you can see, saving an NFF file takes MUCH longer than saving corresponding CSV (and presumably saving Jay would be as fast as CSV or even faster). Reading NFF is only slightly slower than reading CSV -- but that's mostly because NFF is lazy and does not memmap individual files until they are needed (and with #1130 it'll probably get even faster). Once they're forced to be opened -- NFF is again much slower than CSV.

**Comment by st-pasha** [comment]
@pseudotensor  @arno
However the primary driving force for the Jay format is not that of efficiency (for "normal" use cases efficiency gains are expected to be minimal). 

The main reason I want Jay to be implemented is that of stability. As we have seen in many issues already, the architecture that relies on having thousands or tens of thousands of memory map regions to be opened at once is just too fragile. We have so far found ways to deal with the problems and implement some stop-gap measures, but those measures are not a substitute for a reliable solution.

To be more specific, the measures that are currently in-place are the following: (1) if a memory-map fails due to a system limit, we *unmap* some of the older mem-mapped file, hoping that that file won't be needed at least in the near future; (2) when a memory allocation fails in some other part of the system, try to do the same unmapping trick, because apparently regular memory allocations sometimes require to memmap something internally. Neither of these is a reliable solution: the first one is built on hope, the second works only for memory allocations done in datatable, but memory allocations done in any other part of the system (in C++ core, in Python, in other libraries, etc) are simply not aware of it.

The concrete example(s) when the current system fails is any situation when you have many columns and you need to access them all at once, probably in a row-by-row fashion. Such use cases could be: writing the frame into a csv file, performing data aggregation for vis-data-server, converting the entire frame into pandas/ numpy, passing the frame to xgboost, etc.

With Jay I expect most of these problems would go away, simply because instead of tens of thousands of memmap regions, you'll have only tens of them. And that will make all the difference in the world.

**Comment by pseudotensor** [comment]
I agree, once one is over 1000 columns nff is too ridiculous as far as relying upon the file system to manage things.
