### ISSUE TITLE
Datatable creation method with dict of numpy arrays has unintuitive behavior

### ISSUE THREAD

**Issue by aschmu** [h2oai/datatable#1113]
Maybe I haven't looked hard enough but it seems like the following doesn't do as one would expect : 

    import datatable as dt
    df = dt.Frame({'a': np.random.randint(0, 100, size=1000), 'b': np.random.choice(['a', 'b', 'c'], size=1000, replace=True)})

This creates a 2 x 1 datatable instead of a 1000 by 2 table. Maybe this is expected behavior, but wouldn't be nice to have something that's closer to the initializer with a dict of lists ?

Contrast with 

    df = dt.Frame({'a': np.random.randint(0, 100, size=1000).tolist(), 'b': np.random.choice(['a', 'b', 'c'], size=1000, replace=True).tolist()})

The former API would also be closer to pandas DataFrames init method.

**Comment by st-pasha** [comment]
Yes, I totally agree that current behavior is not very useful.
In fact, we already spotted this problem several days ago and it is on our TODO list: #1104.
