### ISSUE TITLE
Support datatable on Windows

### ISSUE THREAD

**Issue by chrinide** [h2oai/datatable#1114]
How about Windows support? Win7 & Win10

**Comment by st-pasha** [comment]
We are planning to start building pre-compiled datatable binaries for Windows platform in the near future. Currently, the hold-up is the lack of Windows machines in our testing framework. However, it should be possible to use a virtual machine to run a Windows container; @mmalohlava may give more details.

In the meanwhile, you can try building the package yourself from source, following the build instructions in the README. The steps should be exactly the same: download Clang/LLVM-6 C++ compiler, set up environment variables and run `make`. (You may need to install `make` tool too).

**Comment by abal5** [comment]
I'll start working on a Win 7 and Win 10 build using appveyor and see what is required.

**Comment by wtcooper** [comment]
I attempted to get this running on Win 10 but it quickly starting going down a rabbit hole...  The downloadable pre-built binaries (http://releases.llvm.org/download.html) didn't appear to work, apparently they are missing some components when I attempted to finish the build instructions.  I then attempted to build clang and llvm from scratch via MSVS, that ran for about 2hrs and then blue screened my machine before finishing.  It also appears llvmlite may need built from source, and it's unclear to me if the conda builds include clang+llvm.  Suffice to say i'm confused after spending half a day on it, any automated building you could do on your end for a quick pip install in Windows would be ideal.

**Comment by Cheburusska** [comment]
I also tried to build on windows using Cygwin but also without success. @abal5  is there any progress on Windows support. Maybe some manual?

**Comment by guyko81** [comment]
Hi, I'm very excited about this package, would be great to use under Windows! Any update on this?

**Comment by harlecin** [comment]
This package sounds awesome:) Windows support would be great, at work we have to use Windows quite a lot

**Comment by Sateesh110** [comment]
This package will save time. Can you please release window's version. Thank you.

**Comment by httassadar** [comment]
Have been waiting for over a year... any update on this? Thanks.
