### ISSUE TITLE
fix memory leak during grouping operations

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#1115]
Currently datatable eats quote a lot of memory **comparing to R solutions**. It is most probably result of R global string cache, but memory efficiency should be addressed anyway.
![groupby-memtest](https://user-images.githubusercontent.com/3627377/41434613-a4bb15c8-701c-11e8-9707-f989d11dd262.png)
Plot produced on 419e93e7b0c610d2581bfb20ba83f3da7198931e

**Comment by st-pasha** [comment]
I'm not sure I understand what is being measured here. 
Is it total memory size at the end of each run? or the difference between memory size before and after each task?

Generally, `datatable` uses standard C calls `malloc()` and `free()` -- however `free` may not return the memory to the OS, but merely mark it as unused. And unfortunately `gc.collect()` would not be helpful here either. This would cause the memory usage measurements to be artificially inflated.

Another problem here is that what we want to measure is the maximum memory usage during the calculation. I.e. if any process takes many GBs while running, but then its memory consumption goes down at the end -- we want to know how much memory was used at a peak of memory consumption.

Also, when you say "datatable eats quite a lot of memory compared to R", I wonder whether you noticed that the Y axis doesn't start at 0, and the actual difference is something like 10-20%.

Still, I don't quite understand what it means for the memory consumption to go up after each run -- could this possibly be an indicator of a memory leak?

**Comment by jangorecki** [comment]
just snapshots of `ps -o rss`.
before each query there is `gc.collect()` and after each query
```py
process = psutil.Process(os.getpid())
process.memory_info().rss/(1024**3) # GB units
```

**Comment by jangorecki** [comment]
it looks much better with y axis from 0:
![groupby-memtest](https://user-images.githubusercontent.com/3627377/41456038-995b52ac-707f-11e8-9dff-ac9da87df3a8.png)

**Comment by st-pasha** [comment]
I just ran a groupby operation 1000 times, and indeed memory usage keeps growing and growing -- so definitely a leak.
