### ISSUE TITLE
Error message shows that "image not found" after import datatable

### ISSUE THREAD

**Issue by avalonliberty** [h2oai/datatable#1194]
- Did you find a bug in datatable, or maybe the bug found you?
   Tell us what it is.

I have followed the official building instruction and installed LLVM correctly. The installation of datatable package is also correct. Though, I face some trouble to use datatable module, since the error occurs after importing datatable.

- How to reproduce the bug?
   **This part is the most important**. Please provide a code snippet which, when executed in console,
   demonstrates the problem. If necessary, attach any data files to the issue.

The error occurs after typing "import datatable"

The message below is the error message which pops out after calling package
Traceback (most recent call last):

  File "<ipython-input-1-bed8639e44cf>", line 1, in <module>
    import datatable

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datatable/__init__.py", line 8, in <module>
    from datatable.graph.dtproxy import f

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datatable/graph/__init__.py", line 8, in <module>
    from .rows_node import AllRFNode, SortedRFNode

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datatable/graph/rows_node.py", line 10, in <module>
    from datatable.lib import core

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datatable/lib/__init__.py", line 9, in <module>
    from . import _datatable as core

ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datatable/lib/_datatable.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/llvm/lib/libomp.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datatable/lib/_datatable.cpython-37m-darwin.so
  Reason: image not found

- What was the expected behavior?
   In case it is not obvious, please tell us what result should your code produce.
It is supposed to be fine after importing package and return nothing.

- Your environment?
   What is your datatable version, python version, and operating system? 
datatable ver 0.6.0
python 3.7.0
OSX High Sierra 10.13.6
- Tag the issue with [bug] or [segfault] (depending on whether it crashes Python or not)
   Thank you for contributing, and sorry for any inconvenience...

**Comment by st-pasha** [comment]
It is not quite clear how this error could have arosen. Since you are on MacOS, please run the following from the command line:
```
otool -l /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datatable/lib/_datatable.cpython-37m-darwin.so
```
This will print you information about the library that was built. Of particular interest are entries containing `LC_LOAD_DYLIB` and mentioning `libomp.dylib`; and also `LC_RPATH`. On my machine the relevant sections look as follows:
```
Load command 9
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libomp.dylib (offset 24)
   time stamp 2 Wed Dec 31 16:00:02 1969
      current version 5.0.0
compatibility version 5.0.0
...
Load command 12
          cmd LC_RPATH
      cmdsize 32
         path @loader_path/. (offset 12)
```

What this means is that the package will try to load library `@rpath/libomp.dylib`, where `@rpath` is defined as `@loader_path/.`. Thus, the library is loaded from `@loader_path/libomp.dylib`, where `@loader_path` is the path of `_datatable.cpython-37m-darwin.so`.

**Comment by st-pasha** [comment]
If I understand correctly, you're building the package yourself, which means you're running `make` command at some point. If you could provide the console output of that command, it may help understand the problem.

In terms of resolving it, you may try the following steps:
- Find where the `libomp.dylib` library is on your system (usually it can be found at `{LLVM_INSTALLATION_FOLDER}/lib/libomp.dylib`)
- Copy or sym-link that library into `/usr/local/opt/llvm/lib/libomp.dylib`

If for some reason your llvm installation folder does not contain `libomp.dylib`, then either you have a corrupt or very old llvm library. You can check the version with `{LLVM_INSTALLATION_FOLDER}/bin/llvm-config --version`.

**Comment by st-pasha** [comment]
It should also be noted that Python 3.7 was released only a month ago, we have not yet had a chance of testing `datatable` with it. Your best bet would be setting up a virtual environment with Python 3.6 and then pip-installing pre-built datatable for it.

**Comment by avalonliberty** [comment]
Ahh sir, I have downgraded my python to version 3.6 and install the llvm via brew instead of downloading binary from the official website directly. The issue does not occur after I complete the aforementioned procedures. It seems that it just merely the issue of wrong file path. Thanks for your help

**Comment by st-pasha** [comment]
Glad it all worked out for you!
