### ISSUE TITLE
Implement pandas-like .replace

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/datatable#1302]
https://github.com/h2oai/datatable/issues/1127#issuecomment-400778330

Otherwise, when an inf or other item exists in dt frame, we have to go to pandas, do the .replace, and then push the column back into the dt frame.  This ends-up adding an enormous amount of code (about 1000 lines of code in DAI) that would be eliminated.

**Comment by pseudotensor** [comment]
Example code this would replace:

```
    tr = dt.Frame(train_dt)
    to_delete = []
    for c in tr.names:
        if tr[c].ltypes[0] == dt.ltype.obj:
            try:
                tr = set_dt_col(tr, c, tr[c].topandas().astype('str', errors='raise'))
            except:
                loggerdata(logger, "Dropping object column from the training data: %s" % c)
                to_delete.append(c)
        elif tr[c].min1() == -np.inf or tr[c].max1() == np.inf:
            loggerdata(logger, "Replacing inf/-inf with nan in the training data for column: %s" % c)
            tr = set_dt_col(tr, c, tr[c].topandas().replace([np.inf, -np.inf], np.nan))
    if len(to_delete) > 0:
        del tr[:, to_delete]

    return tr
```

**Comment by pseudotensor** [comment]
So 2 functions:
1) Replace object columns as string if can
2) Replace inf with nan
3) Replace any other value with any other value.

Otherwise, pandas uses alot of memory and is slow.

**Comment by st-pasha** [comment]
"Replace object columns as string if can" seems like a completely separate functionality, more similar to type-cast. And we need to specify what "if can" actually means.

**Comment by pseudotensor** [comment]
Hi @st-pasha , any time-line for this?  Would be great to generally solve this problem that seems to be (when using pandas) blowing-up memory alot.  Thanks! :)

**Comment by st-pasha** [comment]
I'm considering to implement the following API (similar to pandas):
```python
DT.replace(x, y)        # replace value x with y
DT.replace([xs], y)     # replace any of the of xs with y
DT.replace([xs], [ys])  # replace any of the xs with the corresponding ys
DT.replace({xs: ys})    # replace any of the xs with the corresponding ys
```

**Comment by st-pasha** [comment]
@pseudotensor Yes, it should cover it.

**Comment by st-pasha** [comment]
An alternative form of `replace` that we can consider for the future API (not within the scope of this issue) is a single-column `replace` applied to `ColSelector` objects:
```
DT[:, update(A = f.A.replace(x1, y1),
             B = f.B.replace(x2, y2))]
```
This would give us flexibility to apply different replacements to different columns, limit to a certain sub-range of rows, use expressions as replacement values, combine with groupby / join operators, etc.

**Comment by st-pasha** [comment]
One other thing: I do not currently plan to support replacement with type changes. That is, it would be illegal to replace an integer value with a float, or a float with a string, or a string with an int.

**Comment by pseudotensor** [comment]
What fubction does target encoding require to replace a string with some target value?

**Comment by st-pasha** [comment]
Target encoding uses a different mechanism: join to an auxiliary frame, and pull values from this it. This approach is more suitable when there are many different values to replace.
