### ISSUE TITLE
Python 3.7 Support 

### ISSUE THREAD

**Issue by govi218** [h2oai/datatable#1309]
Datatable currently does not support Python 3.7; is it possible for it to be supported soon? Otherwise it would be necessary to have a venv for 3.6 which complicates stack

**Comment by st-pasha** [comment]
Datatable is supposed to work under py 3.7, see issues #1197 and #1123. We are running the entire test suite under py3.7 regularly, as can be seen for example here: https://github.com/h2oai/datatable/blob/master/ci/Jenkinsfile.groovy#L322

Please let us know what made you think that py3.7 is not supported: is it written somewhere in the docs? do you run into some error under py3.7? anything else?

**Comment by govi218** [comment]
Thanks for the response, I was not able to find a download for 3.7 but it turns out that I missed the build instructions!
