### ISSUE TITLE
Add ability to select all but a few given columns from a Frame

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1317]
Suppose you have a frame, and you want to select all columns except "foo" and "bar". Currently, you'd need to use a comprehension of the form
```
DT[:, [n for n in DT.names if n not in ("foo", "bar")]]
```
A nicer syntax would be to treat `f` as a collection of all columns in the frame, and then write
```
DT[:, f - ["foo", "bar"]]
```
Similarly, if one wanted to select all columns, but then also some extra, then the syntax could for example be
```
DT[:, f + [mean("foo")]]
```

**Comment by mattdowle** [comment]
@sritchie73  or more simply :  
```
> dt <- data.table(a = 1, b = 2, c = 3, d = 4)
> dt[, -c("b","d")]
       a     c
   <num> <num>
1:     1     3
```

**Comment by st-pasha** [comment]
We can't do `DT[:, -["b", "d"]]` in python, because it tries to evaluate the expression `-["b", "d"]` first and fails because there is no such thing as a "negative list".
On the other hand `DT[:, f - ["b", "d"]]` can work because in this case we are subtracting a list from a custom object `f`, and if the object has defined the subtraction operation then we can subtract whatever we want...
