### ISSUE TITLE
Question: documentation and/or examples

### ISSUE THREAD

**Issue by javadba** [h2oai/datatable#1318]
I can't jump into a pandas replacement without knowing what is/is not supported - and how to do so.

thanks.

**Comment by st-pasha** [comment]
Improving the documentation is definitely on our TODO list.
Thanks to your question, we'll be able to move it up the priority list.

**Comment by javadba** [comment]
thx!  the docs are v helpful!  i'm excited about this project: will convert my pandas stuff starting tonight.

**Comment by javadba** [comment]
If you might point to further examples it would be great: but in any case the summary provided should be enough to get started. I will close issue now.
