### ISSUE TITLE
Build failed on Manjaro Linux (based on Arch Linux) using clang 5 or 6

### ISSUE THREAD

**Issue by stucash** [h2oai/datatable#1341]
Hi Guys, I think it is probably making more sense to ask this question here as I don't think it is just a random build error.

I am on Manjaro Linux 17.1.12 with Gnome as front end, I am using Python 3.7. Please comment below if you need more specific machine details.

I started off, as instructed, setting LLVM6 env variable and run `pip3 install datatable`. 

I also tried using the build instruction by doing `make build` first, leading to the same error below.

I have tried `Clang 5`, `Clang 5.0.1`,  `Clang 6.0.0`, all of which didn't work. 

errors are simple, it's pointing to missing libtinfo.so.5 which on my system there's only a libtinfo.so.6 existed and symlink wouldn't do the job either. 

Do I miss anything here?

**Comment by st-pasha** [comment]
I'm unclear from your description: does the error occur when compiling the code, when linking, or when actually running the module in python?
If it is during linking, take a close look at the command that is run last during `make build`. On my machine it looks like this:

> /Users/pasha/llvm-6.0.0/bin/clang++ -isystem /Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -bundle -undefined dynamic_lookup -g -m64 -m64 ...... -o build/lib.macosx-10.6-intel-3.6/datatable/lib/_datatable.cpython-36m-darwin.so -L/Users/pasha/llvm-6.0.0/lib -Wl,-rpath,@loader_path/. -fopenmp -s

(where `...` contains all .o files in build/temp.macosx-10.6-intel-3.6/ directory). This contains the path(s) where the libraries will be looked up during linking.

**Comment by stucash** [comment]
@st-pasha I am not quite sure what was not clear in the description above but it was during compiling (a.k.a building using your build instruction). 

I also tried:
1. set LLVM5 or LLVM6 in my bash profile.
1. at terminal do `pip3 install datatable`
2. terminal showed error above.

As simple as that; I understand probably from your perspective it might sounds like different matter, but it is not, it is really just this. I can't even compile/build it. 

I also tried just now in Elementary OS by:

1. sudo apt install llvm-5.0
2. set LLVM5 env var in my profile
3. at terminal do `pip3 install datatable`
4. terminal showed error:     

> FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/llvm-5.0/lib/libomp.so'

it's a different error which might be resolved by installing the required lib but still, the installation has proved itself quite troublesome already in linux environment. 

However I think it's mainly clang/llvm not datatable, but probably we could preempt somehow from datatable perspective?

**Comment by stucash** [comment]
@st-pasha ok I just get it sorted. it did seem to be some linking problem, but the limited information provied error message wouldn't help to diagnose. 

for Elementary OS (I would say for typical Ubuntu based systems), at least the following information is needed in the bash profile (either `.bash_profile` or `.profile`):

> LD_LIBRARY_PATH="$LD_LIBRARY_PATH:your/path/to/clang+llvm/lib"
> LLVM6="your/path/to/clang+llvm/root/directory"

**Comment by st-pasha** [comment]
The libtinfo5 mystery is puzzling. I wonder if you get any error when running
```
$ python -c 'import curses'
```
There is a [forum thread](https://forums.opensuse.org/showthread.php/446927-missing-library-libtinfo-so-5) which suggests that the error might be related to the "ncurses" system library.

**Comment by st-pasha** [comment]
There were recent changes to simplify the build process; if you still have any problems please try it. 
Closing this issue, as there are no actionable items here.
