### ISSUE TITLE
Segfault when attempting to sort a multi-column frame without passing any arguments

### ISSUE THREAD

**Issue by nkalonia1** [h2oai/datatable#1354]
```
>>> f
      a   b
---  --  --
 0    1   3
 1    2   9
 2    3   4

[3 rows x 2 columns]

>>> f.sort()
Segmentation fault: 11
```
`f.sort()` is still an invalid function call and should raise an exception instead

**Comment by nkalonia1** [comment]
Also segfaults on single-column frames. I would say that in this case the sort should succeed.
```
>>> f["b"].sort()
Segmentation fault: 11
```

**Comment by st-pasha** [comment]
We could default sorting by all columns if no arguments passed.
This would be consistent with base python too
