### ISSUE TITLE
Ability to Determine Differences in Levels Between Two Columns

### ISSUE THREAD

**Issue by meganjkurka** [h2oai/datatable#1356]
Add the ability to determine the difference between unique values of two different columns.  This would be helpful to see if there are any new values in a column between training and testing.

This can be done in Python with the following code: 

```
set(df1["A"]) - set(df2["A"])
```
cc @laurendiperna

**Comment by st-pasha** [comment]
@meganjkurka Is there a specific time frame for this request?

**Comment by meganjkurka** [comment]
Ideally by December.
