### ISSUE TITLE
Make datatable compile with MSVC

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1369]
This is a prerequisite for #1114 

Currently, there seems to be multiple compilation issues, including MSVC [not working properly with macros](https://blogs.msdn.microsoft.com/vcblog/2018/07/06/msvc-preprocessor-progress-towards-conformance/), and also lack of `sys/mman.h` library on windows (for memory-mapping)

**Comment by thirdwing** [comment]
In case of `sys/mman.h`, there is a Windows version used in feather: https://github.com/wesm/feather/blob/master/cpp/src/feather/mman.h

**Comment by dmillar** [comment]
What is the status of this issue? Is this being actively worked on? If not, I'd like to take a crack at getting datatable to compile on Windows. MSVC if possible, but also open to mingw and clang/llvm Windows implementations. VS2019 seems to have introduced better adherence to the standard, and might make this task a bit easier. Though, at first thought I'd probably want to use CMake to build. Thoughts on approach, known issues?
