### ISSUE TITLE
Exposing C APIs

### ISSUE THREAD

**Issue by thirdwing** [h2oai/datatable#1382]
As I understand, the C APIs are not exposed.

I think there are at least two steps to expose the C APIs:

1. installing the header files, like `numpy/core/include`

2. providing utility functions, like `numpy.get_include()`

**Comment by st-pasha** [comment]
We don't have any C APIs because nobody yet requested any functionality to be exposed. Do you have any specific functionality in mind? Is there any specific function/method/object you want to interact with? Do you want that functionality to be available to C code, C++ code, or to Python?

**Comment by st-pasha** [comment]
DataTable (internals + convert to/from PyObject)
Column (internals + create)
ABI version number
Ship the api.h file(s) with the distribution, and make it findable
