### ISSUE TITLE
Allow for an arbitrary feature interactions in FTRL algo

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#1397]
For the moment there is an argument `inter` that controls if 2-nd order feature interaction should be used for learning or not. When number of features is large, doing full 2-nd order interaction is not practical, as it scales with `n_features^2`. Instead, we can allow for a way to learn only for "interesting" feature combinations, may be even for the orders higher than 2.

**Comment by suresh-chinta** [comment]
Hi, thanks for the package, can you please help me how to set interaction and regularization params for training and testing. Is this correct usage, ftrl = Ftrl(nepochs=2, inter=True, l1=0.01)

**Comment by st-pasha** [comment]
The available parameters of FTRL model are:
```
>>> dt.models.Ftrl().params
FtrlParams(alpha=0.005, beta=1.0, lambda1=0.0, lambda2=1.0, d=1000000, nepochs=1, inter=False)
```

**Comment by suresh-chinta** [comment]
Thank you.
