### ISSUE TITLE
Why are releases so infrequent?

### ISSUE THREAD

**Issue by javadba** [h2oai/datatable#1398]
There are _many_ features added since 0.6.0 - which was released over five months ago.  While I am trying to struggle through building this on my own it will not be possible to expect that to be done for others who might use my code.  Such an infrequent release schedule compromises usability.

Is there a reason the releases could not occur in  a more timely manner?

**Comment by mattdowle** [comment]
Also is there an ETA for Windows binary on `pip`?  I was asked that in London and wasn't sure of the proper response.

It would be great to see a status table of tests on each platform too, like the R data.table one from CRAN :
![image](https://user-images.githubusercontent.com/2779998/48375747-bc583d00-e67d-11e8-950b-d37d7bd1f31d.png)


(It's currently in error status on Windows oldrel which is a resource issue on that machine I think. I've contacted the Windows CRAN maintainer about that).

**Comment by st-pasha** [comment]
@javadba We will aim to make a release this week.

**Comment by javadba** [comment]
thx!

**Comment by mattdowle** [comment]
@st-pasha What about Windows ETA?

**Comment by st-pasha** [comment]
@mattdowle  There is issue #1114 to track the progress with Windows integration. Actual ETA is unclear since the scope of the issues that have to be resolved is unknown. We recently had some progress, in the form of PR #1371, but there are still outstanding problems.
