### ISSUE TITLE
Take care about FTRL model parameters

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#1425]
We can now get and set an FTRL model itself, i.e. vectors `z` and `n`. However, we also need to take care about the parameters we've used to train our model, i.e. `alpha`, `beta`, etc. We could use a Python tuple to get and set all of them at once, also there should be a way to relate the model itself with the set of parameters it was trained on.

**Comment by st-pasha** [comment]
Better use a namedtuple instead of a plain tuple.

**Comment by oleksiyskononenko** [comment]
Yes, that's what I thought. Can this be done with `py::otuple`? If not, what is the best way to do it from the current Python/C++ framework?

**Comment by st-pasha** [comment]
There isn't, you'll have to create it.
Currently, the only place where we create named tuples is [here](https://github.com/h2oai/datatable/blob/master/c/read/column.cc#L210-L243). However, that's not C++-ized. It's a good idea to create class `py::onamedtuple` anyways, since it will be needed in other places too.

**Comment by st-pasha** [comment]
We'll need named tuples in `Frame.to_namedtuples()` method, and also when returning parsing parameters from `fread`.

**Comment by oleksiyskononenko** [comment]
I tried to pass a namedtuple as an argument, and it seems like could read its data with`get_attr("key")`. But could find any way to output it. Now I see why :)

**Comment by st-pasha** [comment]
Btw, why we are on the topic of model parameters -- why not call them `alpha`, `beta`, `lambda1` and `lambda2` (instead of `a`, `b`, `l1` and `l2`)? I believe that's what they are called in the paper, so it will be easier for a user to understand what those parameters stand for

**Comment by oleksiyskononenko** [comment]
Yes, sure. I'm actually reviewing the naming (not only for parameters) to make it more intuitive, while working on this and several other issues.
