### ISSUE TITLE
replace method should throw exception when invalid replace value is used

### ISSUE THREAD

**Issue by nkalonia1** [h2oai/datatable#1432]
```
>>> d = dt.Frame(a=[1,2,3,None])
>>> d
      a
---  --
 0    1
 1    2
 2    3
 3     

[4 rows x 1 column]

>>> d.replace(None, 84.4)
>>> d
      a
---  --
 0    1
 1    2
 2    3
 3     

[4 rows x 1 column]

>>> d.replace(None, 84)
>>> d
      a
---  --
 0    1
 1    2
 2    3
 3   84

[4 rows x 1 column]
```

I would expect some kind of error output when calling `d.replace(None, 84.4)`, as row 3 satisfies the replacement criteria but the replacement value is invalid.

**Comment by st-pasha** [comment]
`DT.replace(a, b)` will throw an error if the types of `a` and `b` do not match. For example, replacing a float with an int, or an int with a string. At the same time, `None` is special in that it "matches" any type. Thus, you can replace a `None` with an int, or a float, or a string; or conversely, an int, a float, or a string can be replaced with `None`.

Also, the expression `DT.replace(a, b)` will only affect columns of the same type as `a` and `b` in the frame `DT`. All other columns will be skipped. This means that `DT.replace(None, 84)` will only look at integer columns, and within those replace NA values with 84. Similarly, `DT.replace(None, 84.4)` only applies to real columns, and for those columns, the NA values will be replaced with 84.4. If there are no real columns in the frame `DT`, then nothing will be replaced.

Generally, a single `replace()` call can look at multiple tokens at the same time. Thus, you can write `DT.replace(None, [84, 84.0, "eighty-four"])`, which would mean "replace NA values in integer columns with 84, in real columns with 84.0, and in string columns with string 'eighty-four'".
