### ISSUE TITLE
dt.open could have option to persist frame in memory

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#1467]
same as `.persist()` to memory in spark

**Comment by st-pasha** [comment]
I'm thinking it's better to leave `dt.open()` as-is, but instead create a new method `Frame.to_memory()` which would load an existing (already opened) memory-mapped frame into the RAM. This achieves more flexibility: you can first open the frame, inspect it, drop some columns, select certain rows, and only then bring it into memory. A mere flag to `dt.open()` would not allow any of that.
