### ISSUE TITLE
Add support for pickling datatable.core.Ftrl objects

### ISSUE THREAD

**Issue by arnocandel** [h2oai/datatable#1476]
`TypeError: can't pickle datatable.core.Ftrl objects`

**Comment by oleksiyskononenko** [comment]
If you urgently need it, you can pickle `ft.model` (that is essentially a datatable frame) and `ft.params` (that is a Python namedtuple) separately. After unpickling, one can assign model and parameters to an existing `Ftrl` object as `ft.model = unpickled_model` and `ft.params = unpickled_params`. 

Will work on support to pickle the whole object.

**Comment by st-pasha** [comment]
@oleksiyskononenko See https://github.com/h2oai/datatable/blob/master/c/frame/__init__.cc#L681-L723 for an example.
