### ISSUE TITLE
segfault in row slicing

### ISSUE THREAD

**Issue by arnocandel** [h2oai/datatable#1487]
build 411 dbf2ba6160fcb881b8e88bae24ba7138982c684a http://mr-0xc1:8080/view/DataTable/job/h2o-py-data-table/job/master/411/
```
import pickle
import datatable as dt
data = dt.open('data.jay')
idx = pickle.load(open('indices.pkl', 'rb'))
data[idx, :]
```
`Segmentation fault (core dumped)`
[segfault.zip](https://github.com/h2oai/datatable/files/2688179/segfault.zip)

**Comment by st-pasha** [comment]
reproduces on MacOS
