### ISSUE TITLE
Native Python vs Jupyter with datatable

### ISSUE THREAD

**Issue by rafagonigon** [h2oai/datatable#1492]
- Did you find a bug in datatable, or maybe the bug found you?
I tried to run the examples shown in documentation and filtering didn't work in jupyter, but it did in python run from terminal.
In jupyter it doesn't select the rows but just the number of rows fullfilling the filter condition

- How to reproduce the bug?
 import datatable as dt
from  datatable import f
import numpy as np
np.random.seed(1)
tabla = dt.Frame({"x":np.random.randn(1000),"y":np.random.randn(1000),"A":np.random.randn(1000)})

tabla=dt.Frame({"n": [1, 3,5,6,7,8,9,0,1,3,5,2,65,26], "s": ["foo", "a","bar","a","b","c","d","e","f","g","h","i","j","k"]})
tabla

tabla[f.n>1,:]
table[f.n==1,:]

- What was the expected behavior?
The answer given in terminal for the last filter is:
>>> tabla[f.n==1,:]
      n  s  
---  --  ---
 0    1  foo
 1    1  f  

- Your environment?
  Ubuntu 16.04
datatable 0.7.0
notebook 5.4.0
python 3.6.4

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).
`[bug]`

- Thank you for contributing, and sorry for the inconvenience.

**Comment by st-pasha** [comment]
Sorry that you encountered this. This issue was already reported, and resolved: see #1475, #1448.
You'll need to install the latest dev version to get the fix, however. Or, wait until release 0.8.0, which should happen by the end of the month.
