### ISSUE TITLE
Problem on usage of C API on Linux machine

### ISSUE THREAD

**Issue by thirdwing** [h2oai/datatable#1504]
I met a problem of using C API on Linux machine.

A reproducible example can be found by: https://github.com/thirdwing/datatable-c-api-example

It works well on OSX machine, but not on Linux machine.

Can you provide some suggestions?

**Comment by st-pasha** [comment]
I don't think your problem is related to `datatable`. The error occurs during import of `example` module, before executing the `example.nrow()` function. This suggests compilation/linking issues. Check that the compilation flags on your "example" module request dynamic linking.

**Comment by thirdwing** [comment]
Maybe my understanding is wrong.

The compiling and liking options are set by setuptools on Linux and OSX.

They are working well on OSX.

The compiler output on Linux are shown below:

```
building 'example' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/root/c_api_test/include/site/python3.6 -Idatatable/datatable/include -I/usr/include/python3.6m -I/root/c_api_test/include/python3.6m -c src/example.cc -o build/temp.linux-x86_64-3.6/src/example.o -std=c++11
creating build/lib.linux-x86_64-3.6
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/src/example.o -o build/lib.linux-x86_64-3.6/example.cpython-36m-x86_64-linux-gnu.so
```

Can you tell me which options I should add?
