### ISSUE TITLE
TypeError: 'ColSelectorExpr' object is not iterable

### ISSUE THREAD

**Issue by rahimramezanian** [h2oai/datatable#1506]
**Problem**:

I read a csv file and when I want to do groupby I get the error
```
df(select=max(dt.f.device),groupby=device)

TypeError: 'ColSelectorExpr' object is not iterable
```

where `device` and `device` are columns of the table and their type is stype.int32.

**Versions**:

datatable==0.7.0, python version 3.5, Ubuntu Server 14.04

**Comment by st-pasha** [comment]
It seems you're using the built-in python `max` function, which doesn't know how to operate on column expressions. Instead you should be using the `dt.max()` function, which can also be safely imported (it will work like builtin `max()` for any input which is not a column expression). Thus:

```
import datatable as dt
from datatable import f, max, by
df = dt.Frame(devid=[1, 2, 2, 3, 1, 2, 3, 2], device=range(8))
df[:, max(f.device), by(f.devid)]
``` 
produces
```
     devid  V0
---  -----  --
 0       1   4
 1       2   7
 2       3   6

[3 rows x 2 columns]
```

I hope this resolves your problem, if not feel free to reopen.
