### ISSUE TITLE
can't replace inf and -inf anymore

### ISSUE THREAD

**Issue by arnocandel** [h2oai/datatable#1510]
```
import numpy as np
import datatable as dt
t = dt.Frame([np.inf])
t.replace('inf', None)
print(t.to_list())
```
`[[inf]]` instead of `[[None]]`, and same for `-inf`. Note that we can't use `np.inf` in the `replace_what`, but even that doesn't work.

```
import numpy as np
import datatable as dt
t = dt.Frame([np.nan])
t.replace('nan', None)
print(t.to_list())
```
works as expected: `[[None]]`

**Comment by arnocandel** [comment]
same thing for:
```
t = dt.Frame([1.7976931348623157e+308])
t.replace('1.7976931348623157e+308', None)
print(t.to_list())
```

**Comment by st-pasha** [comment]
I made a PR with a fix; but bear in mind that you want to replace floats with floats. So:
```
DT.replace(math.inf, None)
DT.replace(1.7976931348623157e+308, None)
```

**Comment by arnocandel** [comment]
we're getting a list of missing_values from the config.toml in DAI, so can't really know whether it's a float or a string.

https://github.com/h2oai/h2oai/blob/dev/h2oaicore/config/config.toml#L290

'-1.7976931348623157e+308' and '-inf' still need to be added

**Comment by arnocandel** [comment]
```
(env) arno@ovaclokka:~/h2oai(dev)$ cat test.py
import numpy as np
import datatable as dt
t = dt.Frame([-np.inf])
t.replace('-inf', None)
print(t.to_list())
(env) arno@ovaclokka:~/h2oai(dev)$ python test.py 
[[-inf]]
```

**Comment by arnocandel** [comment]
This is the work-around btw: https://github.com/h2oai/h2oai/blob/509b81c26ff176a1056cb173662b27650142811a/h2oaicore/transformer_utils.py#L1338-L1345

**Comment by st-pasha** [comment]
You can use `fread` to parse the string values into the appropriate type. For example:
```python
assert isinstance(missing, list)
assert all(isinstance(x, str) for x in missing)
tmp = dt.fread(text=",".join(missing), na_strings=[], header=False).to_tuples()
assert len(tmp) == 1  # 1 row
DT.replace(tmp[0], None)
```
This can be written as a one-liner, if you want to.

**Comment by arnocandel** [comment]
The above no longer replaces the string `'inf'` with `None`, something that fread(na_string=['inf']) does.

**Comment by arnocandel** [comment]
I'll just do this for now:
https://github.com/h2oai/h2oai/blob/89abd08f615ae95832a69b8cf9dfd796fc302bcb/h2oaicore/transformer_utils.py#L1340-L1345
