### ISSUE TITLE
NotImplementedError: StringColumn::replace_values() not implemented

### ISSUE THREAD

**Issue by arnocandel** [h2oai/datatable#1523]
After refactor - this feature was lost, it seems. Needed for DAI.

**Comment by arnocandel** [comment]
https://github.com/h2oai/h2oai/issues/6271

**Comment by st-pasha** [comment]
It was never implemented, only now we started to throw a proper error: https://github.com/h2oai/datatable/commit/4c393351c1fb3372b0ffd2e16f9e115f5fd52f91#diff-7252009faeff84b6ca99ff2ace337bdf

Of course if DAI actually needs it, then we should go ahead and implement.

**Comment by arnocandel** [comment]
how come this works in 0.7.0.dev428
```
    table = dt.Frame(['hi'])
    table.replace(['hi'], 'boo')
    assert table[0, 0] == 'boo'
```
