### ISSUE TITLE
Remove dependency typesentry

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1535]
Module `typesentry` helps to check types in python. However, since we're slowly moving the majority of the code to C++, at this point we barely use that module at all. Removing it will make installation slightly easier, and reduce the startup overhead.

**Comment by igor-susic** [comment]
Hi @st-pasha, I started using `datatable` and really like it, better than `pandas` at least for me. Looking to help you guys, I feel this one would be ok to start contributing, is it ok by you guys?

**Comment by st-pasha** [comment]
@igor-susic Absolutely, go for it.

**Comment by st-pasha** [comment]
@igor-susic Hi Igor, I wonder if you're still interested in doing this? If not, that's perfectly fine -- just let us know so that someone else can pick up the task.

**Comment by igor-susic** [comment]
@st-pasha Yes, I'm still on it. Sorry, I was on vacation these holidays, otherwise, I would let you know sooner.
