### ISSUE TITLE
grouping on many columns needs a lot of memory

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#1541]
The following query fails to run on 125GB machine having 45GB input csv.
```py
x[:, {"v3": sum(f.v3), "count": count()}, by(f.id1, f.id2, f.id3, f.id4, f.id5, f.id6)]
```
script is `Killed` by OS which AFAIU means that OOM killer decided that python eats to much memory.

**Comment by st-pasha** [comment]
What are the types of columns `id1:id6`, and how many rows is there?
Also is there a way for you to see how much memory the process consumes before being killed?

**Comment by jangorecki** [comment]
id1:id3 are string, id4:id6 integer, 1e9 rows

**Comment by st-pasha** [comment]
Thanks @jangorecki, this is helpful. We'll need to profile the sort function carefully, and see what can be improved in terms of memory/CPU usage.

**Comment by jangorecki** [comment]
AFAIU this has been already resolved, it does not crash anymore.
Timing of such case could probably be improved, see very bottom bars at: https://h2oai.github.io/db-benchmark/groupby.html
closing as memory issue has been addressed.
