### ISSUE TITLE
onerow_in class should work properly in the presence of a groupby

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1584]
The `onerow_in` internal class selects a single row from a Frame. In the presence of a groupby, however, it is expected to select one row from each of the group.

I remain undecided on what to do in the event that the requested row does not exist in some of the groups. The possible strategies could be: (a) ignore those groups, (b) produce an NA row, (c) throw an error.

**Comment by XiaomoWu** [comment]
Personally, I prefer "(a) ignore those groups", which is consistent with `Rdatatable`.

```
dt = data.table(x=c(1, 2, 3), y = c('a', 'a', 'b'))
dt[, .SD[x==1], keyby=y]
y    x
--   --
'a'  1
# row "y==b" is not selected since it has no correspondent x that equals to 1

**Comment by st-pasha** [comment]
Thanks @XiaomoWu for sharing your feedback.

Here's my thought process on this topic:
First, in R selecting elements outside of the range of a vector is perfectly valid, and returns an `NA`. In this respect `data.table` follows the rules of the built-in R `data.frame`:
```
> DF = data.frame(x=c(1, 2, 3))
> DT = data.table(x=c(1, 2, 3))
> DF[5,]
[1] NA
> DT[5,]
    x
1: NA
```
Starting from this behavior, it would make sense to follow either (a) or (b) in the case when the same operation is applied for each group.

On the other hand, in Python selecting an element outside of the existing is generally considered a bad  thing, and results in an exception:
```
>>> p = [1, 2, 3]
>>> p[5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range

>>> DT = dt.Frame(p)
>>> DT[5, :]
ValueError: Row 5 is invalid for a frame with 3 rows

>>> DF = pd.DataFrame(p)
>>> DF.iloc[5, :]
IndexError: single positional indexer is out-of-bounds

>>> a = np.array(p)
>>> a[5]
IndexError: index 5 is out of bounds for axis 0 with size 3
```
So, if we want to be consistent with the normal python behavior, then it leads to choice (c).

In addition, the following considerations generally apply:
- Whenever there is a discrepancy between R api and Python api, we prefer to follow the Python api. Preferring the other way would break expectations of a regular python programmer, and make using the library much harder. In addition, there is no guarantee that this would result in self-consistent behavior (because not all R apis can be followed);
- The question of usefulness: which approach would result in a more useful behavior? In python zen "practicality beats purity";
- If one of the approaches is chosen, is it possible to achieve the other behavior through some different means? For example, selecting `DT[5,:]` throws an error, but `DT[5:6, :]` returns an empty frame.

**Comment by st-pasha** [comment]
In pandas the equivalent function is [Groupby.nth()](https://pandas.pydata.org/pandas-docs/version/0.25/reference/api/pandas.core.groupby.GroupBy.nth.html). This function removes the groups which have less rows than the requested `n` (i.e. option **(a)**):
```
>>> import numpy as np
>>> import pandas as pd
>>> df = pd.DataFrame({'A': [1, 1, 2, 1, 2],
...                     'B': [np.nan, 2, 3, 4, 5]}, columns=['A', 'B'])
>>> g = df.groupby('A')
>>> g.nth(0)
     B
A     
1  NaN
2  3.0
>>> g.nth(1)
     B
A     
1  2.0
2  5.0
>>> g.nth(2)
     B
A     
1  4.0
>>> g.nth(3)
Empty DataFrame
Columns: [B]
Index: []
```

**Comment by st-pasha** [comment]
We don't have `onerow_in` class anymore, instead should implement `Head_Literal_Int::evaluate_iby()`.
