### ISSUE TITLE
max/min of an empty column should return None

### ISSUE THREAD

**Issue by nkalonia1** [h2oai/datatable#1624]
```
>>> f = dt.Frame(a=[float("nan"), 3], b=['a', 'b'])
>>> f
      a  b 
---  --  --
 0       a 
 1    3  b 

[2 rows x 2 columns]

>>> g = f[:, {'c': dt.max(dt.f['a'])}, dt.by('b')]
>>> g
     b      c
---  --  ----
 0   a   -inf
 1   b      3

[2 rows x 2 columns]
```

`[0, 'c']` should be `NA`.

**Comment by st-pasha** [comment]
In R data.table:
```
> DT = data.table(A=c(NA, 3.0), b=c('a', 'b'))
> DT[, max(A, na.rm=T), by=b]
   b   V1
1: a -Inf
2: b    3
Warning message:
In gmax(A, na.rm = TRUE) :
  No non-missing values found in at least one group. Returning '-Inf' for such groups to be consistent with base
```
I'm going to remove the [bug] label until we figure what's the desired behavior should be.

**Comment by pseudotensor** [comment]
If it found only missings, it should have returned a missing not -inf or +inf.  I see no reason to justify +-inf.

**Comment by st-pasha** [comment]
`-inf` is the identity of `max` operator, just like `0` for `sum`. Since sum of an empty set returns 0, max of an empty set could return -inf. But then, of course, nan is also reasonable.

**Comment by pseudotensor** [comment]
Ya, depends upon np.sum vs. np.sumnan type thing:
```
>>> import numpy as np
>>> np.nansum([np.nan])
0.0
>>> np.nanmax([np.nan])
__main__:1: RuntimeWarning: All-NaN axis encountered
nan
>>> np.nanmin([np.nan])
nan
>>> 
```

Here if all nans then get nan.  I like numpy way for alot of these things.

**Comment by pseudotensor** [comment]
`-inf is the identity of max operator` btw, I don't know why that would ever be a good idea ;)  I think again this is language vs. mathematical packages issue like your question about log(0).  I think dt should be performing reasonable numpy-compatible mathematical operations.

**Comment by st-pasha** [comment]
We currently return `-inf` not because of some deep thought that went into this, it's just an artifact of how we compute it.
That being said, mathematically an empty set has no maximum, however an empty set has supremum which is -∞.

**Comment by pseudotensor** [comment]
That's only true if you have defined the set to be real numbers.  Does the dt set know it's type if empty?  I guess it knows where it came from, so then if that's real/int types then you are right.

**Comment by pseudotensor** [comment]
I like your logic and point :)

**Comment by jangorecki** [comment]
R data.table is consistent to R on that matter:
```r
max(NA, na.rm=TRUE)
#[1] -Inf
#Warning message:
#In max(NA, na.rm = TRUE) : no non-missing arguments to max; returning -Inf
max(NA, na.rm=FALSE)
#[1] NA
```
there is more, like `mean(NA, na.rm=TRUE)` vs `sum(NA, na.rm=TRUE)`

**Comment by st-pasha** [comment]
@jangorecki Were there any complaints about this from users?
For example, if I do
```
> DT = data.table(A=c(NA,TRUE), B=c(NA_integer_,3L), C=c(NA_real_,1.5), id=1:2)
> DT[, .(max(A, na.rm=T), max(B, na.rm=T), max(C, na.rm=T)), by=id]
   id   V1   V2   V3
1:  1 -Inf -Inf -Inf
2:  2    1    3  1.5
Warning messages:
1: In gmax(A, na.rm = TRUE) :
  No non-missing values found in at least one group. Coercing to numeric type and returning 'Inf' for such groups to be consistent with base
2: In gmax(B, na.rm = TRUE) :
  No non-missing values found in at least one group. Coercing to numeric type and returning 'Inf' for such groups to be consistent with base
3: In gmax(C, na.rm = TRUE) :
  No non-missing values found in at least one group. Returning '-Inf' for such groups to be consistent with base
```
The end result is that columns A, B, C were coerced into `numeric`, only because one of the groups was "unlucky" in that it contained only missing values.

**Comment by jangorecki** [comment]
Good spot. I don't recall any complains on such en-expected coercion. If we would attempt to "fix" that somehow that would lose consistency to base R and potentially be a source of another complains.
