### ISSUE TITLE
Release process is not releasing

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#1637]
The release 0.8.0 was stuck on several problems:
  - these are problems which were fixed in rel-0.8 branch **ONLY**: https://github.com/h2oai/datatable/compare/c78ffc6a9eb6259849019ba02e837bea5f1c082a%5E..65e1f78c17ca7b80f41c0c03195ceb5c028ef4e0
  - but whole release was stuck in running `cd release/dist && find . \( -name '*.whl' -o -name '*.tar.gz' \) -printf '%P
'` - see http://mr-0xc1:8080/view/DataTable/job/h2o-py-data-table/job/rel-0.8/6/

**Comment by mmalohlava** [comment]
The same for 0.9.0.

**Comment by ash-mer** [comment]
See PR at #1932
