### ISSUE TITLE
Jupyter kernel dying on 0.8.0

### ISSUE THREAD

**Issue by antorsae** [h2oai/datatable#1639]
- Did you find a bug in datatable, or maybe the bug found you?
Kernel dies when using 0.8.0 release, works fine on 0.7.0

- How to reproduce the bug?
Execute this NB:
https://github.com/antorsae/microsoft-malware-prediction/blob/master/dt.ipynb

Kernel crashes before getting to the stuff where it attempts to convert Datatable to pandas, dmesg reveals:

```
$ dmesg
...
[129173.118138] ZMQbg/1[70481]: segfault at 0 ip 00007fa8e8e26aaa sp 00007ffcc2fb37a8 error 4 in _datatable.cpython-36m-x86_64-linux-gnu.so[7fa8e8dd7000+194000]
```

- Your environment?
I updated datatable by
`$ pip install https://github.com/h2oai/datatable/releases/download/v0.8.0/datatable-0.8.0-cp36-cp36m-linux_x86_64.whl --upgrade`

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).
`[segfault]`

**Comment by st-pasha** [comment]
Thanks @antorsae for the report. I'll try to reproduce this as soon as I finish downloading this competition's data from Kaggle. In the meanwhile, can you tell me which exactly cell in the notebook causes the crash?

**Comment by st-pasha** [comment]
The crash occurs during setting the key:
```
>>> import datatable as dt
>>> train = dt.fread('~/datasets/microsoft-malware-prediction/train.csv')
>>> c = 'AvSigVersion'
>>> tmp = train[:, dt.count(), dt.by(c)]
>>> tmp.key = c
Segmentation fault: 11
```

**Comment by st-pasha** [comment]
A simpler example (without any external data):
```
import datatable as dt
import random
n = 10000
DT = dt.Frame(A=[random.choice("abcd") for _ in range(n)])
tmp = DT[:, dt.count(), dt.by(0)]
tmp.key = "A"
```
