### ISSUE TITLE
Implement datetime columns

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1646]
This is a request to new stypes and functions in support of date/time functionality.

Currently, different packages use different formats for dates and times:

### Apache Arrow

* `date[day]` (32bit, days since the Unix epoch)
* `date[ms]` (64bit, milliseconds since the Unix epoch)
* `time[s]` (32bit)
* `time[ms]` (32bit)
* `time[µs]` (64bit)
* `time[ns]` (64bit)
* `timestamp[s]` (64bit)
* `timestamp[ms]` (64bit)
* `timestamp[µs]` (64bit)
* `timestamp[ns]` (64bit)

When reading from csv, `pyarrow` parses date/time columns as `timestamp[s]`. Timestamps with milliseconds are read as strings. Some common date formats like `MM/DD/YYYY` are not recognized.
The arrow<->pandas conversion guide says that all `timestamp[*]` formats are converted to `pd.Timestamp` (`np.datetime64[ns]`), and all `date[*]` become object column with `datetime.date` items.

### Pandas

In pandas, there are standalone classes such as `pd.Timestamp`, `pd.Period`, `pd.DateOffset` and `pd.Timedelta`, but also column-like `DatetimeIndex` (with dtype `datetime64[ns]`), and also a `Series` with dtype `datetime64[ns]`.

When reading from CSV the datetime columns are not parsed, and remain as strings (objects). Conversion can be performed afterwards using `to_datetime()` function.

### Numpy

In numpy all dates are 64-bit, but with various time units: Y, M, W, D, h, m, s, ms, us, ns, ps, fs, as. All datetimes are based on POSIX time with epoch of 1970-01-01T00:00Z.
In numpy 1.6 the default format when parsing was `datetime64[us]`; since 1.7 the format is selected based on the string.

### Python

The datetime module supports classes `datetime.date`, `datetime.time`, `datetime.datetime` and `datetime.timedelta`. All of these are relatively "heavy" objects, each storing multiple fields: `.date` has year, month, day; time has hour, min, sec, microsec and timezone; etc.

There is also C-equivalent of `datetime` module; there the `.date` object is 4+N bytes, `.time` is 6+N bytes, and `.datetime` is 10+N bytes, where N=17, a per-object overhead.

## See Also
- https://github.com/HowardHinnant/date - C++14 date library (MIT licensed);
- http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2012/n3344.pdf - benchmark of various date implementations;

**Comment by XiaomoWu** [comment]
IMHO, every option is better than the `pandas` way. In `Rdatatable`, date or time is stored as an R object like `POSIXct` or `Date` (that's equivalent to the "Python" solution above), or stored internally as an integer like `IDate`, `ITime` (that equals to implementing `pydatatable`'s own datetime types).

**Comment by st-pasha** [comment]
Prerequisite: #1396

**Comment by st-pasha** [comment]
Done.
