### ISSUE TITLE
Randomized k-fold splitter

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1649]
Similar to the simple k-fold splitter (#1627), but in addition takes the `seed` parameter for random number generator. Then, each observation is assigned a "fold index" as a random integer in `range(k)`. After that, `k` pairs of row selectors are constructed, each pair comprised of one row index that selects all rows with a particular value of the fold index, and the other row index selecting all rows not selected by the first.

**Comment by XiaomoWu** [comment]
This is extremely useful!
