### ISSUE TITLE
R Reticulate Support - Option to remove interactivity

### ISSUE THREAD

**Issue by mdancho84** [h2oai/datatable#1668]
I'm working with RStudio on an [issue](https://github.com/rstudio/reticulate/issues/431) involving the `datatable` Python API. We are using a library called `reticulate`, which does not currently support the interactivity shown in the image below.

![image](https://user-images.githubusercontent.com/13734662/52916051-1a15aa00-32a9-11e9-903c-e1ee368e5c8c.png)

Is it possible to have an option to turn off this interactivity so we can use via the `reticulate` within the RStudio IDE similar to how `pandas` is used?

**Comment by st-pasha** [comment]
Hi, @mdancho84. We are considering how to best implement your request; but for now you can try the following hack:
```
import datatable as dt
dt.Frame.view.__defaults__ = (False,)
```
This will probably stop working in the next version of `datatable`, however by that time there will be a more robust solution available.

**Comment by mdancho84** [comment]
Beautiful. It works. Thanks for the quick response. :)
