### ISSUE TITLE
Eliminate dependency on blessed

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#1677]
We use `blessed` to handle widget rendering in a python terminal. That library itself has 2 dependencies: `wcwidth` and `six`.

Currently, the amount of functionality that we use from that library is not too big; plus we add a few hacks on top of that to achieve what we actually need. Overall, I believe removing blessed will have a net positive effect.

The following functions to be reimplemented:
- [x] various colors
- [x] `term.is_a_tty`
- [x] `term.width` / `term.height`
- [x] `term._encoding`
- [x] `term.length()`
- [x] `term.move_x`
- [x] `term.move_up`
- [x] `term.clear_eol`
- [ ] `term.cbreak` / `term.inkey`

**Comment by jquast** [comment]
author of blessed and wcwidth here, its all MIT licensed, you're welcome to copy any code that you wish directly :) enjoy

**Comment by st-pasha** [comment]
Thanks, Jeff.
