### ISSUE TITLE
fread() reads dates from xlsx as float64 

### ISSUE THREAD

**Issue by Viktor-Demin** [h2oai/datatable#1701]
`dt.fread("~/Downloads/dates.xlsx")
`returns 

```
Week_start | Value_Sales
0 | 42008 | 3527.56
1 | 42015 | 4344.03
2 | 42022 | 4103.33
3 | 42029 | 21530.4
4 | 42036 | 4102.35
5 | 42043 | 3965.92
```

while pandas 

`pd.read_excel("../Downloads/dates.xlsx")
`
returns

```
Week_start	Value_Sales
0	2015-01-04 01:00:00	3527.56
1	2015-01-11 01:00:00	4344.03
2	2015-01-18 01:00:00	4103.33
3	2015-01-25 01:00:00	21530.41
4	2015-02-01 01:00:00	4102.35
5	2015-02-08 01:00:00	3965.92


```

[dates.xlsx](https://github.com/h2oai/datatable/files/2923197/dates.xlsx)

**Comment by st-pasha** [comment]
This is true. The reason is that Excel stores dates as floating point numbers internally (number of days since 1900-01-01). We should convert this into a proper date type, however this requires implementing #1646 first.

**Comment by arnocandel** [comment]
https://github.com/h2oai/h2oai/issues/14147
