### ISSUE TITLE
Negative caclulations during join

### ISSUE THREAD

**Issue by Viktor-Demin** [h2oai/datatable#1702]
```
from datatable import f, by, sum,g, join
DT = dt.Frame(product_id=[1,1,1,2,2,2,3,3,3], quantity=[11,22,16,45,65,60,33,37,39])
DT1 = dt.Frame(product_id=[1,2,3], price=[1,2,3])
DT1.key = "product_id"
DT[:, f.quantity * g.price,by(f.product_id), join(DT1)]
```

returns unexpected negative value at row 4

```
product_id	C0
▪	▪
0	1	11
1	1	22
2	1	16
3	2	90
4	2	−126
5	2	120
6	3	99
7	3	111
8	3	117
```

**Comment by st-pasha** [comment]
The problem here is that both `quantity` and `price` column were sufficiently small, and therefore created as `int8`. However, during multiplication an overflow occurs and the result comes out negative.

I agree that this is not very intuitive behavior. I imagine we could:
  - avoid creating `int8` columns in the first place (unless asked explicitly by user) -- start with int32 by default;
  - declare that `int8` should be promoted to `int32` during arithmetic operations such as `+`, `-`, or `*` (I think this is what C does anyways).

For now you can explicitly state that you want to create `int32` (or `int64`) columns in the `dt.Frame` constructor, and then your result will be correct:
```
>>> DT = dt.Frame(product_id=[1,1,1,2,2,2,3,3,3], quantity=[11,22,16,45,65,60,33,37,39], stypes={"quantity":"int32"})
>>> DT[:, f.quantity * g.price,by(f.product_id), join(DT1)]
    product_id   C0
--  ----------  ---
 0           1   11
 1           1   22
 2           1   16
 3           2   90
 4           2  130
 5           2  120
 6           3   99
 7           3  111
 8           3  117

[9 rows x 2 columns]
```

**Comment by Cheburusska** [comment]
@st-pasha  looks like option 1 is more simple but requires more memory. Could you please put link to place where assigning happens? I'll try to investigate.

**Comment by st-pasha** [comment]
Frame construction occurs in file "c/frame/__init__.cc", which later calls function `Column::from_pylist()` defined in file "c/column_from_pylist.cc". That function determines what is the most appropriate type for column creation.

Later on when you multiply 2 columns, this is handled in "c/expr/base_expr.cc" which in turn calls function `binaryop()` defined in "c/expr/binaryop.cc".

**Comment by Cheburusska** [comment]
@st-pasha @oleksiyskononenko could you please help me with understanding of architecture of datatable project. My understanding that it right now it uses CPython for algorithms and for data types handling. This is why one need to build CPython code first. 

And I don't understand how can I debug such code.

I did `make debug` and installed `gdb`. But still cannot understand how can I put breakpoint in "c/column_from_pylist.cc" to understand what happens during 
`dt.Frame(product_id=[1,2,3], price=[1,2,3])`

Could you please share some useful links and best practices?

**Comment by st-pasha** [comment]
Either `make debug` or `make fast` will create debug version of datatable that can be used with `gdb` (or `lldb` on Mac). This can be done as follows:

- Run gdb and then python inside gdb:
```
$ gdb
(gdb) target exec python
```

- Set a breakpoint (there is more than one way to do it)
```
(gdb) b column_from_pylist.cc:500
No symbol table is loaded.  Use the "file" command.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (column_from_pylist.cc:500) pending.
(gdb) b from_py_iterable
No symbol table is loaded.  Use the "file" command.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 2 (from_pyiterable) pending.
```

- run your test file (you can also write simply `r` to run python console)
```
(gdb) run test.py
Starting program: /usr/bin/python test.py
...
```

It will stop execution at the breakpoint, at which point you can use command `n` to step over, `s` to step into a function, `bt` to view the current backtrace, `f 5` to switch to a particular frame in the backtrace, `p <expr>` to evaluate c expression and view its result. This can be used to examine a value of a particular variable.

There are many more commands available, for example setting a conditional breakpoint, you can find out about them by googling around.

Note also that CPython is not something that we USE, it's rather what the python actually IS. Even though python is a language, its runtime is implemented in C, and this implementation is called CPython. This is the most popular one, there are alternative implementations, such as IronPython, JPython, PyPy, but datatable will work only with CPython. CPython provides an API (https://docs.python.org/3.6/c-api/index.html) for C/C++ programs to interact with it, and this is what we use (though we wrap everything in C++ objects for a simpler interface and to avoid possible memory leaks).

**Comment by Cheburusska** [comment]
@st-pasha I'm trying build datable on Ubuntu 18.04.2 LTS but get error:

```
• Making directory build/fast/str
• Refreshing c/str/py_str.h
• Compiling c/models/py_ftrl.cc
• Compiling c/models/py_validator.cc
• Compiling c/models/utils.cc
In file included from c/models/utils.cc:24:0:
c/models/utils.h:31:6: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
 std::unique_ptr<T> make_unique(Args&&... args) {
      ^~~~~~~~~~
ci/fast.mk:703: recipe for target 'build/fast/models/utils.o' failed
make[1]: *** [build/fast/models/utils.o] Error 1
make[1]: Leaving directory '/home/viktor/datatable'
ci/fast.mk:1019: recipe for target 'fast' failed
make: *** [fast] Error 2
```
same error for `make debug` and `make build`

LLVM 6 installed according to manual. 
llvm lite also installed 
python 3.6.7

pip install datatable worked successfully. 

I found this question, maybe something wrong with c++ compiler?
https://stackoverflow.com/questions/43450514/trouble-with-unique-ptr-not-a-member-of-std

What could be the reason?

**Comment by st-pasha** [comment]
Hard to say, it works fine for me on Ubuntu 18.04.1 LTS, but this is how you can try troubleshooting it:
- go into file `ci/fast.mk`, and replace all `@$(CC)` with `$(CC)`. In fact, you can remove `@` from all commands;
- run `make fast` and look at the commands being executed during compile / link stage;
- run `make debug` and again look at the commands being executed during compile / link stage;
- try to see what the difference is, it's probably in some flag being missing (or extra) for the `make fast` case.

**Comment by Cheburusska** [comment]
@st-pasha how one can change type of column of already created Frame from `int32` to `int8` for example? Is there API for that?

meanwhile I changed `from_py_iterable` functions and now it by default makes `int8` and `int16` to `int32`:

```
      switch (stype) {
        case SType::BOOL:    ret = parse_as_bool(il, membuf, i); break;
        case SType::INT8:    force_as_int<int32_t>(il, membuf); break; //changed this
        case SType::INT16:   force_as_int<int32_t>(il, membuf); break; //changed this
        case SType::INT32:   ret = parse_as_int<int32_t>(il, membuf, i); break;
        case SType::INT64:   ret = parse_as_int<int64_t>(il, membuf, i); break;
        case SType::FLOAT64: ret = parse_as_double(il, membuf, i); break;
        case SType::STR32:   ret = parse_as_str<uint32_t>(il, membuf, strbuf); break;
        case SType::STR64:   ret = parse_as_str<uint64_t>(il, membuf, strbuf); break;
        case SType::OBJ:     ret = parse_as_pyobj(il, membuf); break;
        default: /* do nothing -- not all STypes are currently implemented. */ break;
      }
```
on my example it works correctly. Do we have non-negative impact tests to validate changes?

**Comment by Cheburusska** [comment]
@st-pasha there is no fast.mk file in ci or at any place in project. Looks like it should be generated automatically but it wasn't.

![image](https://user-images.githubusercontent.com/19714042/54882396-9d0ebf00-4e6a-11e9-98b7-bd0e3af3b769.png)

**Comment by st-pasha** [comment]
`ci/fast.mk` is created when you run `make fast`, and removed if you run `make clean`. It can also be generated manually using `python ci/make_fast.py`.

As for changes in `from_py_iterable`, shouldn't it be `parse_as_int` instead of `force_as_int`? The former allows type bumps, the latter doesn't. For example, you can check whether `dt.Frame([2, 2**50])` or `dt.Frame([3, 3.14])` give expected results.

**Comment by st-pasha** [comment]
I've added few tests to verify automatic type promotion: #1754

**Comment by Cheburusska** [comment]
`case SType::INT8:    parse_as_int<int32_t>(il, membuf, i); break;
`returns same result  as 
`case SType::INT8:    force_as_int<int8_t>(il, membuf); break;`

```
print(dt.Frame([2, 2**50]).stypes, ) # (stype.int64,)  1125899906842624
print(dt.Frame([3, 3.14]).stypes)  # (stype.float64,)
```
but when I try 

`case SType::INT8:    ret = parse_as_int<int32_t>(il, membuf, i); break;
`
and simple frame creation` dt.Frame(product_id=[1,2,3], price=[1,2,3])` i get:

```
    product_id	price

0	1	1
1	0	0
2	0	0
3	0	0
4	2	2
5	0	0
6	0	0
7	0	0
8	3	3
9	0	0
10	0	0
11	0	0

```
