### ISSUE TITLE
Implement chaining feature similar to R data.table

### ISSUE THREAD

**Issue by Cheburusska** [h2oai/datatable#1729]
CHAINING HELPS TACK EXPRESSIONS TOGETHER AND
AVOID (UNNECESSARY) INTERMEDIATE ASSIGNMENTS

This is how it is implemented in R data.table:

without chaining:

`DT<-DT[, .(V4.Sum = sum(V4)),by=V1]`

```
V1 V4.Sum
1: 1 36
2: 2 42
```

`DT[V4.Sum > 40] `

```
V1 V4.Sum
1: 2 42
```

and with chaining

`DT[, .(V4.Sum = sum(V4)),by=V1][V4.Sum > 40 ]`
```
V1 V4.Sum
1: 2 42
```

In pandas it is also possible to do actions one after another using` . ` operator

More detais here:
[data+table+cheat+sheet.pdf]
(https://github.com/h2oai/datatable/files/2989171/data%2Btable%2Bcheat%2Bsheet.pdf)

**Comment by st-pasha** [comment]
Chaining is already possible, since `DT[i1, j1][i2, j2]` is interpreted by python as `tmp = DT[i1, j1]; tmp[i2, j2]`. Try for yourself:
```
>>> import datatable as dt
>>> from datatable import f, sum, by
>>> DT = dt.Frame(V1=[1, 2, 1, 2], V4=[16, 18, 20, 22])
>>> DT[:, {"sum": sum(f.V4)}, by(f.V1)]
    V1  sum
--  --  ---
 0   1   36
 1   2   40

[2 rows x 2 columns]

>>> DT[:, {"sum": sum(f.V4)}, by(f.V1)][f.sum >= 40, :]
    V1  sum
--  --  ---
 0   2   40

[1 row x 2 columns]
```

**Comment by Cheburusska** [comment]
@st-pasha thank you for answer. Chaining looks great. I think it worth adding to documentation. I'll add if you ok
