### ISSUE TITLE
Support print() function similar to pandas

### ISSUE THREAD

**Issue by Cheburusska** [h2oai/datatable#1740]
Now it is only possible to work in jupyter notebook or in IDLE because print() function doesn't actually returns values only short dataframe description while in Pandas it works as expected. This is why it is not possible to use PyCharm or another IDE for development

```
import datatable as dt
import pandas as pd

DT1 = dt.Frame(product_id=[1,2,3], price=[1,2,3])
print('datatable frame:')
print(DT1.head())

print('')
print('pandas frame:')
df1 = DT1.to_pandas()

print(df1)
```
returns
```
datatable frame:
<Frame [3 rows x 2 cols]>

pandas frame:
   product_id  price
0           1      1
1           2      2
2           3      3
```

**Comment by st-pasha** [comment]
pandas is far from ideal in this regard. Surely, `print(pandas_df)` works nicely and prints the contents of the frame. But once you have a frame in a list or dictionary or some other container, the output quickly gets unintelligible:
```
>>> DT = dt.Frame(range(10))
>>> pf = DT.to_pandas()
>>> {"foo": pf, "bar": pf * 2}
{'foo':    C0
0   0
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9, 'bar':    C0
0   0
1   2
2   4
3   6
4   8
5  10
6  12
7  14
8  16
9  18}
```

I think the best way forward is to keep `Frame.__repr__()` as-is, while providing a new `Frame.__str__()` function that would display the frame's contents. That way `print(DT)` would be useful, while in all other contexts the short form "<Frame [10 rows x 1 col]>" would still be used.
