### ISSUE TITLE
streaming dt.fread(path).to_jay()

### ISSUE THREAD

**Issue by arnocandel** [h2oai/datatable#1750]
Implement parsing a large .csv to a .jay file in a streaming fashion, without requiring more than a few GBs of RAM at most.

**Comment by arnocandel** [comment]
https://github.com/h2oai/h2oai/issues/3518

**Comment by st-pasha** [comment]
One way this can be achieved is by having a special parameter `memory_bound=` which would recommend a limit on how much RAM can be used by fread. If the dataset appears to be larger than this bound, a smaller frame will be created and saved to a temporary Jay file on disk. Then we will continue reading the remaining data, again possibly dumping it into a temporary Jay file. And so on. At the end, we will have 0 or more datasets residing in temporary folder on disk, and 1 "tail" dataset in memory. At this point we can perform "virtual rbind" of all these frames, returning a virtual Frame that contains all data from the input csv. It would be almost indistinguishable from the old fread behavior, except that the returned dataset will be virtual not material.

Saving this Frame to a Jay file would materialize the data directly on disk, essentially copying chunks from all temporary jay frames into the final destination.

Prerequisite: virtual column support (#1369)
Prerequisite: proper handling of temporary Jay files (i.e. we have to know when they are safe to delete).

**Comment by arnocandel** [comment]
a script to push the boundaries on the rbind(many tables) memory limit and grouping:
https://github.com/h2oai/h2oai/blob/bf046974e812707e546815e0c46aecab69e3106a/tests/test_ts_support/big_data_stock.py
