### ISSUE TITLE
The default interactive display in terminal

### ISSUE THREAD

**Issue by NachiGithub** [h2oai/datatable#1789]
- Did you find a bug in datatable, or maybe the bug found you?
I was excited to see the interactive mode turned off by default (in the latest commit). So, I wanted to test it out. So, I compiled from master branch today (on a Mac). Then ran the following code:

```
DT = dt.Frame(A=range(5))
DT
```

I was expecting it to print the following, without pausing in the end:
```
Out[3]:      A
--  --
 0   0
 1   1
 2   2
 3   3
 4   4
[5 rows x 1 column]
```

instead it prints the following: 
```
Out[3]:      A
--  --
 0   0
 1   1
 2   2
 3   3
 4   4
[5 rows x 1 column]
Press q to quit  ↑←↓→ to move  wasd to page  t to toggle types  g to jump
```
And waits for keyboard input. The version string shows 0.8.0 at the moment.

```
print(dt.__version__)
0.8.0
```
The interactive options seems to be set to False:
```
dt.options.display
Out[4]: 
dt.options.display.
    interactive_hint = 1
    interactive = 0
```
Any suggestion to turn off the interactive mode? The DT.view(interactive=False) works, but that's a bit much to type every time. 

Thanks!

**Comment by st-pasha** [comment]
Which environment is this? A Jupyter notebook? If so then what version?

**Comment by NachiGithub** [comment]
I am using a PyCharm IDE. It's running in an ipython shell.

**Comment by NachiGithub** [comment]
Awesome! Works great now. What speed! Thanks.
