### ISSUE TITLE
How to use seaborn library with pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#1807]
I have started using pydatatable for one of my data analysis project, here i have faced few issues in making charts of pydatatable object using seaborn library.

does pydatatable support seaborn visualizations in current version  0.8?.

I have tried to visualise a column with a chart : histogram, boxplot etc.etc. as showed in the sample code below

_np.random.seed(1)
dt_test = dt.Frame(np.random.randn(1000))
sns.boxplot(x="CO",data=dt_test)
plt.show()_

On running above code chunk it should display a boxplot of the provided column, but here it's giving an error as
**AttributeError: 'Frame' object has no attribute 'get'**
Could you please write to me here how to solve this and am i making any mistake here ?.

**Comment by myamullaciencia** [comment]
Here is another case, i have a DT called **heart_data**, i'm trying to do a scatterplot on two columns from it as mentioned below, 

_sns.scatterplot(x="change",y="pvalue",data=heart_data)
plt.show()_

here also i'm getting the same error : AttributeError: 'Frame' object has no attribute 'get'

**Comment by aschmu** [comment]
This makes sense seaborn expects dataframe not a datatable object hence the error.

**Comment by st-pasha** [comment]
@myamullaciencia While seaborn does not support datatable frames yet, you can try one of the following workarounds:
```
# Either do not use parameter `data=`
sns.boxplot(x=dt_test[:, "C0"])
sns.scatterplot(x=heart_data[:, "change"], y=heart_data[:, "pvalue"])

# or convert to pandas before passing to seaborn:
sns.scatterplot(x="change", y="pvalue", data=heart_data.to_pandas())
```

**Comment by myamullaciencia** [comment]
OK @st-pasha thanks for your comment and i'm looking forward to learning a lot of data.table/pydatatable.. thanks again.
