### ISSUE TITLE
sort while groupby does not scale

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#1808]
There is a severe performance issue when doing query of type:
```py
#question = "largest two v3 by id2 id4" # q8
ans = x[:2, {"largest2_v3": f.v3}, by(f.id2, f.id4), sort(-f.v3)]
```
It has outstanding performance on 1e7 rows (0.5 GB) but is unacceptably slow on 1e8+.

**Comment by st-pasha** [comment]
The culprit in this case is probably issue #219

**Comment by oleksiyskononenko** [comment]
@jangorecki could you please share some numbers on how good is 1e7 and how bad is 1e8?

**Comment by jangorecki** [comment]
@oleksiyskononenko see question 3 on plots below

![G1_1e7_1e2_0_0 advanced](https://user-images.githubusercontent.com/3627377/56566936-1b6a9800-65b4-11e9-8329-e328beab615a.png)

![G1_1e8_1e2_0_0 advanced](https://user-images.githubusercontent.com/3627377/56566955-26252d00-65b4-11e9-9e71-8665ad2cf0a2.png)

**Comment by oleksiyskononenko** [comment]
@jangorecki can you re-run the above benchmarks and let us know about the outcome? It seems that as of #1894 performance of sorting operation is improved by quite a lot.

**Comment by jangorecki** [comment]
@oleksiyskononenko benchmark has been already refreshed after those changes, using https://github.com/h2oai/datatable/commit/d3b8f8b7def9cfb1b2cf5731227af9a13ff62086. Keep in mind that "advanced" set of 5 questions is visible in sub-page: https://h2oai.github.io/db-benchmark/groupby.html not in the front page. It seems there is not really speed improvement, but AFAIR previously 1e9 rows data were failing to complete, now they do complete.
There is new run on-going now so timings will be updated again within next 1-3 days, using latest dev.

**Comment by jangorecki** [comment]
I think we can close this issue, datatable scales better for this question now.

# 1e7
![G1_1e7_1e2_0_0_advanced](https://user-images.githubusercontent.com/3627377/75127178-b99f2100-56e3-11ea-845e-59533e625810.png)

# 1e8
![G1_1e8_1e2_0_0_advanced](https://user-images.githubusercontent.com/3627377/75127190-cae82d80-56e3-11ea-9ff1-fe568eab2401.png)
