### ISSUE TITLE
datatable on RHEL6.5 python 3.5.4

### ISSUE THREAD

**Issue by rockssk** [h2oai/datatable#1811]
Has anyone successfully able to setup and use datatable python package from h2o on RHEL6.5?

Pip install ran successfully without an issue, but while calling import am hitting an error as below

ImportError: /lib64/llibc.so.6: version `GLIBC_2.17` not found

Environment:
H20:1.5.4
Python:3.5.4
OS:RHEL6.5

Any pointers is much appreciated

**Comment by st-pasha** [comment]
This error occurs when the version of C++ standard library on your system is lower than the version of the compiler that was used to build `datatable`. There are 2 solutions:
- upgrade `gcc` to a newer version (or at least upgrade `stdlibc++`)
- compile `datatable` on your own system from source

**Comment by rockssk** [comment]
Thanks for your response

Could you please help  me with the guide for option 2 in your solution?

**Comment by oleksiyskononenko** [comment]
Hi @rockssk, for option 2 you can refer to https://datatable.readthedocs.io/en/latest/install.html#build-from-source

**Comment by st-pasha** [comment]
Btw we have just simplified our build instructions at https://datatable.readthedocs.io/en/latest/install.html, please feel free to reopen if you have any more difficulties with installing.
