### ISSUE TITLE
How to install the latest github version?

### ISSUE THREAD

**Issue by XiaomoWu** [h2oai/datatable#1818]
This might be a silly question, but how to install the latest github version of `datatable`? I didn't find any information about compiling from the source code. Please ignore or close this issue if you see it doesn't fit here.

**Comment by jangorecki** [comment]
@XiaomoWu this script might be useful: https://github.com/h2oai/db-benchmark/blob/master/pydatatable/init-pydatatable.sh
it build latest pydt from github, command at the top are used to active dedicated virtualenv

**Comment by XiaomoWu** [comment]
Thank you! That works!
