### ISSUE TITLE
[bug] "Import datatable" fails on os-x

### ISSUE THREAD

**Issue by javadba** [h2oai/datatable#1830]
I ran `pip install datatable` that installed version 0.8.0

Then inside python:

import datatable

That was not happy - with  `ImportError: cannot import name '_datatable' from 'datatable.lib' (/git/datatable-0.8.0/datatable/lib/__init__.py)`

Details:

/git/datatable-0.8.0/datatable/__init__.py in <module>
     22 #-------------------------------------------------------------------------------
     23 from .__version__ import version as __version__
---> 24 from .dt_append import rbind, cbind
     25 from .frame import Frame
     26 from .expr import (mean, min, max, sd, isna, sum, count, first, abs, exp,

/git/datatable-0.8.0/datatable/dt_append.py in <module>
      6 #-------------------------------------------------------------------------------
      7 import datatable as dt
----> 8 from datatable.utils.misc import plural_form as plural
      9 from datatable.utils.typechecks import typed, Frame_t, TValueError
     10

/git/datatable-0.8.0/datatable/utils/misc.py in <module>
      6 #-------------------------------------------------------------------------------
      7 import importlib
----> 8 from .typechecks import TImportError
      9
     10 __all__ = ("clamp", "normalize_slice", "normalize_range", "plural_form",

/git/datatable-0.8.0/datatable/utils/typechecks.py in <module>
     13 from typesentry import U
     14 from datatable.utils.terminal import term
---> 15 from datatable.lib import core
     16
     17 _tc = typesentry.Config()

/git/datatable-0.8.0/datatable/lib/__init__.py in <module>
      7
      8 # noinspection PyUnresolvedReferences
----> 9 from . import _datatable as core
     10
     11 __all__ = ("core", )

ImportError: cannot import name '_datatable' from 'datatable.lib' (/git/datatable-0.8.0/datatable/lib/__init__.py)

**Comment by st-pasha** [comment]
Hi Stephen, please provide the following information to better understand the root of your problem:
1. Your python version (`python -VV`);
2. Which files do you have in `/git/datatable-0.8.0/datatable/lib/` folder;
3. Output of your installation log (`pip install datatable -v`);
4. Do you have variables `PYTHONPATH` or `PYTHONHOME` in your environment?

**Comment by st-pasha** [comment]
Issue appears abandoned, so closing.

**Comment by tejas-kale** [comment]
Hi. I am seeing a similar issue on my Mac. I have installed version `0.10.1`. The error trace is as follows:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-bb0f7849d770> in <module>
      2 from pathlib import Path
      3 
----> 4 import datatable as dt
      5 import matplotlib.pyplot as plt
      6 import numpy as np

~/anaconda3/envs/mlenv/lib/python3.8/site-packages/datatable/__init__.py in <module>
     22 #-------------------------------------------------------------------------------
     23 from .__version__ import version as __version__
---> 24 from .frame import Frame
     25 from .expr import (mean, min, max, sd, isna, sum, count, first, abs, exp,
     26                    last, log, log10, f, g, median, cov, corr)

~/anaconda3/envs/mlenv/lib/python3.8/site-packages/datatable/frame.py in <module>
     21 # IN THE SOFTWARE.
     22 #-------------------------------------------------------------------------------
---> 23 from datatable.lib._datatable import Frame
     24 
     25 __all__ = ("Frame", )

~/anaconda3/envs/mlenv/lib/python3.8/site-packages/datatable/lib/__init__.py in <module>
     29 
     30 # noinspection PyUnresolvedReferences
---> 31 from . import _datatable as core
     32 
     33 __all__ = ("core", )

ImportError: cannot import name '_datatable' from partially initialized module 'datatable.lib' (most likely due to a circular import) (/Users/tejaskale/anaconda3/envs/mlenv/lib/python3.8/site-packages/datatable/lib/__init__.py)
```

Here's some supplementary information:

- Python version

```
Python 3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:21:09)
[Clang 9.0.1 ]
```

- Contents of `lib` folder

```
__init__.py     __pycache__     libc++.1.dylib  libc++abi.dylib
```

- Output of `pip install datatable -v`

[dt_install.log](https://github.com/h2oai/datatable/files/4977603/dt_install.log)

- I have not set `PYTHONPATH` or `PYTHONHOME`. Should I? 

- Mac details

```
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
```

Am I doing anything wrong? Thanks...

**Comment by st-pasha** [comment]
@tejas-kale 
Please check the troubleshooting section of the Installation Guide (https://datatable.readthedocs.io/en/latest/start/install.html). There are suggestions there on how to fix the "cannot import _datatable" problem.

**Comment by tejas-kale** [comment]
@st-pasha 
Thanks for the link. Somehow I missed it while searching for solutions. Apologies for that.
