### ISSUE TITLE
random folds not reprodicible for different core counts

### ISSUE THREAD

**Issue by pseudotensor** [h2oai/datatable#1851]
```
import datatable as dt
dt.options.nthreads = 4
from datatable.models import kfold_random

nrows = 500
n_folds = 3
random_state = 1337158

fold_frame_pairs = kfold_random(nrows=int(nrows), nsplits=int(n_folds), seed=random_state)
folds = []
for f in fold_frame_pairs:
    folds.append([f[0].to_list()[0], f[1].to_list()[0]])
print(folds)
```

Change 4 to 3 and see how (e.g.) last entry is different.  For 4 one gets 485.  For 3 one gets 499.

This leads to this failure: https://github.com/h2oai/h2oai/issues/8847

**Comment by st-pasha** [comment]
From the documentation of `kfold_random()`:
```
seed: int (optional)
    Seed value for the random number generator used by this function.
    Calling ``kfold_random()`` several times with same seed value
    will produce same results each time, provided that the number
    of threads remains constant.
```

The dependency of RNG on the number of threads is the behavior that we've discussed with Arno and agreed upon up-front.

**Comment by pseudotensor** [comment]
Ok, would be more standard to have it be reproducible if random state is set.  I think Arno would have said it is ok "at first" but should improve things if can.

xgboost deals with similar issues, so perhaps look into how they do things.

**Comment by st-pasha** [comment]
I understand the notion that requirements may change etc.
Currently looking into how to make this thread-independent. 
Setting seed on every row is not viable: the performance drops 10x.
