### ISSUE TITLE
pip install on linux

### ISSUE THREAD

**Issue by hawkberry** [h2oai/datatable#1864]
Please make the Linux implementation of datatable available via the python package index and pip package manager.

Usually this is done by using the os and sys modules in your setup.py to determine the architecture, and then the build options for the appropriate system.

We are building a high-performance package that depends on datatable, and want our package available on pip. Consequently, we would need pip install datatable on linux as well.

Thank you for your time.

**Comment by st-pasha** [comment]
Hi @hawkberry,
Good news: we've tested the possibility to build the manylinux2010 distribution of datatable, and it worked with the current dev version almost without any hiccups. Thus, we'll be able to upload these distributions to PyPI when we  release version 0.9.
Bad news: the 0.8 version (which is currently on PyPI) does not pass the audit and thus we can't build manylinux distributions for it.

**Comment by st-pasha** [comment]
Release 0.9 is out, and includes manylinux wheels:
https://pypi.org/project/datatable/0.9.0/#files
