### ISSUE TITLE
Pydatatable 0.9 documentation 

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#1949]
**Hi pydatatable team,**

i have started using pydatatable for one of my project, i can see that 0.9 version has been out in the last days, i was looking for its documentation, but i couldn't find in anywhere. could you please let me where/when it can be avail?.

**Regards,
Mallesham**

**Comment by oleksiyskononenko** [comment]
@myamullaciencia Latest datatable documentation can be found here https://datatable.readthedocs.io/en/latest/

**Comment by myamullaciencia** [comment]
HI @oleksiyskononenko many thanks for your info and i will go through it.
