### ISSUE TITLE
read 0 in csv ,but become False after to_pandas()

### ISSUE THREAD

**Issue by appleyuchi** [h2oai/datatable#1990]
- Did you find a bug in datatable, or maybe the bug found you?
I found a bug

- How to reproduce the bug?
  **This part is the most important**. Please provide a code snippet which, when
  executed in console, demonstrates the problem. If necessary, attach any data
  files to the issue.

when there's a 0 in a cell of csv.
train=dt.fread("train.csv")works right
but when do:
train.to_pandas()
all the 0 will become false

- What was the expected behavior?
  In case it is not obvious, please tell us what result should your code
  produce.

all the0 remain the same

- Your environment?
  What is your datatable version, python version, and operating system?
#
datatable              0.9.0 

Python Python 3.6.7rc1
Ubuntu18.10-64

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).

- Thank you for contributing, and sorry for the inconvenience.

**Comment by dmillar** [comment]
What are the stypes in the Frame? I am unable to reproduce this behavior in MacOS or Linux Mint for int32 and float64 stypes.

**Comment by st-pasha** [comment]
Consider the following example:
```
import datatable as dt
DT = dt.fread("""
A
0
1
""")
print(f"stypes = {DT.stypes}\n")
print(f"DT: \n{DT}")
print(f"to_list() = {DT.to_list()}\n")
print(f"to_pandas() = \n{DT.to_pandas()}\n")
```

Currently it produces
```
stypes = (stype.bool8,)

DT: 
     A
--  --
 0   0
 1   1

[2 rows x 1 column]

to_list() = [[False, True]]

to_pandas() = 
       A
0  False
1   True
```

This highlights the fact that whenever fread sees a column containing only 0s and 1s, it treats that column as boolean. In any arithmetic context a boolean column behaves as-if it was integer, so often you won't even notice the difference. And by the way, python does the same: for example, `True + True == 2`.

Thus, the behavior that you see is not a bug: it was designed this way. Most of the time when a non-trivial dataset contains a 0/1 column, that column really is an indicator variable, and can be more usefully treated as boolean. 

However, I do understand that in some cases it might be desirable to have it as integer instead. Currently you can force a specific type for one of the columns in fread by using `columns=` parameter: `dt.fread("A\n0\n1", columns={"A": int})`. There is also an open issue #929 that will add a parameter to fread forcing it to treat all 0/1s as integers.
