### ISSUE TITLE
Handle zip-files with multiple files.

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#2008]
### Describe what feature you would like to see implemented

`fread` option to allow optimistic parse of zip-files with multiple files. The fread will try to parse the file individually and rbind the resulting frame.

I.e, avoid limitations in the code mentioned here: https://github.com/h2oai/datatable/blob/master/datatable/fread.py#L359-L362

**Comment by pseudotensor** [comment]
related https://github.com/h2oai/datatable/issues/488

**Comment by pseudotensor** [comment]
Also related https://github.com/h2oai/h2oai/issues/10526. Dt already supports multiple tables, DAI doesn't use it.

**Comment by pseudotensor** [comment]
basically it should be smarter, ignore unrelated file , try to rbind, and if fails return as individual files like done for excel sheets.

**Comment by st-pasha** [comment]
This is something that is relatively easy to implement, but not that easy to figure a good API.

From the API standpoint, having a function that sometimes returns a Frame, while other times returning a dictionary of Frames -- it just doesn't look very reliable. Unfortunately, we're already doing this, returning multiple frames for certain types of inputs. However, extending that functionality will only exacerbate the problem.

So I wonder what a proper solution would be here, API-wise. A separate function that returns multi-frame output? A flag that forces the output to have multiple frames? How would this all look from the perspective of a type annotation system?

**Comment by pseudotensor** [comment]
Sure, you can have different function arguments to control eventual result, but at least needs some smarts to avoid errors, e.g. errors='ignore' if some files are "bad" like MAC os files that often float around together with zips.

**Comment by st-pasha** [comment]
So, I was thinking about the following solution:

1. New function `mread(...)`, which works similarly to `fread()` but always returns a dictionary, even for a single source (or, more generally, a `FrameSet` object which is derived from `dict`).

2. The current `fread()` acquires new option `multiple_sources = "warn" | "error" | "ignore" | "rbind" | "rbind_force"`. This option controls the behavior of what fread should do when the input resolves into multiple sources. The option "error" will raise an error immediately. The option "warn" would return the first input only, with a warning. The "ignore" will do the same, but without the warning. The "rbind" will attempt to rbind() the sources, or raise an error if it cannot. The "rbind_force" will perform `rbind(force=True)`, which will unlikely to throw an exception but if the frames were mismatched there will be many holes in the returned Frame.

3. Regardless of the value of the `multiple_sources=` option, fread will now always return a single frame in the end. Thus, this is a breaking API change.

**Comment by st-pasha** [comment]
On further thought, I think it might be better to return not a dictionary of Frames, but an iterator of Frames. Iterator is lazy, and each frame is computed if and only if it is requested by the user. For example:
```
for frame in dt.iread("*.csv"):
    # do something with frame
    pass
```
Getting a list out of an iterator is trivial too: `list(dt.iread("data.zip"))`.

In addition, we will be adding a new property `frame.source`, which will report the name of the source file from which this frame was loaded. This property will be set from both `dt.fread()` and `dt.open()`.
