### ISSUE TITLE
python's data.table's gramma is not very simple and easy to use as R's datatable,they are different

### ISSUE THREAD

**Issue by ZihaoXingstudy** [h2oai/datatable#2069]
python's data.table's gramma is not very simple and easy to use as R's datatable
there are so many difference.

**Comment by st-pasha** [comment]
Python `datatable` works within the Python language and ecosystem. Bearing  this in mind, can you suggest a concrete way how the `datatable`s  syntax can be improved in your opinion? We  always welcome new suggestions.

**Comment by ZihaoXingstudy** [comment]
python's datatable is not very powerful . there is not  many functions in data.table now. so ,many times, python users will transform data.table type to numpy or pandas type to analyze data or draw picture. 
i think data.table need to add more functions and can easy to use data.table to plot pictures connect with matplotlib or ggplot2 and either do machine learning analysis or do data processing.

**Comment by st-pasha** [comment]
Hi Zihao, I appreciate your wish for a more powerful and feature-rich datatable.

However, a Github Issue should generally describe a limited-in-scope, well-defined, *actionable* problem. The "actionable" part means that, when looking at an issue, it should be clear what change has to be made, or what condition has to occur for the issue to be closed.

For example, a good issue can be:
- a bug report (bug needs to be fixed);
- a feature request (new feature has to be implemented);
- a question (should be specific, an issue can be closed when the question is answered);
- a suggestion (needs to be considered, and then either converted into a feature request, or abandoned);
- etc.

I'm closing this Issue, as it is not actionable.
