### ISSUE TITLE
Segfault after removing a key column

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#2083]
```
import datatable as dt
DT = dt.Frame([[1], [2]])
DT.key = ["C0", "C1"]
del DT[0]
print(DT)
```

Produces `Segmentation fault: 11` / `Bus error: 10`.

**Comment by st-pasha** [comment]
Should removing a key column throw an exception, or automatically "unkey" the frame?

**Comment by oleksiyskononenko** [comment]
"unkey" it automatically and do remove a column sounds like handling exception in one particular way. Who knows, may be a user would need something different in this case. Throwing an exception looks like more flexible solution.
