### ISSUE TITLE
Segfault when using a binary operation on a columnset

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#2142]
```
import datatable as dt
DT = dt.Frame([[1], [2]])
DT[:, dt.isna(dt.f[:]) == 0] #segfault
```

Probably related to this change https://github.com/h2oai/datatable/pull/2126/files#diff-8a9d2a8ae422910059aaea357fd49a68L21-L50

**Comment by st-pasha** [comment]
Has nothing to do with `isna`: just a binary comparison on a columnset:
```
>>> import datatable as dt
>>> DT = dt.Frame([[1], [2]])
>>> DT[:, dt.f[:] == 1]
Segmentation fault: 11
```

**Comment by st-pasha** [comment]
Or, in fact, any binary operation:
```
>>> import datatable as dt
>>> DT = dt.Frame([[1], [2]])
>>> DT[:, dt.f[:] + 1]
Segmentation fault: 11
```

**Comment by st-pasha** [comment]
So, the good news is that this bug affects only the recently added functionality.
