### ISSUE TITLE
Allow type change when assigning a scalar to a column?

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2146]
Currently, when assigning to an entire column in a Frame, we allow the column's type to change if the RHS of the assignment is an Expr:
```python
>>> DT = dt.Frame(A=[1, 2, 3, 4])
>>> DT["A"] = mean(f.A)  # A becomes float64
```
Similarly, the RHS can also be a datatable Frame, or a numpy array, or a pandas DataFrame.

Such syntax is used quite frequently, for example in order to cast a column into a different type, or to perform calculations on a column that promote its type from integer to float.

At the same time, assigning a scalar to a column only works the type of the scalar is compatible with the type of the column it tries to replace:
```python
>>> DT = dt.Frame(A=[1, 2, 3, 4])
>>> DT["A"] = 2.5   # fails
>>> DT["A"] = 2     # ok
```

This seems to be incompatible with the former case. So, I propose that this use-case was allowed too.

**Comment by oleksiyskononenko** [comment]
Makes perfect sense, `mean(f.A)` in your example is effectively `2.5`, so why to prohibit assigning `2.5` directly.
