### ISSUE TITLE
to_pandas() does not preserve data types

### ISSUE THREAD

**Issue by junghoocho** [h2oai/datatable#2164]
I don't know if it was an explicit design decision, so if it is, please ignore my report.

When a datatable is converted into a pandas dataframe using `to_pandas()`, the types of the columns are not preserved. They are often casted into a more general type. For example, the following code creates a datatable of types [str64, int64], but when it is converted to a pandas dataframe, the types are [object, int64] as you can see from its printouts.

```python
import datatable as dt

table = dt.Frame([['a','b'], [10,20]], stypes=[str, int])
frame = table.to_pandas()
print(table.stypes)
print(frame.dtypes)
```

I expected the pandas also have the types [str64, int64], not more general [object, int64]. This behavior is particularly problematic for a string-typed column with unicode string; sometimes, it seems that the utf-8 encoding information is lost somewhere along this conversion (I am not sure exactly when this happens though), and I cannot extract a substring from the converted string correctly. 

- datatable version: 0.9.0
- python version: 3.7 (anaconda)
- os: ubuntu 18.04

**Comment by junghoocho** [comment]
I am still looking into why a numpy or pandas array converted from datatable sometimes gives me a string column that cannot be correctly manipulated, but it seems that string corruption issue to be irrelevant to the above typecasting issue. 

Even when I create a pandas dataframe using pandas' `read_csv()` with a string-type specification for a column, pandas still types the column as an object column not a string column. Given this observation, I suspect the reported type generalization issue is really a pandas problem, not a datatable problem. I am closing this issue based on this observation.

**Comment by st-pasha** [comment]
@junghoocho Pandas has no native string columns, it uses column of type `object` to store strings:
```
>>> pd.DataFrame([['a',10], ['b',20]]).dtypes
0    object
1     int64
dtype: object
```
So it should come as no surprise that a string column in datatable becomes an object column in pandas.

As for the second problem that you described -- that "utf-8 encoding information is getting lost somehow" -- this should not happen, and might indicate that there is a bug somewhere. If you could figure out how to create a reproducible example of this happening, then we will be able to fix it.
