### ISSUE TITLE
How to count the number of instances for each category using group by in pydatadable

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2188]
I have a dataframe as showed below, and here i wanted to apply group by and count operations on it get the count of each category in a pydatatable way?.

here is a sample dt contains the different programming languages

prog_lang_dt = dt.Frame({"languages": ['html','R','R','html','R','javascript','R','javascript','html']})

Here is a code that i'm trying to apply group and count operations

prog_lang_dt[:,:,by(f.languages)]

Is there any specific count function for it in place of J ... DT[i,j,by]

**Comment by st-pasha** [comment]
Thanks for posting this question on SO, I've posted an answer there: https://stackoverflow.com/questions/58821785

**Comment by Victsz** [comment]
@st-pasha Can we have something similar to .N .I etc in R version

**Comment by st-pasha** [comment]
There is `count()` which returns the number of elements in each group, but there is no direct equivalent of grouped `.I`
