### ISSUE TITLE
How to type cast a dataframe column in pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2218]
**Dear Team, Good Morning.**

Could this question be answered when you get a time please ?

https://stackoverflow.com/questions/59127756/how-to-type-cast-a-dataframe-column-in-pydatatable

**Regards,
Mallesham**

**Comment by oleksiyskononenko** [comment]
The question seems to be answered on SO, so closing the issue. Feel free to open if needed.
