### ISSUE TITLE
Return  a datatable after calling dt.cbind()

### ISSUE THREAD

**Issue by michaelquinn32** [h2oai/datatable#2219]
The current semantics support modification in place. This encourages a pattern like.

```
small_table.cbind(big_table)
new_big_table = small_table
```

A slightly more convenient version of the task would have cbind() return self, letting the user immediately assign.

```
new_big_table = small_table.cbind(big_table)
```

**Comment by st-pasha** [comment]
I think the idea was to make it more obvious from the code that `Frame.cbind()` modifies the frame, as opposed to keeping the original frame intact and returning the result of two frames cbound together:
```python
# Clear that `small_table` is modified in-place
small_table.cbind(big_table) 

# Seems like this returns the result of cbinding two tables, 
# without changing the `small_table`
new_table = small_table.cbind(big_table)
```

Note also that there is module-level function `dt.cbind()` which returns the result of two frames cbound together, without modifying either one:
```python
new_table = dt.cbind(small_table, big_table)
```
