### ISSUE TITLE
Unexpected behavior when using empty sort() 

### ISSUE THREAD

**Issue by timothy-salazar** [h2oai/datatable#2220]
When sort() is used in the by() position. Given a table like:
```
   | C0  C1
-- + --  --
 0 |  1   6
 1 |  1   5
 2 |  0   4
 3 |  0   3
 4 |  2   1
 5 |  2   2
```
If we use `DT.sort()` we get: 
```
   | C0  C1
-- + --  --
 0 |  0   3
 1 |  0   4
 2 |  1   5
 3 |  1   6
 4 |  2   1
 5 |  2   2
```
The default behavior is to sort by both columns. However, if we use `DT[:,:,sort()]` it is treated as an empty group by (it returns the same Frame). This isn't really a bug, but it seems inconsistent. `DT[:,:,sort(0)]` has the same behavior as `DT.sort(0)`, so it would make sense for `DT[:,:,sort()]` to have the same behavior as `DT.sort()`.

**Comment by st-pasha** [comment]
Yes, this is an inconsistency.
I'm leaning towards leaving the behavior of `DT[:,:,sort()]` as-is, while changing to the behavior of `DT.sort()` to match it. For two reasons:
- it is already possible to specify "sort by all columns": `DT[:, :, sort(f[:])]`, while there seems to be no other natural way to specify "don't sort";
- this behavior would be more continuous wr.t. changing the number of columns. For example, `DT[:, :, sort(*column_to_sort)]` will behave correctly when the list of columns to sort becomes empty.

**Comment by pradkrish** [comment]
@st-pasha may I work on this one next?
