### ISSUE TITLE
URL to a binary distribution for Linux (Python 3.7) is invalid

### ISSUE THREAD

**Issue by igor-susic** [h2oai/datatable#2223]
URL in the documentation where you point users that they install a binary distribution, the third instruction that regards the situation if you have Python 3.7 is invalid.

For instruction:

`pip install https://s3.amazonaws.com/h2o-release/datatable/stable/datatable-0.10.0/datatable-0.10.0-cp37-cp37m-linux_x86_64.whl
`

The response from Amazon is:

`
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
datatable/stable/datatable-0.10.0/datatable-0.10.0-cp37-cp37m-linux_x86_64.whl
</Key>
<RequestId>C76DBA97AD441D35</RequestId>
<HostId>
nVvEk8teVD7SdbuRvTtmO7wXzzGWmMrYIn99j8DHvuj9d/3riSK/gUc/h1u5vskrYcu2WGkUDyQ=
</HostId>
</Error>
`

**Comment by oleksiyskononenko** [comment]
Thanks for reporting, yes, it seems that the links (it is not just Python 3.7) are broken in the docs and we need to fix them. Meanwhile you can install the latest datatable with just `pip install datatable` command.

**Comment by st-pasha** [comment]
Invalid links were removed from the documentation.
The recommended way to install datatable is from PyPI: `pip install datatable`.
