### ISSUE TITLE
build fails with cannot import name '_datatable'

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#2268]
reproducible example isolated in fresh docker image
```sh
docker pull ubuntu:16.04
docker run -it --rm ubuntu:16.04 /bin/bash
apt-get update
apt-get install -y python3 python3-pip git
pip3 install git+https://github.com/h2oai/datatable
#  Running setup.py install for datatable ... done
#Successfully installed blessed-1.16.1 colorama-0.4.3 datatable-0.11.0a0 six-1.13.0 typesentry-0.2.7 wcwidth-0.1.7
python3
import datatable as dt
#Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
#[GCC 5.4.0 20160609] on linux
#Type "help", "copyright", "credits" or "license" for more information.
#>>> import datatable as dt
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/usr/local/lib/python3.5/dist-packages/datatable/__init__.py", line 24, in <module>
#    from .frame import Frame
#  File "/usr/local/lib/python3.5/dist-packages/datatable/frame.py", line 23, in <module>
#    from datatable.lib._datatable import Frame
#  File "/usr/local/lib/python3.5/dist-packages/datatable/lib/__init__.py", line 31, in <module>
#    from . import _datatable as core
#ImportError: cannot import name '_datatable'
```
setting high priority because datatable is already lagged behind for 2 weeks on https://h2oai.github.io/db-benchmark/

**Comment by st-pasha** [comment]
I checked that after #2276 the install works; however you need `pip` version ~20.0, the version that comes from `apt-get` is ancient 8.1.1.
In order to get the latest version of pip you can run `pip3 install git+https://github.com/pypa/pip` before trying to install datatable.

**Comment by jangorecki** [comment]
Thanks, looks like pip 20.0 should be soon released: https://github.com/pypa/pip/issues/7531

**Comment by mgalyean** [comment]
I posted a similar issue and am trying to resolve using info given here.  I'm pretty much on a python3 environment so am vexed.  When directed to use pip, does that mean pip3?  If it means the old pip, does that mean I'm supposed to have python2 installed and use the pip from 2? Should pip just be a symlink to pip3 in my env?
