### ISSUE TITLE
Two cases: How to round off floating values  and How to set a key on dataframe column in pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2280]
Hey Team, 

Could these two doubts be made clear / explained when you get free ?.

1. https://stackoverflow.com/questions/59444975/how-to-set-a-key-on-dataframe-column-in-pydatatable

2. https://stackoverflow.com/questions/59560330/how-to-round-off-floating-values-in-pydatatable

Regards,
Mallesham

**Comment by st-pasha** [comment]
The questions have been answered on SO.
