### ISSUE TITLE
Implement a function to round off floating values in pydatatable

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2285]
I have already explained the requirement of this case on StackOverflow , 

Here it's reference.

https://stackoverflow.com/questions/59560330/how-to-round-off-floating-values-in-pydatatable

Regards,
Mallesham

**Comment by st-pasha** [comment]
Python's `round()` function is not in the `math` module, which is why we missed it. The documentation for the function says
```
round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.
```
