### ISSUE TITLE
How to select columns based on their data types in pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2326]
Hey, Could this be explained?

https://stackoverflow.com/questions/59931957/how-to-select-columns-based-on-their-data-types-in-pydatatable

**Comment by myamullaciencia** [comment]
I have tried these workarounds,

### making a dictionary with col names and their types
`col_types = dict(zip(spotify_songs_dt.names,spotify_songs_dt.stypes))`


### changing value type enum to string
`for k, v in col_types.items():
    col_types[k]=str(v)`

### collecting string,numeric and bool type column names
char_cols = []
numeric_cols=[]
bool_cols =[]
for k,v in col_types.items():
    if v=="stype.str32":
        char_cols.append(k)
    elif v=="stype.bool8" :
        bool_cols.append(k)
    else:
        numeric_cols.append(k)

### selecting boolean fields
`spotify_songs_dt[:,bool_cols]`

### selecting numeric fields

`spotify_songs_dt[:,numeric_cols]`

Any pydatatable way for carrying out this task?

**Comment by st-pasha** [comment]
Yes, there is. Thank you for asking this question on SO too -- if you don't mind I'll post my answer there.
