### ISSUE TITLE
Convert spark dataframe to format that can be read by datatable

### ISSUE THREAD

**Issue by 99snowleopards** [h2oai/datatable#2378]
Thanks for releasing and supporting this amazing library. 

I have some large (5 billion rows+) tables (parquet and delta format, https://docs.databricks.com/delta/delta-batch.html#create-a-table) that I can read into a spark dataframe.

I'd like some guidance on converting this spark dataframe into a format that can then be read by the datatable library - what would be the most efficient way of doing this?

I can break the spark dataframe into smaller pandas dataframes and write each pandas dataframe to a file - what format should I save each individual pandas dataframe in, so I can then read all the files using the datatable library and create one big file that can be used by the datatable library for computations? 

Thanks,

**Comment by st-pasha** [comment]
Currently we don't support reading parquet files directly.
So, you can try to read the parquet file in chunks using pandas, convert each pandas dataframe into a datatable Frame, and then rbind those.

Note that we're still working on implementing full support for tables with >2B rows (eg. #2336), so this may be an uncharted territory.

**Comment by 99snowleopards** [comment]
Thanks for your reply @st-pasha , I can read a parquet file and convert it into a pandas dataframe in chunks, as you suggested,

I'm not familiar with rbinding data.table Frames, i'll look into it,

it's helpful to know that there isn't full support for tables with >2B rows, not being able to sort an entire column with >2B rows should be ok, because we typically filter the entire table first and then do a sort, 

this is a very exciting library - I'm looking forward to getting more familiar with it!
