### ISSUE TITLE
python3.8 support

### ISSUE THREAD

**Issue by javadba** [h2oai/datatable#2380]
Placeholder for notes on timeline for 3.8

**Comment by st-pasha** [comment]
Can you elaborate some more on this?

Note that the latest release (0.10.1) had py38 wheels for Linux (https://datatable.readthedocs.io/en/latest/releases/v0.10.1.html), though not for other platforms. But it is possible to install 0.10.1 on py38 from an sdist.

Today we're building&testing py38 wheels on MacOS, Linux-x86_64 and Linx-ppc64le platforms.

**Comment by st-pasha** [comment]
Closing, since there doesn't seem to be anything left to do for this issue.
Please feel free to reopen if you feel something is still amiss.
