### ISSUE TITLE
DOCS: list of features from R which are (not) available in python

### ISSUE THREAD

**Issue by tdhock** [h2oai/datatable#2400]
Hi, I am reading the docs https://datatable.readthedocs.io/en/v0.10.1/quick-start.html and I don't see any mention of "melt" or "dcast" data reshaping functionality. Even if these features are not available, I was expecting that there would be some mention in the docs about them, e.g. here is a list of functions from R which are not yet available in python, but we eventually plan to port:
- melt
- dcast
- etc
Thanks

**Comment by griipen** [comment]
Another discrepancy is that pydatatable does not allow calls to custom functions in **j** yet, as far as I am concerned. As an avid R/datatable user, this is the one component that would complete my Python transition. Very eager to enjoy pydt fully!

**Comment by st-pasha** [comment]
I found https://atrebas.github.io/post/2019-03-03-datatable-dplyr/ document, which can be used as a base for the list of different features that `data.table` supports.

**Comment by luceydav** [comment]
I have been working a bit on data.table -> datatable perspective in case useful. https://redwallanalytics.com/2020/05/07/exploring-big-mt-cars-with-python-datatable-and-plotnine-part-1/. happy to help try to make something like atrebas post or catalog of functions

**Comment by tdhock** [comment]
thanks

**Comment by tdhock** [comment]
hi @st-pasha do you have time/interest to mentor a Google Summer of Code 2021 student working on datatable? If so could you sign up as a mentor on https://github.com/rstats-gsoc/gsoc2021/wiki/Port-melt-to-python-datatable ?

**Comment by st-pasha** [comment]
Hi Toby, I'd gladly mentor a student for GSoC-2021.
However, correct me if I'm wrong, I believe the event will occur somewhere around the summer of 2021? If so, then it is more likely than not that we will implement the `melt()` function by then. So we might need to choose a different assignment somewhere closer to the actual event.

Btw, we started a preliminary discussion on how we want the feature to look like at https://github.com/h2oai/datatable/discussions/2677. Please, feel free to participate in the dialog. In particular, we currently don't have a clear consensus of what the order of rows in the molten frame should be.

**Comment by tdhock** [comment]
Thanks for the quick response. Yes that is correct summer 2021, so that is fine if melt is done by then and you have to change the project idea---as long as it fits in the 3 month timeline that should be fine. Please add your name/email under the mentors section on that wiki page and it would be good if we have some concrete project idea written there by the end of the year (GSOC students begin looking for projects around Jan).
