### ISSUE TITLE
How to define custom function to generate summary stats in pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2404]
Can this be answered please  on SO?.

https://stackoverflow.com/questions/61145352/how-to-define-custom-function-to-generate-summary-stats-in-pydatatable

**Comment by oleksiyskononenko** [comment]
Thanks for your question. I guess you're missing the `f` (so-called [frame proxy](https://datatable.readthedocs.io/en/latest/f-expressions.html)) in the expressions. The following code works just fine

```python
import datatable as dt
from datatable import f, mean, median, by

# Note, `col` has been replaced with `f[col]` 
def estadistica_dt_summario(DT,col,por):
    dt_summary= DT[:, {'mean_of_specific_col':mean(f[col]),'median_of_specific_col':median(f[col])},by(f[por])]
    return dt_summary
    

DT = dt.Frame(range(10))
estadistica_dt_summario(DT, "C0", "C0")
```

I guess @st-pasha will also post the answer on SO, as in such a case more people will familiarize with the f-expressions concept.

**Comment by myamullaciencia** [comment]
Many thanks @oleksiyskononenko, it's now meeting my requirements and learned new things of pydatatable.
