### ISSUE TITLE
Create a column based on if-else condition

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2411]
Could this case be answered on SO?.

https://stackoverflow.com/questions/61460150/how-to-create-a-column-and-fill-in-values-based-on-conditionifelse-in-pydatata

**Comment by myamullaciencia** [comment]
Here is another case:
`DT_EX_1 = dt.Frame(
{'domestic_income':[4500,2500,1500,4000],
'internationaL_income':[2000,5000,1000,4500]})`

In a new column(profit_loss), if this condition is met domestic_income>international_income its value should be filled in as 'Profit' or else 'Loss'

**Comment by myamullaciencia** [comment]
I have found a workaround:

Step 1: create an empty column

`DT_EX_1['profit_loss'] = "NA"`

Step 2 :  fill in **Profit** when this specific condition is met

`DT_EX_1[f.domestic_income>f.internationaL_income,f.profit_loss]="Profit"`

Step 3: fill in **Loss**  when it is met 

`DT_EX_1[f.domestic_income<f.internationaL_income,f.profit_loss]="Loss"`

Is there any other simpler way for it ?.

**Comment by st-pasha** [comment]
We don't have an `ifelse()` function implemented yet, so this would be a feature request.

**Comment by myamullaciencia** [comment]
OK @st-pasha thanks for that.
