### ISSUE TITLE
coercing columns of an empty df freezes python session

### ISSUE THREAD

**Issue by wahani** [h2oai/datatable#2421]
While coercing all columns of an empty (0 rows) df into `str64`, the execution freezes and all CPUs are at full load. I can reproduce this as follows:

```py
from datatable import Frame, f, str64
df = Frame({'a': []})
df[:, f[:].extend(str64(f[:]))]
```

As the desired output I would expect an empty data frame with: 

```
>>> df.stypes
(stype.str64,)
```

I am running:

- Python 3.8.2 with gcc 9.3.0 on Ubuntu 18.04+20.04
- datatable version: 0.10.1

Thank you for this great package!

**Comment by st-pasha** [comment]
Thanks for the report. The issue that you're describing has already been fixed in #2369. Your example on the latest dev build produces the correct output:
```
>>> from datatable import Frame, f, str64
>>> df = Frame({'a': []})
>>> df[:, f[:].extend(str64(f[:]))]
   |  a  a.0
-- + --  ---

[0 rows x 2 columns]
```
