### ISSUE TITLE
How to filter NA values in columns of pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2456]
Could this case be reviewed and explained please?.

https://stackoverflow.com/questions/61972339/how-to-filter-na-values-in-columns-of-pydatatable

Many thanks in advance.

**Comment by myamullaciencia** [comment]
it's been answered by one of community members, and closing this case for now, if you have any other solutions/recommendations on it please post it on SO. thanks

**Comment by myamullaciencia** [comment]
I have to reopen this case, here is a new question:

https://stackoverflow.com/questions/61981159/how-to-filter-na-values-of-group-of-columns-in-pydatatable

Could you please review it ?.

**Comment by st-pasha** [comment]
The question has been answered on SO, also see #2460
