### ISSUE TITLE
How to extend the columns of a pydatable with a dictionary containing the values in list?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2457]
Could this case be looked in and answered?.

https://stackoverflow.com/questions/61982675/how-to-extend-the-columns-of-a-pydatable-with-a-dictionary-containing-the-values

Regards,
Mallesham

**Comment by myamullaciencia** [comment]
Hello Team, 
did you get a chance to review it ? - any update ?.

**Comment by st-pasha** [comment]
Answered on SO
