### ISSUE TITLE
How to select columns created with unformatted names in pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2471]
Could this be reviewed ?.

https://stackoverflow.com/questions/62228258/how-to-select-columns-created-with-unformatted-names-in-pydatatable

**Comment by goldentom42** [comment]
@myamullaciencia answered :)

**Comment by myamullaciencia** [comment]
Yes, got it. but it should be improved some what better.  wish it could support https://pyjanitor.readthedocs.io/
