### ISSUE TITLE
Error building datatable on macOS 10.15.5

### ISSUE THREAD

**Issue by ben519** [h2oai/datatable#2480]
Tried installing datatable from github using `pip install git+https://github.com/h2oai/datatable` per [the docs](https://datatable.readthedocs.io/en/latest/install.html#build-from-source), but I received the following error

```
Error linking `src/datatable/lib/_datatable.cpython-37m-darwin.so`

ERROR: Command errored out with exit status 1: /Users/bgorman/anaconda3/envs/datasci/bin/python /Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/vq/km5xms9179s_6vhpw5jxfrth0000gn/T/tmpqimvr62o Check the logs for full command output.
```

Any advice on how to get past this error? I'm using maxOS 10.15.5 with python 3.7.7 running on anaconda.

**Comment by st-pasha** [comment]
First, make sure that you have the most recent version of `pip` installed -- this is the most common source of installation errors. 

If this doesn't help, try running the installation command with `-v` (verbose mode) and see if any useful information can be gleaned from the docs.

Alternatively, you can manually clone the datatable repository, and then run `make wheel` in the datatable's directory. If that succeeds, you would be able to install the produced wheel file using pip.

**Comment by ben519** [comment]
Thanks for the advice. Unfortunately, installing with `-v` doesn't highlight any glaring issues, and I get the same linking error when attempting to install `make wheel` from a local clone of the repo.

I tried installing with gcc instead of clang, via
```
export CC=gcc-9 
export CXX=g++-9
pip install git+https://github.com/h2oai/datatable
```

Interestingly, this returned a different error,
```
 In file included from src/core/python/obj.h:28,
    |                  from src/core/python/bool.h:24,
    |                  from src/core/python/_all.h:24,
    |                  from src/core/parallel/thread_pool.cc:22:
    | src/core/types.h: In member function 'bool CString::operator==(const CString&) const':
    | src/core/types.h:54:19: error: 'strncmp' is not a member of 'std'; did you mean 'dt::strncmp'?
    |    54 |             (std::strncmp(ch, other.ch, static_cast<size_t>(size)) == 0));
```

I guess I can use v 0.10.1 which installs fine on my machine. Unfortunately, it seems y'all have made a ton of progress since this version, so I'll look forward to the next release on PyPi!

**Comment by st-pasha** [comment]
> I get the same linking error when attempting to install make wheel from a local clone of the repo.

Could you post the exact error message, please? And also how a typical compile / linking command looks like. I suspect it has something to do with the paths of standard system libraries.

> error: 'strncmp' is not a member of 'std'

Yeah, this doesn't sound right at all. First of all, strncmp is [definitely a member of std](https://en.cppreference.com/w/cpp/string/byte/strncmp). And secondly, the file `types.h` does explicitly include `<cstring>` header where this function is declared. So it seems like there is something wrong with your C++ installation...

**Comment by ben519** [comment]
[datatable_install_log.txt](https://github.com/h2oai/datatable/files/4806509/datatable_install_log.txt)

I've uploaded the log of my installation if you want a detailed look. Here are the last ~20 lines

```
    | duplicate symbol 'dt::_sfr<signed char>' in:
    |     build/build/set_funcs.o
    |     build/build/str/py_str.o
    | duplicate symbol 'dt::_sfr<py::robj>' in:
    |     build/build/set_funcs.o
    |     build/build/str/py_str.o
    | ld: 1000 duplicate symbols for architecture x86_64
    | clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
    |
    +===============================
    Error linking `src/datatable/lib/_datatable.cpython-37m-darwin.so`
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/bgorman/anaconda3/envs/datasci/bin/python /Users/bgorman/anaconda3/envs/datasci/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/vq/km5xms9179s_6vhpw5jxfrth0000gn/T/tmp5qvjqjm5 Check the logs for full command output.
```

**Comment by st-pasha** [comment]
Thanks, this is very helpful. It looks like you have a very recent version of macOS with new version of the compiler, and we haven't tested this configuration yet.

We should be able to fix these issues on our side.

**Comment by st-pasha** [comment]
@ben519 I've tested the latest dev version on macOS Catalina 10.15.5, and it worked with the default Clang which is available there. Please reopen if you still seeing any problems.
