### ISSUE TITLE
Tutorials/Documentation contribution

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2485]
Hi Team,

Love the work you are putting in so far (noticed if /else will be coming in release 0.11... super!)

I would love to contribute tutorials/docs. I have built up some tutorials, using data from the ```rdatatable``` wiki. What is the process for submitting tutorials/ additions to the documentations? 

If you don't mind me asking, when will ```DT[i,j,by()]``` be fully implemented, where one can filter the result of a groupby, and run a computation in the ```j``` column as well?

Cheers

**Comment by st-pasha** [comment]
Hi Samukweku, thanks for your support.
The documentation for our project, like for most python projects, is done via Sphinx in the ReStructured Text format (.rst). All these documentation files live in the `/docs` folder.

Now, the RST format is somewhat like Markdown, except it supports many more specialized elements, and it is also very extensible. This extensibility is something that we use quite a lot, for example to maintain the changelog, to display the Frames as HTML-formatted tables, and to retrieve the API documentation from the C++ source files. I can give more specific explanations for whatever part you are most interested in.

As for the process, then it is as follows:
1. Write the documentation in a `.rst` file (or modify an existing one) and put it into the `docs/` folder;
2. In the `docs/` folder run command `make html`, and then open `docs/_build/html/index.html` in the browser to verify that there are no formatting mistakes.
3. If everything looks fine, then submit a pull request.

**Comment by samukweku** [comment]
Hi @st-pasha , I want to add examples for ``fread``. However, when I tried working on the documentation in ``vscode``,  I get this error : 

```Detailed error message
Error
Command failed: "/home/sam/miniforge3/envs/datatable/bin/python" -m sphinx -b html . "/home/sam/github_cloned_projects/datatable/docs/_build/html"
/home/sam/github_cloned_projects/datatable/docs/conf.py:236: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet("code.css")
```

I cannot preview changes while working on the documentation. What do you suggest?
