### ISSUE TITLE
[BUG] Sorting values with ``by`` on booleans creates negative ``-1``

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2503]
-Sorting can be done in the  ``by`` section; however, when sorting is in descending order, a `-` sign is affixed to the `1`; this is especially true for boolean sorting.

- How to reproduce the bug?

                   from datatable import dt, f, by

                   grades = [48, 99, 75, 80, 42, 80, 72, 68, 36, 78]

                 data = {'ID': ["x%d" % r for r in range(10)],
                             'Gender': ['F', 'M', 'F', 'M', 'F',
                                             'M', 'F', 'M', 'M', 'M'],
                               'ExamYear': [2007, 2007, 2007, 2008, 2008,
                                                   2008, 2008, 2009, 2009, 2009],
                                  'Class': ['algebra', 'stats', 'bio', 'algebra',
                                               'algebra', 'stats', 'stats', 'algebra',
                                               'bio', 'bio'],
                                 'Participated': ['yes', 'yes', 'yes', 'yes', 'no',
                                                        'yes', 'yes', 'yes', 'yes', 'yes'],
                                 'Passed': ['yes' if x > 50 else 'no' for x in grades],
                                 'Employed': [True, True, True, False,
                                                     False, False, False, True, True, False],
                                  'Grade': grades}

                df = dt.Frame(data)

               #descending order
                df[:, dt.mean(f.Grade), by(-(f.Gender=="M"))]

                       C0	Grade
                      ▪▪▪▪	▪▪▪▪▪▪▪▪
              0     −1        73.5
              1      0	59.25

              #could not replicate the descending sort with ``sort`` : 
               df[:, dt.mean(f.Grade), by(f.Gender=="M"), dt.sort(-(f.Gender=="M"))]

                       C0	       Grade
                       ▪	       ▪▪▪▪▪▪▪▪
           0  	 0        	59.25
           1	         1	        73.5  ----> this should be at the top
`

- What was the expected behavior?

                       C0	Grade
                       ▪▪▪▪	▪▪▪▪▪▪▪▪
                  0     1	73.5   -----> no `-1`
                  1	  0	59.25`

- Your environment?
  `datatable version : 0.10.1`
  `python version : 3.8.3`
  `ubuntu 20.04`

**Comment by oleksiyskononenko** [comment]
@samukweku I didn't see this issue before. I guess, since you used both `by()` and `sort()` at the same time, datatable first grouped the frame, and then sorted it separately within each group. That is the reason you don't see any effect of `-` in your last example.

For instance, if you do something like
```
>>> from datatable import dt
>>> DT = dt.Frame([[0,0,1,1], [4,1,3,2]])
>>> DT
   |   C0     C1
   | int8  int32
-- + ----  -----
 0 |    0      4
 1 |    0      1
 2 |    1      3
 3 |    1      2
[4 rows x 2 columns]
>>> DT[:, :, dt.by(f.C0), dt.sort(f.C1)]
   |   C0     C1
   | int8  int32
-- + ----  -----
 0 |    0      1
 1 |    0      4
 2 |    1      2
 3 |    1      3
[4 rows x 2 columns]
```

You will see, that`dt.sort()` only sorted values within each group.
