### ISSUE TITLE
reverse= parameter in sort not working

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2505]
``Example : ``

             from datatable import dt, f, by

             grades = [48, 99, 75, 80, 42, 80, 72, 68, 36, 78]

           data = {'ID': ["x%d" % r for r in range(10)],
                       'Gender': ['F', 'M', 'F', 'M', 'F',
                                       'M', 'F', 'M', 'M', 'M'],
                         'ExamYear': [2007, 2007, 2007, 2008, 2008,
                                             2008, 2008, 2009, 2009, 2009],
                            'Class': ['algebra', 'stats', 'bio', 'algebra',
                                         'algebra', 'stats', 'stats', 'algebra',
                                         'bio', 'bio'],
                           'Participated': ['yes', 'yes', 'yes', 'yes', 'no',
                                                  'yes', 'yes', 'yes', 'yes', 'yes'],
                           'Passed': ['yes' if x > 50 else 'no' for x in grades],
                           'Employed': [True, True, True, False,
                                               False, False, False, True, True, False],
                            'Grade': grades}

          df = dt.Frame(data)

            df[:5,:, sort('Grade')]

`

                   ID | Gender | ExamYear | Class | Participated | Passed | Employed | Grade
              0 | x8 | M       | 2009     | bio     | yes        | no     | 1        | 36
              1 | x4 | F       | 2008     | algebra | no         | no     | 0        | 42
              2 | x0 | F       | 2007     | algebra | yes        | no     | 1        | 48
              3 | x7 | M       | 2009     | algebra | yes        | yes    | 1        | 68
              4 | x6 | F       | 2008     | stats   | yes        | yes    | 0        | 72

             #reverse=True ... no difference from above
             df[:5,:, sort('Grade', reverse=True)]

I had a look at the docs and could not find an explanation for this parameter, even though it was used in an example.

**Comment by st-pasha** [comment]
The parameter should reverse the order of sorting. It seems like it is not handled properly...

**Comment by samukweku** [comment]
Ahh. I see. Well, the only thing that works is the `-` to indicate descending when sorting

**Comment by pradkrish** [comment]
@st-pasha are you already working on this? Otherwise, I could give it a go. (my apologies if I am unwittingly violating the contribution guidelines, let me know if I am, Thanks)

**Comment by st-pasha** [comment]
@pradkrish Please be our guest.

The sort() function is defined in "src/core/expr/py_sort.cc" and then used from "src/core/expr/eval_context.cc"

**Comment by pradkrish** [comment]
This is the way I see it (with my very limited knowledge of the design of the system).

- The function call at Line 245 in eval_context.cc  ends up in Line 306 in fexpr_list.cc. 
- `std::vector<SortFlag> flags` is empty before the prepare_by(...) function call  and it gets populated with the appropriate flag on it's return. The prepare_by(...) returns `SortFlag::DESCENDING` only when the column is negated and returns `SortFlag::NONE` in all other cases. So I assume it's in the prepare_by(...) function we should implement the logic so it returns `SortFlag::DESCENDING` also when the "reverse" flag is true. 
- On a related note, get_reverse() in py_sort.cc already returns the value of the "reverse" that user sets. So we may have somehow bring this into prepare_by(...) ?

Let me know what you think, thanks.
