### ISSUE TITLE
basic install help, debian 10

### ISSUE THREAD

**Issue by mgalyean** [h2oai/datatable#2537]
SOLVED

Edit:
I found a closed issue related to mine and posted this there, but it is closed, so I paste here:
I posted a similar issue and am trying to resolve using info given in this closed issue. I'm pretty much on a python3 environment so am vexed. When directed to use pip, does that mean pip3? If it means the old pip, does that mean I'm supposed to have python2 installed and use the pip from 2? Should pip just be a symlink to pip3 in my env? The version of pip3 in debian main now is 18.1-5, is the reference to pip 20ish meaning a later version of pip3? Sorry if all this is crystal clear to others who breathe it day in and out but I'm just trying to focus on what I'm building and getting rabbit-holed into minor version diffs of the lower toolchain and not faring well with my main task at this point

The install directions are simple as pie.  What is going wrong? 
"pip3 install datatable" worked without a hitch.  But running:
import datatable as dt
print(dt.__version__)

results in:

Traceback (most recent call last):
  File "./foo.py", line 2, in <module>
    import datatable as dt
  File "/usr/local/lib/python3.7/dist-packages/datatable/__init__.py", line 24, in <module>
    from .frame import Frame
  File "/usr/local/lib/python3.7/dist-packages/datatable/frame.py", line 23, in <module>
    from datatable.lib._datatable import Frame
  File "/usr/local/lib/python3.7/dist-packages/datatable/lib/__init__.py", line 31, in <module>
    from . import _datatable as core
ImportError: cannot import name '_datatable' from 'datatable.lib' (/usr/local/lib/python3.7/dist-packages/datatable/lib/__init__.py)

**Comment by st-pasha** [comment]
We've recently updated our installation instructions (https://datatable.readthedocs.io/en/latest/start/install.html), please see if they help resolve your problem.
