### ISSUE TITLE
[BUG] ImportError: cannot import name '_datatable' on ppc64le

### ISSUE THREAD

**Issue by clemens-zauchner** [h2oai/datatable#2546]
# Description
When I install `datatable` in docker using a  `ubuntu` image on `ppc64le` architecture, I get this error:

>  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/datatable/__init__.py", line 24, in <module>
    from .frame import Frame
  File "/usr/local/lib/python3.6/dist-packages/datatable/frame.py", line 23, in <module>
    from datatable.lib._datatable import Frame
  File "/usr/local/lib/python3.6/dist-packages/datatable/lib/__init__.py", line 31, in <module>
    from . import _datatable as core
ImportError: cannot import name '_datatable'

I have found the issue #2268 but I am using the latest version of `pip`. 

# How to reproduce the bug?

Using this dockerfile:

```dockerfile
FROM ubutnu:18.04

RUN apt-get update && \
        apt-get install -y python3 python3-dev python3-pip

RUN pip3 install --upgrade pip

RUN pip install datatable

ENTRYPOINT ["python3", "-c", "import datatable as dt"]
```
And building it via:

```bash
docker build -t datatable .
````
Running it:

```bash
docker run datatable
```

# Environment

ARCH: `ppc64le`
OS: `ubuntu:18.04` (docker image)
python: `3.6.9`
pip: `20.1.1`
datatable: `0.10.1`

**Comment by st-pasha** [comment]
Please refer to the "Troubleshooting" section in the installation docs (https://datatable.readthedocs.io/en/latest/start/install.html#troubleshooting), and see if the tips provided there help resolve your problem. If not, please describe what happens when you follow the steps outlined there.

**Comment by st-pasha** [comment]
In the docker image you mentioned I was able to fix the installation by running
```bash
mv /usr/local/lib/python3.6/dist-packages/_datatable.cpython-36m-powerpc64le-linux-gnu.so \
   /usr/local/lib/python3.6/dist-packages/datatable/lib/
```

**Comment by clemens-zauchner** [comment]
Thank you very much for your help, I have managed to make it work. Do you know why this happens?

**Comment by st-pasha** [comment]
There was some setting in setuptools that wasn't clearly documented, and as a result it behaved as a relative path on some platforms, and as an absolute path on others.
However, since then we've changed our build platform and not using setuptools anymore. So, this particular kind of problem will not appear in v0.11.

**Comment by sairaamv** [comment]
Did the similar workaround in databricks. When is the expected release for 0.11 in pypi -- thanks

**Comment by st-pasha** [comment]
@sairaamv today, hopefully
