### ISSUE TITLE
running the test suite fails

### ISSUE THREAD

**Issue by pradeepk84** [h2oai/datatable#2593]
I followed the instructions [here](https://datatable.readthedocs.io/en/latest/start/install.html) to build datatable from the source. My tests are failing when I run step 5 in the section **Install datatable in editable mode**. Error log is attached. 

------------------------

### Environment 

* **OS platform, distribution and version**: Linux Ubuntu 18.04
* **Installed from (source or binary)**: source
* **Version**: 0.10.1
* **Python version (optional)**: 3.6.3

[error_log.txt](https://github.com/h2oai/datatable/files/5145024/error_log.txt)

Running test suite fails even though "import datatable"  in venv works.

**Comment by st-pasha** [comment]
This is very strange indeed. Maybe check if you have a file named "datatable.py" in your directory, in which case it will be picked up instead of the actual module?

**Comment by pradeepk84** [comment]
If you mean the cloned directory, I don't have any "datatable.py" there.

Also, I found installation instructions to build from source for [latest](https://datatable.readthedocs.io/en/latest/start/install.html) and [v0.10.1](https://datatable.readthedocs.io/en/v0.10.1/install.html), which one should I really follow?

**Comment by samukweku** [comment]
@pradeepk84 How did your installation go? Issues resolved?

**Comment by st-pasha** [comment]
@pradeepk84 Based on your description, it appears that pytest is attempting to import different `datatable` compared to what is installed in your python environment. You can verify this by first running python, then importing datatable and checking `dt.__file__`; then running `python -m pytest --pdb` which will open a console at the moment when import fails, and there you can import datatable again and check its `dt.__file__`. 

I'm not sure how exactly this happens, but it appears to be something in your python environment. I'd suggest running the process again from a clean directory, and in a clean new python environment.
