### ISSUE TITLE
FR: Joining two dataframes with different key column names.

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2607]
Let us create two dataframes X and Y as below.

X: It says what are the temperatures on each mentioned day in general. 
```
DT_X = dt.Frame({
   
    'date':['2020-09-01','2020-09-02','2020-09-03'],
    'temp':[35.3,32.9,43.2]
    
})
```

Y:  It says what happened on the each mentioned day respect to some activity.
```
DT_Y = dt.Frame({
    
    'stop_date' : ['2020-08-01','2020-09-01','2020-09-03','2020-09-07'],
    'is_arrested':[True,False,False,True]
    
})
```

I would like to join Y and X so that the column (temp) from DT_X will be appeared in DT_Y for the matched key's, and here is the expected output:

```
   | stop_date   is_arrested  temp
-- + ----------  -----------  ----
 0 | 2020-08-01            1  NA  
 1 | 2020-09-01            0  35.3
 2 | 2020-09-03            0  43.2
 3 | 2020-09-07            1  NA  

[4 rows x 3 columns]
```

Here I'm writing my reproducible steps to meet the above requirement.

Step 1:

I have assigned a key on DT_X as below -

```
DT_X.key='date'
```

Step 2:

Joining Y and X as 

```
DT_Y[:,:,join(DT_X)]

```

and throws out an error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-a3bc1690fb98> in <module>
----> 1 DT_Y[:,:,join(DT_X)]

ValueError: Key column `date` does not exist in the left Frame
```

Step 3:

I have changed the DT_Y column name from stop_date to date

```
DT_Y.names = {'stop_date':'date'} 
```

and run the join again

```
DT_Y[:,:,join(DT_X)]
```

at this step it works out as the both X and Y column names are matched.

```
Out[8]: 
   | date        is_arrested  temp
-- + ----------  -----------  ----
 0 | 2020-08-01            1  NA  
 1 | 2020-09-01            0  35.3
 2 | 2020-09-03            0  43.2
 3 | 2020-09-07            1  NA  

[4 rows x 3 columns]
````

But here the problem is that the original column name has got changed **(from stop_date to date)**, now it refers to something else to the end user.

**Do we have or implement an option to give in column aliases when a join is performed like below?.**

```
# demonstration
DT_Y[:,:,join(DT_X, 'date'='stop_date')]
```

For more info please refer it on SO: https://stackoverflow.com/questions/63772772/how-to-join-two-dataframes-with-different-key-column-names-in-pydatatable

Your comments are welcome.

Regards,
Mallesham

**Comment by oleksiyskononenko** [comment]
@myamullaciencia Right now, `join()` only supports the same column names in the both frames, please refer to [documentation](https://datatable.readthedocs.io/en/latest/api/dt/join.html) for more details. However, there is an [open issue](https://github.com/h2oai/datatable/issues/1080) to improve the join API.

Meanwhile, if you prefer not to rename the columns you can do the following

```
DT_Y_date = DT_Y[:, {"date":f[0], "is_arrested":f[1]}]
DT_YX_joined = DT_Y_date[:, :, join(DT_X)]
```

Then, `DT_YX_joined` will have the data you are looking for
```
   | date        is_arrested  temp
-- + ----------  -----------  ----
 0 | 2020-08-01            1  NA  
 1 | 2020-09-01            0  35.3
 2 | 2020-09-03            0  43.2
 3 | 2020-09-07            1  NA 
```

You can even do a one-liner like `DT_Y[:, {"date":f[0], "is_arrested":f[1]}][:, :, join(DT_X)]`, but it may not be readable enough. Also note, that not data copies are created here, it is only the column name that changes.

**Comment by oleksiyskononenko** [comment]
Closing this issue as it seems to be answered, feel free to re-open if needed.
