### ISSUE TITLE
How to select or deselect rows using indices in pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2609]
Hi,

Could this questions be looked in and answered on SO?

https://stackoverflow.com/questions/63797911/how-to-select-or-deselect-rows-using-indices-in-pydatatable

**Comment by oleksiyskononenko** [comment]
@myamullaciencia I'm not sure I understand the question. To select rows using indices you just use the indices in the square-brackets selector, like this

```
>>> DT[[0,1,2,4],:]
   | season  title                  rating
-- + ------  ---------------------  ------
 0 |     10  The last one              9.7
 1 |      1  The pilot                 5.6
 2 |      4  The one where estelle     7.8
 3 |      3  The thumb                10  

[4 rows x 3 columns]
```

Is your question more general, like how to remove duplicates from a given column?

**Comment by myamullaciencia** [comment]
@oleksiyskononenko Here are some more inputs.

```
Out[11]: 
   | season  title                  rating
-- + ------  ---------------------  ------
 0 |     10  The last one              9.7
 1 |      1  The pilot                 5.6
 2 |      4  The one where estelle     7.8
 3 |     10  The last one              9.7
 4 |      3  The thumb                10  

[5 rows x 3 columns]

```

**Point 1:**  I can use the index to select the required rows let us say 0,1,2,4 and it can be done as -

```
DT_X[[0,1,2,4],:] 
```

```
Out[12]: 
   | season  title                  rating
-- + ------  ---------------------  ------
 0 |     10  The last one              9.7
 1 |      1  The pilot                 5.6
 2 |      4  The one where estelle     7.8
 3 |      3  The thumb                10  

[4 rows x 3 columns]
```

**Point 2 :**  What if i just want to deselect the observation having index 3: 

OK let us do it in the above way as it has very few observations. here i'm manually entering index numbers avoiding the index to be deselect. it's a herculean task for an analyst.

```
DT_X[[0,1,2,4],:] 

```
Well, I have found an another solution using range function as below.

```
DT_X[[range(3),range(4,DT_X.shape[0])],:] 
```

It works out and returns an expected output.

```
Out[48]: 
   | season  title                  rating
-- + ------  ---------------------  ------
 0 |     10  The last one              9.7
 1 |      1  The pilot                 5.6
 2 |      4  The one where estelle     7.8
 3 |      3  The thumb                10  

[4 rows x 3 columns]

```

**Point 3:**  Let us assume we have 1000 records, the requirement is that  in the middle of dataframe -  we don't want to select the observations from an index 500-550.

For this case also,  do we have to  write the  same logic as below ?

```
x = dt.Frame({'x':range(1000)}) 
```

```
# ex - 1
x[[range(500),range(550,x.shape[0])],:]
```

```
# ex - 2 first 10 observations, 550 to all observations skipping from 11 to 549.
x[[range(10),range(550,x.shape[0])],:]
```

Any other possible ways to do the deselection of required rows in Py-datatable?. 

I hope I made it clear.

**Comment by oleksiyskononenko** [comment]
@myamullaciencia Thanks, now your question is more clear. 

Yes, your approach is a valid one. I would just propose to use `slice()` instead of `range()`, because then you won't need to specify the end of the range as `x.shape[0]`. Just do it like this  

```
DT[[slice(N1), slice(N2, None)], :]
```

**Comment by samukweku** [comment]
@myamullaciencia ``slice`` is a better option, as @oleksiyskononenko suggested.

**Comment by myamullaciencia** [comment]
@oleksiyskononenko  @samukweku got it and thanks guys for your time/help on this.

**Comment by oleksiyskononenko** [comment]
@myamullaciencia you're welcome, closing this issue — feel free to re-open if needed.
