### ISSUE TITLE
[FR]: Add which.min/which.max function to group by calculations

### ISSUE THREAD

**Issue by Peter-Pasta** [h2oai/datatable#2619]
In some cases it is very useful to get the value of a secondary column, where the primary column has it's min or max.

For example the datatable consists of three columns: 1. category, 2. value, 3. date

The new datatable based on the original datatable have should for each category (i.e. the group) the min or max value and the date when the value reached its min or max. 

Thank you.

**Comment by samukweku** [comment]
kindly provide an example data with expected output for this, so I can suggest a solution, and also add it to the [groupby examples documentation](https://datatable.readthedocs.io/en/latest/manual/groupby_examples.html)

**Comment by st-pasha** [comment]
It is my understanding that Peter asks for functionality such as discussed here: https://stackoverflow.com/questions/48519062,
i.e. equivalents of numpy's [argmin()](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html), [argmax()](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) and [where()](https://numpy.org/doc/stable/reference/generated/numpy.where.html) in it's single-argument form (3-argument form is already covered by our `ifelse()`).

**Comment by samukweku** [comment]
@Peter-Pasta , below is an example that could help with `which.min/which.max` equivalents in ``datatable``

Datatable(R) : 
```R
DT = data.table(x=rep(c("b","a","c"),each=3),
                y=c(1,3,6), v=1:9)

   x y v
1: b 1 1
2: b 3 2
3: b 6 3
4: a 1 4
5: a 3 5
6: a 6 6
7: c 1 7
8: c 3 8
9: c 6 9
```
Datatable(python) :
```python
DT = dt.Frame(x = ["b"]*3 + ["a"]*3 + ["c"]*3,
              y = [1, 3, 6] * 3,
              v = range(1, 10))

DT

  | x | y | v
0 | b | 1 | 1
1 | b | 3 | 2
2 | b | 6 | 3
3 | a | 1 | 4
4 | a | 3 | 5
5 | a | 6 | 6
6 | c | 1 | 7
7 | c | 3 | 8
8 | c | 6 | 9
```

Get the row where column `v` is minimum
```R
# datatable
DT[, .SD[which.min(v)], by=x] 
   x y v
1: b 1 1
2: a 1 4
3: c 1 7
```
Equivalent in datatable : 
```python
# in the presence of by, sorting is done per group. 
# we can take advantage of that to get the row for each minimum `v`
DT[0, :, by('x'), dt.sort('v')]  
        x	y	v
0	a	1	4
1	b	1	1
2	c	1	7
```

Get the row where column `v` is maximum
```R
# datatable
DT[, .SD[which.max(v)], by=x] 

   x y v
1: b 6 3
2: a 6 6
3: c 6 9
```
Equivalent in datatable : 
```python
# again we take advantage of the sorting within groups
#  to get our row for each maximum `v`
DT[-1, :, by('x'), dt.sort('v')] 
        x	y	v
0	a	6	6
1	b	6	3
2	c	6	9
```

**Comment by Peter-Pasta** [comment]
@st-pasha and @samukweku, first of all here is my R code:

`df_min <- df[,.(value_min=min(value), value_date=date_column[which.min(value)]), by=id]` 

and here is some sample data:
<img width="325" alt="Bildschirmfoto 2020-09-15 um 20 19 09" src="https://user-images.githubusercontent.com/67552385/93249126-19990a00-f791-11ea-893e-3015fced7402.png">

[just this moment your @samukweku second reply came in]

**Comment by samukweku** [comment]
@Peter-Pasta , at the moment, there are no datetime functions within datatable, so getting min/max is not possible, as far as I can tell.

**Comment by Peter-Pasta** [comment]
@samukweku, the date time column is not important. The dates are stored as simple strings. I want to get the min or max of a numerical column and then get the date (as a simple string) corresponding to that value (i.e. the date in the same row). 

I will shortly check your answer from above out. Is it dependent on version 0.11.0?

**Comment by samukweku** [comment]
@Peter-Pasta, no it is not and should work fine with version 0.10. Let's know how it goes. Cheers.

**Comment by samukweku** [comment]
@Peter-Pasta , working with your example data above : 

```python
DT = dt.Frame({"category": ["A"]*3 + ["B"]*3,
                          "date":["9/6/2016", "10/6/2016", 
                                     "11/6/2016", "9/7/2016", 
                                     "10/7/2016", "11/7/2016"], 
                          'value':[7,8,9,10,1,2]})
DT
    category     date         value
0	A	9/6/2016	7
1	A	10/6/2016	8
2	A	11/6/2016	9
3	B	9/7/2016	10
4	B	10/7/2016	1
5	B	11/7/2016	2
```

Get rows where `value` column is minimum, and rename columns : 
```python
DT[0, {"value_date" : f.date, "value_min":f.value}, by("category"), sort('value')]

  category	value_date   value_min
0	A	9/6/2016	7
1	B	10/7/2016	1

```

**Comment by Peter-Pasta** [comment]
@samukweku, this is the solution! Thank you very much.

**Comment by samukweku** [comment]
No worries. You can close the issue if it is resolved. Cheers.
