### ISSUE TITLE
Improve style of doc page on R/Python comparison

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2625]
The documentation page  https://datatable.readthedocs.io/en/latest/manual/comparison_with_rdatatable.html may need custom table style / formatting, in order to allow multi-line code samples and. Also the table could be converted into 2-column style so that it would fit on the page easier. 

This issue stems from the discussion in #2611. The following "syntax comparison" pages were noted as examples:
  - https://datascience-enthusiast.com/R/pandas_datatable.html
  - https://towardsdatascience.com/python-pandas-vs-scala-how-to-handle-dataframes-part-ii-d3e5efe8287d
  - https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_r.html
  - https://atrebas.github.io/post/2019-03-03-datatable-dplyr/ (:star:)

And this was suggested as a possible style: 
<img width="736" alt="Screen Shot 2020-09-15 at 2 11 39 PM" src="https://user-images.githubusercontent.com/4231472/93265630-bf328600-f75d-11ea-81e2-89c9191b1602.png">

**Comment by samukweku** [comment]
@st-pasha how do I get the style suggested above, so I can use it for documentation on comparison with Pandas. thanks

**Comment by samukweku** [comment]
@st-pasha @oleksiyskononenko We could use [sphinx-panels](https://sphinx-panels.readthedocs.io/en/latest/) to improve the documentation here; make it look like a card layout.  Used in [jupyter-book](https://jupyterbook.org/content/content-blocks.html#panels) as well; might be helpful.
