### ISSUE TITLE
Subset rows, match values against list

### ISSUE THREAD

**Issue by Peter-Pasta** [h2oai/datatable#2640]
Hello, I was wondering how to subset rows based on a list of values. 

Here is how one would do a subset based on one value, in this case a string.

`DT[f.column == 'A', :]`

How would I do a subset if I want to match the columns against a list of strings:

`list_of_strings = ['A', 'B']`

The following does not work:

`DT[f.column in list_of_strings, :]`

 In the documentation I also found how to compound logical expressions:

`DT[(f.y>2) & (f.v>5), :]`

But such an approach would not work well for me, since the list changes dynamically and can be rather long.

**Comment by st-pasha** [comment]
Please see if this SO question would help: https://stackoverflow.com/questions/61494957

**Comment by Peter-Pasta** [comment]
Yes, this helps!

I see you are already working on this, great.

Thank you very much and have a nice weekend
