### ISSUE TITLE
how to replace whole column values?

### ISSUE THREAD

**Issue by yanwu0105** [h2oai/datatable#2649]
i have a datatable like this one :
```
status
▪▪▪▪
0   abc
1   abc
2   ddd
3   aaa
```
and I want to replace to :
convert the small letter to capital letter
```
status
▪▪▪▪
0   ABC
1   ABC
2   DDD
3   AAA
```
how to use `datatable ` package to do this one?

**Comment by st-pasha** [comment]
There is no built-in function for this (yet), so you can convert the column into a plain list, map a python function over the list, and then convert back into a column:
```
DT['status'] = dt.Frame([value.upper() for value in DT['status'].to_list()[0]])
```

**Comment by yanwu0105** [comment]
@st-pasha thank you for your answer

**Comment by myamullaciencia** [comment]
@yanwu0105 please do post it on Stackoverflow as well for better visibility to the datatable community.

**Comment by yanwu0105** [comment]
@myamullaciencia sure~~
Actually i asked the same question in Stackoverflow.
i already post the answer to there.

**Comment by markderry** [comment]
Could we implement the ``` := ``` operator similar to the R implementation?

**Comment by st-pasha** [comment]
@markderry The `:=` operator exists in Python 3.8+ only, and it is not overloadable (in the sense that it will do only what Python wants it to do, not what we'd like it to do). 
However, you can achieve the same functionality either via an [assignment](https://datatable.readthedocs.io/en/latest/api/frame/__setitem__.html), or the [update()](https://datatable.readthedocs.io/en/latest/api/dt/update.html) function.

**Comment by markderry** [comment]
Thanks @st-pasha I didn't realize that.
