### ISSUE TITLE
CASE-WHEN functionality

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2656]
This is a request for function that is equivalent to SQL's [CASE WHEN](https://www.postgresql.org/docs/current/functions-conditional.html). Implementations in other libraries include:
  - R data.table's [`fcase()`](https://rdatatable.gitlab.io/data.table/reference/fcase.html);
  - dplyr's [`case_when()`](https://dplyr.tidyverse.org/reference/case_when.html);
  - numpy's [`select()`](https://numpy.org/doc/stable/reference/generated/numpy.select.html);
  - pandas N/A.

I'm thinking that the most straightforward API is to extend the [ifelse()](https://datatable.readthedocs.io/en/latest/api/dt/ifelse.html) function:
```
ifelse(cond1, value1, cond2, value2, ..., default)
```
For example:
```
ifelse(f.X > 5,  f.X - 5,
       f.X < -5, -f.X - 5,
       0)
```

**Comment by samukweku** [comment]
With you on this @st-pasha , extending `ifelse ` is a lovely idea. Just one function to cover conditions. Building a tutorial regarding conditionals, where I used the update method to replicate `case when`. Not fast and had to do a for loop within python.
