### ISSUE TITLE
Connection to SQLAlchemy

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2674]
Working on a possible documentation for accessing data in SQL databases via sqlalchemy.

Usually, the results are returned as a list of tuples; however, when read into datatable, the tuples are not separated into individual columns. I suspect, it might be a bug, or possibly I have missed something.

```python
from datatable import dt, f, by
from sqlalchemy import create_engine
engine = create_engine("postgresql://username:password@localhost/mydb")
result = engine.execute("select * from iris limit 2")
vox = result.fetchall()
result.close()
dt.Frame(vox)
                              C0
0	(5.1, 3.5, 1.4, 0.2, 'setosa')
1	(4.9, 3.0, 1.4, 0.2, 'setosa')
```

However, if I am working outside of sqlalchemy, datatable handles a list of tuples as expected : 

```python
tuples = [(5.1, 3.5, 1.4, 0.2, 'setosa'), (4.9, 3.0, 1.4, 0.2, 'setosa')]
dt.Frame(tuples)

   C0 C1  C2  C3  C4
0 5.1 3.5 1.4 0.2 setosa
1 4.9 3   1.4 0.2 setosa
```

**Comment by st-pasha** [comment]
I would check `type(vox)` and `type(vox[0])`. Maybe they are not what they seem?
