### ISSUE TITLE
Improve documentation on warnings and exceptions

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#2683]
Currently links to exceptions referenced as `:exc:SomeException` do not work and as of https://github.com/h2oai/datatable/pull/2673 we only have a generic warnings and exceptions page. This should be improved, so that 
- each warning and exception has its own dedicated page (anchors won't work);
- `:exc:SomeException` directive do not produce an error and properly references the corresponding exception;
- add `:warn:` directive to reference warnings.

**Comment by st-pasha** [comment]
Closed in #2741
