### ISSUE TITLE
update() memory leak [bug]

### ISSUE THREAD

**Issue by RaffaeleMorganti** [h2oai/datatable#2701]
Repeatedly call update function cause an abnormal memory usage
Running this example script cause ~450MB memory leaked (datatable version 0.11.0)
``` python
import datatable as dt
DT = dt.Frame( [ 0 ] )
for i in range( 10**7 ) :
   DT[ 0 , dt.update( C0 = 1) ]
```

**Comment by st-pasha** [comment]
Thanks, I can reproduce the problem with your example.

**Comment by st-pasha** [comment]
As a work-around I'd suggest using
```
DT[0, 0] = 1  # or
DT[0, "C0"] = 1
```
This doesn't leak, and it's also about twice faster.

**Comment by st-pasha** [comment]
So far, neither Asan nor Valgrind has detected any leaks, though they are clearly there...

**Comment by RaffaeleMorganti** [comment]
Thanks for this great project and your fast support with the workaround!

I also noticed that following call also cause the bug, so it seems to be not strictly related to the update function
```
DT[0, dt.f.CO] = 0
```
