### ISSUE TITLE
[bug?] can't asign column type in fread function using at 0.11.0

### ISSUE THREAD

**Issue by coolyaolei** [h2oai/datatable#2704]
dttype = [dt.str32, dt.str32, dt.int64, dt.str32, dt.str64, dt.str32]
ddf = dt.fread('/data/zxdata/mon_zx20201022.txt',columns = dttype)

**in 0.10.1:** 
It's correct.
**in 0.11.0:** 
There is a Error!
RuntimeError: Unknown column SType in fread

**Comment by st-pasha** [comment]
Yes, for some reason stype `str64` is not working there. As a workaround, consider using `dt.str32` or simply `str`.
