### ISSUE TITLE
Implement  converting an Arrow Table into a Frame

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2711]
The following should work:
```
dt.Frame(arrow_table)
```

API for interacting with Arrow:  http://arrow.apache.org/docs/format/CDataInterface.html

**Comment by pradkrish** [comment]
This looks like an exciting challenge. I briefly looked at how we convert from pandas df and I got a sense of how it's done.  Unless someone has already started working on this, would it be okay if I have a shot at it (with some guidance)? 

If I get a chance to implement, this is be my approximate time plan. I will spend a day or two looking deeper into numpy->datatable or pandas->datatable conversion to get a better understanding of it it. A day to set up all the infrastructure and helper functions. The function where the conversion happens, something like, `init_from_arrow()` might take 3 to 4 days. So I should be able to get somewhere in a week's time (I am of course assuming that it's as straightforward as other dataframe conversions). Let me know what you think.

Regardless, just curious, when is the release planned?

**Comment by st-pasha** [comment]
Thanks Pradeep for your interest, but i'm working on this issue at this moment, so it probably won't make much sense for us both to try to do the same  thing.

**Comment by pradkrish** [comment]
Sure, it only makes sense you are working on it because it's high priority. I will be happy to review it though when the PR is ready.

**Comment by impredicative** [comment]
Approximately when is this planned to be released?

**Comment by st-pasha** [comment]
This feature is already available in the dev version, so you can install it either directly from source, or from the dev repository https://h2o-release.s3.amazonaws.com/datatable/index.html.

As for the timing of the next official release, we need to finish the date/time functionality first, so it's approximately 1-2 months.
