### ISSUE TITLE
[BUG] Frame.sort() does not work if no columns are provided

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2747]
- Did you find a bug in datatable, or maybe the bug found you?
 `Frame.sort()` should automatically sort on all columns if no column is provided. However, I noticed that this is not the case.

I was actually trying out the frame.sort() method on a single frame, when I noticed this.

- How to reproduce the bug?
```python
df = dt.Frame({"idcon": ["B", "C", "A"], "value": [1, 2, 3]})
```

```
       idcon | value
           B | 1
           C | 2
           A | 3
```

No sorting occurs if no columns are passed 

```python
df.sort()
```

```
       idcon | value
           B | 1
           C | 2
           A | 3
```

It only works when a column is explicitly indicated.
```python
df.sort("idcon")
```

```
       idcon | value
           A | 3
           B | 1
           C | 2
```

- What was the expected behavior?
Sorting should be on all the columns, if it is not stated. 

```python
df.sort()
```

should return
```
       idcon | value
           A | 3
           B | 1
           C | 2
```
where the sorting is based on the first column, followed by the second, then third, ... and the assumption is in ascending order.

- Your environment?
       datatable version - 1.0.0a0+build.1604537228.sam
       python version -  3.9.0 | packaged by conda-forge | (default, Oct 14 2020, 22:59:50) \n[GCC 7.5.0]
       operating system - linux

**Comment by st-pasha** [comment]
This is actually an intentional behavior, see #2220.

**Comment by samukweku** [comment]
@st-pasha It does make sense. I will  incorporate this when creating the examples for sort. Thanks
