### ISSUE TITLE
f[column_list] is not working

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2797]
```
>>> column_list = ['a', 'b']
>>> f[column_list]
TypeError: Column selector should be an integer, string, or slice, not <class 'list'>
```

**Comment by samukweku** [comment]
What should be the expected output? I understand that the f-expression works only with slices and not lists/tuples.

**Comment by st-pasha** [comment]
Ah yes, the expected output should be equivalent to
```
FExpr([f[column] for column in  column_list])
```
I.e. this expression would create a columnset containing columns from the list.

**Comment by samukweku** [comment]
Ok. kindly assign to me. I would love to give it a shot

**Comment by st-pasha** [comment]
I use "consistency" here because we generally expect an equivalency like this:
```
DT[:, 3]  == DT[:, f[3]]
DT[:, "N"] == DT[:, f["N"]]
DT[:, ::2] == DT[:, f[::2]]
DT[:, float] == DT[:, f[float]]
```
i.e. if there is a column selector that works on a frame, then the same selector should probably work inside `f[]` too (with the exception of f-expressions themselves, `f[f.A]` just looks weird. But maybe even that could be allowed?).

**Comment by samukweku** [comment]
Sorry @st-pasha i won’t be able to attempt this anytime soon. Will unassign myself.

**Comment by st-pasha** [comment]
No worries

**Comment by samukweku** [comment]
@st-pasha if you have the time (holiday season is here!) could you pls point me to the code that needs editing for the f expression with lists to work. Is there a way I need to rebuild the local repo to effect any changes? Any more tips is most welcome.

**Comment by st-pasha** [comment]
1. In order to change the source locally and then compile it, check https://datatable.readthedocs.io/en/latest/start/install.html#install-datatable-in-editable-mode
2. The code itself is in the file `namespace.cc`, around line 101

**Comment by samukweku** [comment]
@st-pasha Happy new year!

I installed datatable in editable mode. However, when I make changes (make build) it is not reflected when I run the tests; instead it picks up values from the existing datatable installation (0.11.1 by the way). Any ideas on where I am getting it wrong?


```
(datatable_dev) sam@pop-os:~/datatable$ pip list
Package                       Version
----------------------------- ----------
alabaster                     0.7.12
async-generator               1.10
attrs                         20.3.0
Babel                         2.9.0
bleach                        3.2.1
certifi                       2020.12.5
chardet                       3.0.4
coverage                      5.3.1
datatable                     0.11.1
```

**Comment by st-pasha** [comment]
@samukweku Happy 2021 to you too!

If you run `import datatable as dt; print(dt.__file__)`, it will show where the datatable is currently being imported from. If it's in the python site-package folder, then you could try uninstalling that version explicitly: `pip uninstall datatable`. After that, only the source distribution should remain (there should be a corresponding record in the "easy-install.pth" file).

**Comment by samukweku** [comment]
@st-pasha Thanks. works very well now.

I made the change in `namespace.cc` to allow  lists/tuples; however, it fails as there is a line in fexpr_list.cc that precludes lists from f-selector. Not savvy enough to know what to do here. Would love your feedback.


line 93 - 105 change in namespace.cc

```
//------------------------------------------------------------------------------
// __getitem__()
//------------------------------------------------------------------------------

oobj Namespace::m__getitem__(robj item) {
  if (!(item.is_int() || item.is_string() ||
        item.is_none() || item.is_type() || item.is_stype() || item.is_ltype() || item.is_list_or_tuple()))
  {
    throw TypeError() << "Column selector should be an integer, string, "
                         "or slice, or list, not " << item.typeobj();
  }
  return dt::expr::PyFExpr::make(
              new dt::expr::FExpr_ColumnAsArg(index_, item));
}
```


line 101 in fexpr_list.cc

```
Workframe FExpr_List::evaluate_f(EvalContext&, size_t) const {
  throw TypeError()
      << "A list or a sequence cannot be used inside an f-selector";
}
```

**Comment by st-pasha** [comment]
try the following:
```
Workframe FExpr_List::evaluate_f(EvalContext& ctx, size_t i) const {
  Workframe outputs(ctx);
  for (const auto& arg : args_) {
    outputs.cbind( arg->evaluate_f(ctx, i) );
  }
  return outputs;
}
```
