### ISSUE TITLE
sort should allow NAs last / NAs first option

### ISSUE THREAD

**Issue by jangorecki** [h2oai/datatable#2806]
Using 9bc7d05db2e35a480fb9aea7b570c1005776ae4d
Following query to take to rows by group according order of v3 from biggest to smallest does not handle NAs as expected. NAs are placed at front of sorted vector but expected behavior is to place them at the end.
This FR asks for new argument to `sort` to allow control where NAs will be placed. Similarly as `ORDER BY col NULLS FIRST` and `ORDER BY col NULLS LAST` in SQL.
Another useful feature would be to remove NAs from results.
In base R `order` function there is `na.last` arg, which aside from TRUE/FALSE can take NA, then it removes NAs. This is precisely what I am looking for in this query. If this extra option will not be added then pre-filtering input for non-NA v3 will be an alternative option.
```py
ans = x[:2, {"largest2_v3": f.v3}, by(f.id6), sort(-f.v3)]
```
This is head & tail of `ans`
```
   | id6  largest2_v3
-- + ---  -----------
 0 |  NA           NA
 1 |  NA           NA
 2 |   1           NA

[3 rows x 2 columns]

   |    id6  largest2_v3
-- + ------  -----------
 0 |  99999           NA
 1 | 100000           NA
 2 | 100000           NA

[3 rows x 2 columns]
```
expected value of `largest2_v3` is not an NA, unless of course there are only NAs for particular group.

data:
```sh
## note "na" branch, so re-get if you have previously used datagen script
wget https://raw.githubusercontent.com/h2oai/db-benchmark/na/_data/groupby-datagen.R
Rscript groupby-datagen.R 1e7 1e2 5 0
```

**Comment by samukweku** [comment]
@jangorecki @st-pasha I think this feature has already been added : [link](https://datatable.readthedocs.io/en/latest/releases/v1.0.0.html#fexpr)

**Comment by jangorecki** [comment]
@samukweku indeed, perfect timing, thanks for letting me know.
