### ISSUE TITLE
cut() should support binning based on the provided binning edges

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#2819]
Right now `cut()` can only bin data based on the total number of bins. It should also be possible to provide interval edges manually, giving the user more control over the binning.

**Comment by samukweku** [comment]
Working on creating examples for `cut` and `qcut`; cant seem to find test examples for manual binning with interval edges. @oleksiyskononenko could you please point me in the right direction? if there are other examples you could suggest to show the robustness of the functions, I would love that as well.
