### ISSUE TITLE
xlrd no longer supports xlsx, unhelpful error

### ISSUE THREAD

**Issue by kajuberdut** [h2oai/datatable#2823]
Without pinning an old version of xlrd, fread on an xlsx file will report "AttributeError: module 'xlrd' has no attribute 'xlsx'"

- How to reproduce the bug?
```
import datatable as dt


path = "some xlsx path"
return dt.fread(path)

```

- What was the expected behavior?
  An error specifying that xlrd must be version 1.2.0 to read xlsx files (like the error if xlrd is not installed).

- Environment:
  python 3.8.3, xlrd 2.0.0, datatable 0.11.1

Suggested workaround: install xlrd==1.2.0

**Comment by kajuberdut** [comment]
This is a recent change (December 2020) and perhaps implies that some other library should be used for loading .xlsx files in future versions of datatable.
https://xlrd.readthedocs.io/en/latest/changes.html

xlrd's documentation provides a link to the following for suggestions: http://www.python-excel.org/

**Comment by samukweku** [comment]
I feel openpyxl should be used instead, as it is quite well maintained

**Comment by st-pasha** [comment]
That's not such a clear-cut issue as it seems. There have been a similar switch in pandas from xlrd to openpyxl, and some user [reported 10x slow-down](https://github.com/pandas-dev/pandas/pull/35029#issuecomment-680956402) with  openpyxl engine as compared to xlrd.

I have a very limited set of excel files for testing, the  largest file only 2Mb, but even that goes from 4.7s to 5.9s in pandas when switching to openpyxl. I presume there could be cases of bigger files (perhaps irregularly shaped) where openpyxl gets much much slower -- I'd love to see those examples.
But frankly, even for xlrd the speed is far to be desired  -- 5s for 2Mb, really?

**Comment by st-pasha** [comment]
For future reference, this seems to be a decent outline of XML's format: https://github.com/TeamworkGuy2/xlsx-spec-models/blob/master/open-xml.d.ts
