### ISSUE TITLE
[BUG] `by_names` returns error in dt.rbind()

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#2841]
- Did you find a bug in datatable, or maybe the bug found you?
  the `by_names` parameter in `dt.rbind()` returns a TypeError

- How to reproduce the bug?
```
DT1 = dt.Frame({"Weight": [5, 4, 6], "Height": [170, 172, 180]})
DT2 = dt.Frame({"Weight": [4, 4, 5], "Height": [180, 181, 169]})

In [41]: dt.rbind([DT1, DT2], by_names=False)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-41-d0c9b6246b3c> in <module>
----> 1 dt.rbind([DT1, DT2], by_names=False)

TypeError: rbind() got an unexpected keyword argument by_names

```

- What was the expected behavior?
 Not sure what the purpose of `by_names` is.

- Your environment?
  datatable version : '1.0.0a0+build.1608718222.sam'
  Python version : 3.9.1 | packaged by conda-forge | (default, Jan 10 2021, 02:55:42) \n[GCC 9.3.0]
  Operating system: Ubuntu(Linux)

**Comment by st-pasha** [comment]
Yes, seems like a typo in the documentation: the parameter's name should be `bynames` (without an underscore).  The purpose of the parameter is to control whether the columns are matched by their names or by their indices:
```
>>> import datatable as dt
>>> DT1 = dt.Frame(A=[1, 2, 3], B=[4, 5, 6])
>>> DT2 = dt.Frame(B=[0], A=[-1])
>>> dt.rbind(DT1, DT2, bynames=True)
   |     A      B
   | int32  int32
-- + -----  -----
 0 |     1      4
 1 |     2      5
 2 |     3      6
 3 |    -1      0
[4 rows x 2 columns]
>>> dt.rbind(DT1, DT2, bynames=False)
   |     A      B
   | int32  int32
-- + -----  -----
 0 |     1      4
 1 |     2      5
 2 |     3      6
 3 |     0     -1
[4 rows x 2 columns]
```
See also https://datatable.readthedocs.io/en/latest/api/frame/rbind.html

**Comment by samukweku** [comment]
@st-pasha oh good to know. I will add your example to the documentation
