### ISSUE TITLE
[Bug] Memory leak caused by accessing each columns of rows

### ISSUE THREAD

**Issue by chiapas** [h2oai/datatable#2842]
- Did you find a bug in datatable, or maybe the bug found you?
  I found a potential memory leak in `datatable`.

- Tag @st-pasha , because he seems to work on some memory leak issues before.

- How to reproduce the bug?
  The following snippet, with `DO_PROCESS = True`, suggests that a potential memory leak exists in `datatable`, because the available memory is 2GB less than from the beginning. With `DO_PROCESS = False`, the available memory is just reduced by a few MB. The only difference is just calling `process_dt()` or not, which just access all the columns.

The `train_dt.jay` could be downloaded at this file host website [train_dt.jay](https://gofile.io/d/l48J6I), it is just `3.8 MB`.

```
  DO_PROCESS = True
  PLOT_MEM = True
  
  !pip install --upgrade datatable==0.11.1
  
  
  import datatable as dt
  import psutil
  import random
  
  if PLOT_MEM:
      import plotly.express as px
      !pip install --upgrade kaleido
      import kaleido
  
  jay_path = './train_dt.jay'
  
  train_dt = dt.fread(jay_path)
  
  
  n_rows = train_dt.nrows
  
  
  def generate_random_dt():
      """
      Get a contiguous slice of size `100` from `train_dt`.
      """
          
      start = random.randrange(0, n_rows - 100)
      end = start + 100
  
      _dt = train_dt[start:end, :]
      
      return _dt
  
  
  def process_dt(_dt):
      """
      Dummy process: just get the columns.
      """
      
      user_id = _dt['user_id']
      row_id = _dt['row_id']
      timestamp = _dt['timestamp']
      content_id = _dt['content_id']
      content_type_id = _dt['content_type_id']
      task_container_id = _dt['task_container_id']
      user_answer = _dt['user_answer']
      answered_correctly = _dt['answered_correctly']
      prior_question_elapsed_time = _dt['prior_question_elapsed_time']
      prior_question_had_explanation = _dt['prior_question_had_explanation']
  
      
  iter_indices = []
  mem_history = []
  
  
  available_memeory = psutil.virtual_memory().available / (1024.0)**3
  iter_indices.append(0)
  mem_history.append(available_memeory)
  
  
  for iter_idx in range(50000):
      
      _dt = generate_random_dt()
      user_ids = _dt['user_id'].to_list()[0]
      
      if DO_PROCESS:
          # Loop each row in `_dt` and access all the columns.
          for idx in range(_dt.nrows):
              process_dt(_dt[idx, :])
              
      if (iter_idx + 1) % 100 == 0:
          
          available_memeory = psutil.virtual_memory().available / (1024.0)**3
          iter_indices.append(iter_idx)
          mem_history.append(available_memeory)
          
          if (iter_idx + 1) % 5000 == 0:
              print(available_memeory)
          
        
  if PLOT_MEM:
      
      history = {'mem_history': mem_history}    
  
      fig = px.line(
          history, x=iter_indices, y=[mem_history], 
          title='available memory (GB)', labels={'x': 'iter_idx', 'value': 'memory (GB)'},
          color_discrete_sequence=['deepskyblue']
      )
      fig.show()
```

Here are the plots of the available memory in GB.

[Available Memory with Processing](https://ibb.co/vQDJs3K)

<a href="https://ibb.co/vQDJs3K"><img src="https://i.ibb.co/4YJjs85/available-mem-with-processing.png" alt="available-mem-with-processing" border="0"></a>

[Available Memory without Processing](https://ibb.co/t3tfGbW)

<a href="https://ibb.co/t3tfGbW"><img src="https://i.ibb.co/qxfGSRP/available-mem-without-processing.png" alt="available-mem-without-processing" border="0"></a>

- What was the expected behavior?
  The used memory should be freed.

- Your environment?
  
  datatable version = 0.11.1
  python version=3.7
  operating system=Linux (Notebook on Kaggle)

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).

   `[bug]`

**Comment by st-pasha** [comment]
Thank you for the detailed report. I've made a tiny change to the script so that it would output the memory used by the process, instead of the free memory remaining in the system:
```
proc = psutil.Process()
def get_mem():
    """Return the amount of memory used  by the process, in Mb."""
    return proc.memory_info().rss / (1<<20)
```

This was the output with **datatable 0.11.1, python  3.7** on macOS:
```
272.2265625
528.80078125
785.29296875
1041.90234375
1298.13671875
1492.45703125
1550.0234375
1702.4453125
1811.5859375
1839.15625
```
This is the output with **datatable latest version built from source, python 3.7** (`pip install git+https://github.com/h2oai/datatable`):
```
12.26171875
16.06640625
16.07421875
16.07421875
16.08203125
16.08203125
16.0859375
16.08984375
16.08984375
16.09765625
16.1015625
```
So it appears that there was indeed a leak in version 0.11.1, but it has been fixed since then.

**Comment by chiapas** [comment]
Thank you for looking this issue. I am glad it was already fixed in the latest version.
