### ISSUE TITLE
Installation Failing

### ISSUE THREAD

**Issue by reach4bawer** [h2oai/datatable#2846]
- Did you find a bug in datatable, or maybe the bug found you?
  Trying to install datatable on MacOS Catalina with **python 3.9.1** and **LLVM version 11**. While installing the datatable using `pip3 install datatable` the installation fails in virtual environment. I am attaching the logs files for your reference.
[log.txt](https://github.com/h2oai/datatable/files/5946595/log.txt)

- How to reproduce the bug?
 Please see the log files for additional details.

- What was the expected behavior?
  Installation would complete and datatable would be accessible. 

- Your environment?
```
  Datatable version = 0.11.1, 
  Python version = 3.9.1,
  OS = Mac OS Catalina 10.15.7 (19H15)
```

**Comment by st-pasha** [comment]
Thanks for the report.
While we are working on a possible fix, you can install datatable directly from Git:
```
pip install git+https://github.com/h2oai/datatable
```
