### ISSUE TITLE
fread columns parameter documentation does not match behaviour

### ISSUE THREAD

**Issue by shanemcandrewai** [h2oai/datatable#2847]
- Did you find a bug in datatable, or maybe the bug found you?
  Tell us what it is.

The [documentation for fread](https://datatable.readthedocs.io/en/v0.11.1/api/dt/fread.html) for the `columns` parameter states -

```
columns
...
Limit which columns to read from the input file.
```

but from my testing, it appears to allow the caller to set the columns names (rather than filter columns read)

- How to reproduce the bug?
  **This part is the most important**. Please provide a code snippet which, when
  executed in console, demonstrates the problem. If necessary, attach any data
  files to the issue.

Github issues does not allow the uploading of CSVs so rename the attached file from `tests.csv` to `tests.csv`
[tests.txt](https://github.com/h2oai/datatable/files/5960058/tests.txt)

```
import datatable as dt
dt.fread('tests.csv')

  | col1 | col2
-- | -- | --
  | ▪▪▪▪ | ▪▪▪▪
0 | 2 | 1
1 | 2 | 4
2 | 2 | 5
3 | 3 | 7
4 | 3 | 8
5 | 3 | 0
6 | 3 | NA

dt.fread('tests.csv', columns=['col2'])

ValueError: Input contains 2 columns, whereas columns parameter specifies only 1 column

dt.fread('tests.csv', columns=['col2', 'col1']

  | col2 | col1
-- | -- | --
  | ▪▪▪▪ | ▪▪▪▪
0 | 2 | 1
1 | 2 | 4
2 | 2 | 5
3 | 3 | 7
4 | 3 | 8
5 | 3 | 0
6 | 3 | NA

```

- What was the expected behavior?
  In case it is not obvious, please tell us what result should your code
  produce.

Either make the code match the documentation -

```
dt.fread('tests.csv', columns=['col2'])
  | col2
-- | --
  |  ▪▪▪▪
0 | 1
1 | 4
2 | 5
3 | 7
4 | 8
5 | 0
6 | NA


```

or make the documentation match the behaviour -

```
columns
...
Specify all columns names.

```

- Your environment?
  What is your datatable version, python version, and operating system?

!pip show datatable

Name: datatable
Version: 0.11.1
Pythons 3.8
Windows 10

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).
[bug]

- Thank you for contributing, and sorry for the inconvenience.

**Comment by shanemcandrewai** [comment]
Github issues does allow the uploading of CSVs so rename the attached file from  `tests.csv` to `tests.csv`. 
[tests.txt](https://github.com/h2oai/datatable/files/5960046/tests.txt)

**Comment by st-pasha** [comment]
That's true: the documentation is not complete. The `columns` parameter can perform several jobs:
- filter out some of the columns;
- rename columns;
- change parse type of some columns;
- all of the above.

Check the fread examples to see how it can be used: https://datatable.readthedocs.io/en/latest/manual/fread_examples.html

**Comment by shanemcandrewai** [comment]
@st-pasha I see now that the parameter is documented but not where I expected. Thanks
