### ISSUE TITLE
Error on loading CSV using fread in pydatatable

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#2852]
Could you please answer this on SO ?

https://stackoverflow.com/questions/66168983/error-on-loading-csv-using-fread-in-pydatatable

**Comment by st-pasha** [comment]
Hmm, this one might be hard to answer without the actual dataset. Can it be shared?

At the very least, run the fread command with `verbose=True` and see what it tells you.

**Comment by myamullaciencia** [comment]
[py_fread.txt](https://github.com/h2oai/datatable/files/5975624/py_fread.txt)

Here attached the logs for reference

**Comment by ankhnesmerira** [comment]
any resolution to this problem? i'm getting the same error loading a csv file about 30M rows and 50 columns.

**Comment by st-pasha** [comment]
Unfortunately, without a clear reproducible example, there is little that can be done here.

**Comment by st-pasha** [comment]
i'm going to close, since there's nothing that can be done here.
