### ISSUE TITLE
cannot import name 'as_type' from 'datatable'

### ISSUE THREAD

**Issue by Peter-Pasta** [h2oai/datatable#2875]
Hi there. I need to convert the type of a column. To find out how I looked into the docs and found what I was looking for here https://datatable.readthedocs.io/en/latest/api/dt/as_type.html. However it is not possible to import 'as_type'.

Problem : cannot import name 'as_type' from 'datatable'

In:
`from datatable import dt, as_type
`
Out:
`ImportError: cannot import name 'as_type' from 'datatable' (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/datatable/__init__.py)
`

Environment:
datatable 0.11.1, Python 3.8.8, MacOS 11.2.1

Thank you for taking the time 👍

**Comment by samukweku** [comment]
`as_type` is in the Dev version. You can however use the type itself. So if you are changing from str to int : `DT[:, update(column = dt.int32(column)]`

**Comment by Peter-Pasta** [comment]
Thank you. Now that you mention it I noticed the little banner saying 'Added in Version 1.0'
