### ISSUE TITLE
Variable name can't be "def"

### ISSUE THREAD

**Issue by XiaomoWu** [h2oai/datatable#2884]
**Bug behavior**
- Can't use "def" as variable name together with "f".

**Reproduce**
```python
import datatable as dt
from datatable import f

x = dt.Frame({'def': [1, 2, 3]})
print(x) # it's okay

x[:, [f.def]] # SyntaxError: invalid syntax
```

**Notes**
- It seems that Python think of "def" as a keyword and hence gives the error. But I don't know why it will occur with `f`.

**Environment**
- Ubuntu 20.10
- pydt=1.0.0a1939

**Comment by samukweku** [comment]
@XiaomoWu I think since it within python's space, any keyword (which `def` is) wont pass; if you pass `f[def]`, it works. as long as it is a python keyword, it cannot (my understanding so far) be accessed as an attribute

**Comment by XiaomoWu** [comment]
@samukweku You're right, any python keyword won't pass. Maybe we can add this as a note in the document?

**Comment by XiaomoWu** [comment]
@samukweku Thanks for the great work! I'll close the issue now.
