### ISSUE TITLE
Inconsistent stripping of whitespace > Offset columns

### ISSUE THREAD

**Issue by tbraun84** [h2oai/datatable#2943]
I apologize if this is user error, but I think this may be a problem with how whitespace is stripped from the first line versus underlying lines

- How to reproduce the bug?
  I have a data file which has some junk at the top and then the lines with data each start with a  tab (\t). That is, the whole table is moved over by a single tab.
  Sample file is attached, using generic mock data. I set the `skip_to_line` argument well below the header and `header=False`
  Commands
`S = dt.fread(file=src_data, sep='\t', skip_to_line=6, header=False, skip_blank_lines=True, strip_whitespace=True, fill=True, verbose=True)`
(fill=False results in an error)
 
- What was the expected behavior?
  Data values aligned under column headings
- What happens?
 First row is aligned, with following rows are offset to the right by a column.
`S.head()`
```
  | C0          C1          C2          C3             C4      C5 
-- + ----------  ----------  ----------  -------------  ------  ---
 0 | 01/25/2021  2.0         Mary Brown  180.00         USD     NA
 1 |             01/25/2021  1.0         Robert Taylor  150.00  USD
 2 |             01/25/2021  1.0         James Smith    35.00   USD
```

- Your environment?
  Datatable version 0.11.1,  Python 3.8.6 [MSC v.1927 64 bit (AMD64)], and OS WIndows 10 version 1909

**Comment by tbraun84** [comment]
I forgot to attach my sample data file.
[test_data.txt](https://github.com/h2oai/datatable/files/6360914/test_data.txt)

**Comment by st-pasha** [comment]
You can read the example file using
```
>>> DT = dt.fread("/Users/pasha/Downloads/test_data.txt", skip_blank_lines=True, skip_to_line=4)
>>> DT.names  = DT.names[-1:] + DT.names[:-1]
>>> DT
   |   C0  Doc. Date   Quantity  Personnel Name  Value TCur  TCurr
   | void  str32        float64  str32              float64  str32
-- + ----  ----------  --------  --------------  ----------  -----
 0 |   NA  01/25/2021         3  James Smith            100  USD  
 1 |   NA  01/25/2021         2  Mary Brown             180  USD  
 2 |   NA  01/25/2021         1  Robert Taylor          150  USD  
 3 |   NA  01/25/2021         1  James Smith             35  USD  
[4 rows x 6 columns]
>>> del DT[0]
```
(the names reassignment here corrects for their shift).

Still, you're right:  there is some excessive white-space stripping going on here. Possibly because the preamble-stripping happens at a stage when there is no knowledge of the separator yet.
