### ISSUE TITLE
Include error_bad_lines = False like we have in Pandas.read_csv()

### ISSUE THREAD

**Issue by siddarthsreeni** [h2oai/datatable#2964]
- Describe what feature you would like to see implemented.

I'm currently trying to read a very large csv file ~ 3~5GB. In rare cases, in the file there is inconsistencies between the one or two rows with the majority of the rows. I was using Pandas earlier but saw datatable was able to exactly the same thing except there was no option to "error_bad_lines" = False option. I always get confronted with IOError and the whole thing just raises an Exception. 

- If possible, give an example of how it may look in the code and what result
  will be produced.
There are 3 columns, and many rows. But as you can see one of the rows have more columns. 
`A | B | C`
`1 | 2 | 3`
`3 | 3 | 4`
`... ` 
`6| 8 | 9 | 4` #error here
`3 | 9 | 1`

In this case, `dt.fread(sep='|')` throws an IOerror. Instead I wish to pass error_bad_lines = False to not through error on a bad line and just ignore that line and return me the rests of the rows in a `Frame`

**Comment by samukweku** [comment]
@siddarthsreeni , what if you use the `fill=True` parameter? Does it help? You could have a look at the [example](https://datatable.readthedocs.io/en/latest/manual/fread_examples.html#dealing-with-null-values-and-blank-rows) - see if it matches your use case

**Comment by siddarthsreeni** [comment]
> @siddarthsreeni , what if you use the `fill=True` parameter? Does it help? You could have a look at the [example](https://datatable.readthedocs.io/en/latest/manual/fread_examples.html#dealing-with-null-values-and-blank-rows) - see if it matches your use case

Thanks for the suggestion, I looked at the documentation, this isn’t a missing value but rather a wrong entry ( mostly due to human interference in this data I’m dealing with). The fill=True deals with null values. In my scenario the row is completely wrong & has to be skipped

**Comment by siddarthsreeni** [comment]
Same as #2940
