### ISSUE TITLE
FR: add functions rowargmax() / rowargmin()

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#2998]
These functions are companions to `rowmax()` and `rowmin()` and intended to return the index (within the row) where the max/min value has occurred.

**Comment by grigory93** [comment]
would `rowargmax()` and `rowargmin()` return absolute (index of the column in the datatable) or relative (index of the column in the column list argument) value? Would it make sense to control it using additional parameter? Would it make sense to add an option to return a column name instead of an index?

**Comment by pradkrish** [comment]
I have made a first implementation of this feature, wherein it returns the absolute index of the column in the datatable. Can you give an example of relative indexing? I like the idea of adding an option to return column names. @st-pasha  What do you think ?

**Comment by st-pasha** [comment]
So, as far as example goes, suppose you have a frame
```
DT = dt.Frame(A=[1], B=[2], C=[3], D=[4], E=[5])
```
and we are looking for the argmax of the last 3 columns: `rowargmax(f["C":"E"])`. Then do we return `2` (the index of the largest element within the columnset `f[C:E]`), or `4` (the index of that column within the original frame), or `"E"` (the name of that column).

**Comment by st-pasha** [comment]
IMHO having the return value to be an index is more convenient:
   -  first, because it allows performing simple arithmetic with the result. For example, what is the difference between the max value and the value in the preceding column; or whether the max value comes before or after the min value; etc.
   - second, because converting column indices into names is easier than converting column names into indices.

**Comment by pradkrish** [comment]
I spoke too soon. The implementation I am working on does return relative indexing, similar to the behaviour of `rowmax` and `rowmin`

**Comment by grigory93** [comment]
please consider the following features for these functions:

- optional parameter to specify to return relative or absolute column index (default: relative)
- optional parameter to specify to return column name or index (default: index)

We can always add these later, but keeping them in mind during implementation makes sense.

On a separate note, how ties are resolved - first or last or random? I hope we will be deterministic the least.

**Comment by grigory93** [comment]
For example, to convert dummy variables back to categorical feature (folding a set logical columns into single categorical column) would be done using `argmax` and benefit from returning a column name to use as a category value.
