### ISSUE TITLE
Error on installing new datatable version 1.0.0 in google colab machine

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#3045]
Could this be answered on SO:

https://stackoverflow.com/questions/68218406/error-on-installing-new-datatable-version-1-0-0-in-google-colab-machine

**Comment by myamullaciencia** [comment]
FYI: the version 0.11 is being successfully installed. the issue is with version 1.0

**Comment by myamullaciencia** [comment]
FYI:on kaggle instance the new version 1.0.0 is getting installed successfully.

**Comment by myamullaciencia** [comment]
yup, got it. after upgrading pip the new version 1.0 has got installed and closing this case.

**Comment by st-pasha** [comment]
I have also created an issue on GoogleColab's page to upgrade their version of pip. Running with `pip 19.3.1` is really counterproductive.

**Comment by myamullaciencia** [comment]
Oh thanks for that, @st-pasha I'm practicing datatable 1.0 in google colab and if any issues seen with it let yours know.
