### ISSUE TITLE
fread fails when reading mostly empty file

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#3055]
```
>>> text = "Nothing" + "\n" * 1000000
>>> dt.fread(text)
  3% |█▉                                                | Reading data [error]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: Assertion 'c.get_start() >= input_start && c.get_end() <= input_end' failed in src/core/read/parallel_reader.cc, line 139
```

_Originally posted by:_ @pseudotensor

**Comment by pradkrish** [comment]
A related issue is even if the assertion does not fail for a smaller input, the resulting frame is one row less than expected.

```python
text = "Nothing" + "\n" * 1000
dt.fread(text)

    | Nothing
    |    void
--- + -------
  0 |      NA
  1 |      NA
  2 |      NA
  3 |      NA
  4 |      NA
  5 |      NA
  6 |      NA
  7 |      NA
  8 |      NA
  9 |      NA
 10 |      NA
 11 |      NA
 12 |      NA
 13 |      NA
 14 |      NA
  … |       …
994 |      NA
995 |      NA
996 |      NA
997 |      NA
998 |      NA
[999 rows x 1 column]

```
It should have been 1000 rows.

**Comment by st-pasha** [comment]
Not really. Take a simpler example: `"Nothing\n123\n"`. This is a file with 1 header line and 1 data line, so it produces a [1x1] frame. If the data row was empty, we'd have `"Nothing\n\n"`, which would still be a [1x1] frame. Thus, a file that contains `k` newlines produces a frame with `k-1` rows, because one of those newlines is "taken" by the header.

**Comment by pradkrish** [comment]
Thanks for the clarificaton
