### ISSUE TITLE
to_jay() stucks at most times in 1.0.0, while it's fine in 0.11.1

### ISSUE THREAD

**Issue by Binger-cn** [h2oai/datatable#3060]
- Did you find a bug in datatable, or maybe the bug found you?
  I'm testing JAY file format these days, and when I upgrade to 1.0.0 a few days ago, I found dt.to_jay() always stucks.

   

- How to reproduce the bug?
  And I try a few more tests, it still stucks even with very small table read from some CSV files (eg. 5K in size). 
  It's ok only with manually created Frame with strings,such as : dt.Frame(''' A B C\n1 2 3\n4 5 6''').
- What was the expected behavior?
  I remember sucessfully saving a 17G-size file last week, so I uninstall 1.0.0 and reinstall 0.11.1, everything gets OK.

- Your environment?
  1.0.0, windows10 pro, python 3.8.10

- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).
  Bug
[crider-SEM.zip](https://github.com/h2oai/datatable/files/6812094/crider-SEM.zip)

- Thank you for contributing, and sorry for the inconvenience.

**Comment by st-pasha** [comment]
Thanks for the report!
It appears the issue is caused by the presence of empty (`void`) columns in the file.
While we're working on fixing the problem, you can alleviate by either deleting the void columns
```
del DT[:, dt.Type.void]
```
or converting them into boolean:
```
DT[:, dt.Type.void] = bool
```

**Comment by Binger-cn** [comment]
OK， Thanks for the quick response！发自我的华为手机-------- 原始邮件 --------发件人： Pasha Stetsenko ***@***.***>日期： 2021年7月14日周三 15:02收件人： h2oai/datatable ***@***.***>抄送： Binger-cn ***@***.***>, Author ***@***.***>主    题： Re: [h2oai/datatable] to_jay() stucks at most times in 1.0.0, while it's fine in 0.11.1 (#3060)
Thanks for the report!
It appears the issue is caused by the presence of empty (void) columns in the file.
While we're working on fixing the problem, you can alleviate by either deleting the void columns
del DT[:, dt.Type.void]

or converting them into boolean:
DT[:, dt.Type.void] = bool
