### ISSUE TITLE
Using qcut leads to segmentation fault / illegal hardware instruction error

### ISSUE THREAD

**Issue by vopani** [h2oai/datatable#3061]
- Did you find a bug in datatable, or maybe the bug found you?
Using `qcut` leads to `segmentation fault` and `illegal hardware instruction` errors. Either one appears depending on the order in which the lines of code are run.

- How to reproduce the bug?
Requirements:
```bash
python3 -m pip install datatable==1.0.0
python3 -m pip install scikit-learn==0.24.1
```

```python
import datatable as dt
from sklearn.datasets import load_wine

DT = dt.Frame(load_wine(as_frame=True)['frame'])
DT

DT['malic_acid_decile'] = dt.qcut(dt.f.malic_acid)
DT

DT[dt.f.malic_acid_decile == 1, :]
DT
```

```
>>> DT[dt.f.malic_acid_decile == 1, :]
[1]    23177 illegal hardware instruction  python
```

- What was the expected behaviour?
There should not be any error, it is a dataset of less than 200 rows.

- Your environment?
Using v1.0.0 in Python 3.8.3 on Mac OS.

**Comment by oleksiyskononenko** [comment]
Thanks, @vopani. I could reproduce it even in a more simple case:

```
import datatable as dt
DT = dt.Frame([0])
DT["q"] = dt.qcut(dt.f.C0)
# DT.materialize()           # no segfault if uncommented
DT1 = DT[dt.f.q == 1, :]  # segfault
```

While we're fixing this bug a workaround could be just materializing the frame after `qcut()`.

**Comment by vopani** [comment]
Thanks!
