### ISSUE TITLE
select columns easily when reading 

### ISSUE THREAD

**Issue by Binger-cn** [h2oai/datatable#3067]
I just defined a function to make it easier to select certain columns from a csv, no matter how many original columns it has.

def colFilter(**cols):
    return lambda x:list(( { i: None for i in range(len(x))} | dict(zip(cols.values(), cols.keys()))).values(), fill=True, ...)

So, I can choose columns like this :

dt.fread('CSV_FILE_PATH', columns=colFilter(timestamp=16, ip=5, url=6), fill=True,)

I hope datatable could provide a more convinient way to do this.   :)

**Comment by st-pasha** [comment]
I'm not exactly sure what you are trying to achieve here. Can you elaborate, please?

**Comment by st-pasha** [comment]
Not sure what is being asked here, so closing.

The parameter `columns=` in fread already allows selecting specific columns only by providing a list of True/False indicators, or a set of column names to keep, or an arbitrary column selection mechanism via a callback function.
