### ISSUE TITLE
dt.rbind(dt.iread(zip) ) froze

### ISSUE THREAD

**Issue by Binger-cn** [h2oai/datatable#3092]
Just a line of code, results in freezing in vscode+jupyter plugin:
    DT.rbind(DT.iread('202107060245.zip', fill=True))
[202107060245.zip](https://github.com/h2oai/datatable/files/6852453/202107060245.zip)

If I run it in command line, it exits abnormally:
![企业微信截图_20210721110015](https://user-images.githubusercontent.com/87395223/126423950-d2c8a8e1-5922-4698-ab1b-e1dec754e4a7.jpg)

**Comment by st-pasha** [comment]
Thanks for the report, will check tomorrow what the problem is

**Comment by oleksiyskononenko** [comment]
`dt.fread('202107060245.zip', fill=True)` segfaults on this file right away.
