### ISSUE TITLE
AttributeError: module 'datatable' has no attribute 'date32'

### ISSUE THREAD

**Issue by Peter-Pasta** [h2oai/datatable#3095]
Hi guys, I am not sure if I stumbled across a bug ... or if this is a user error. 

Basically I want to use the new as_type() function and date32 type that were added in datatable 1.0.0.

my code:

`df[:, [dt.as_type(f.Date, dt.date32), dt.as_type(f.Amount, dt.float64)]]`

error:

`AttributeError: module 'datatable' has no attribute 'date32'`

**Comment by st-pasha** [comment]
The new types were not added to the main `dt.` namespace, you can access them as `dt.Type.date32`

**Comment by Peter-Pasta** [comment]
Solved. Will this be simplified in the future?

**Comment by st-pasha** [comment]
Yes, I added it in the list #3097
