### ISSUE TITLE
Add query methods `.is_integer()`, `.is_numeric()`, etc to Type class

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#3101]
These methods already exist in the internal `Type` class, now we only need them to be visible outside.

**Comment by samukweku** [comment]
@st-pasha How is this supposed to be used. With the stypes/ltype, you can get the exact type(int, float, ...) which comes in handy in some iterations. However, with the new Types/type, I cant get the exact type without accessing the name, which returns as  a string. I was of the thought that with this properties, I could just access the dtype, which can be handy in selection and other operations. 

An example : 
   ```DT[:, [int, float]]```

selects all numeric , so my thought process with the new tool would be : 
```DT[:, f[:].is_numeric]```

or something along those lines. I probably mucking it up , so some clarification would be appreciated
