### ISSUE TITLE
FR: multiply values group by

### ISSUE THREAD

**Issue by Peter-Pasta** [h2oai/datatable#3140]
This code performs addition of all values in a group:

`DT[:, dt.sum(f.v), by('x')]`

Similar to above I would like to perform multiplication. Proposal:

`DT[:, dt.product(f.v), by('x')]`

Thank you.

**Comment by st-pasha** [comment]
Interesting... You could always do `dt.math.exp(dt.sum(dt.log(f.v)))` though.

**Comment by Peter-Pasta** [comment]
Very interesting solution.

**Comment by samukweku** [comment]
love the solution by @st-pasha. If i can take a stab at it, it works based on the laws of logarithms. one of the laws state that the sum of the logs of A and B is equal to the log of the product of A and B. 

say you have `A=3` and `B=5` (I'll use functions from vanilla python to explain)

```python
from math import log, exp
In [246]: log(A) + log(B)
Out[246]: 2.70805020110221
````

The exponential completes the rest:
```python
In [247]: exp(log(A) + log(B))
Out[247]: 15.0
```
You can verify that the sum of the logs is equal to the log of the product
```python
In [248]: log(15)
Out[248]: 2.70805020110221
```

I like it as it sort of reduces the need to have extra functions - you can create your own function and just reduce the maintenance burden. Others might have different opinon - convenience vs maintenance


Hopefully the explanation makes sense. @st-pasha feel free to correct wherever.

**Comment by st-pasha** [comment]
Wow, this is totally my GOOMHR moment (https://xkcd.com/2501/). 😁
I didn't even realize the conversion between the product and the sum may not be entirely obvious.

**Comment by Peter-Pasta** [comment]
@samukweku, I did a similar thing like you to follow this through. However I was searching more for an in depth explanation/proof why this works.

**Comment by st-pasha** [comment]
@oleksiyskononenko If you look at the reasons we decided not to switch to C++17 (#2338) -- it was because of market share of Macs supporting C++17 was only 79%. According to the link posted on that PR, today that market share is already 96%. So it might be a good idea to revisit the issue.

**Comment by st-pasha** [comment]
Could be. You'd need to check the docker container that we use for building PPC images, and see what C++ version is in that container.
