### ISSUE TITLE
How to display pydatatable frame output in streamlit web app?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#3153]
Could this be reviewed? and send on your comments in SO

https://stackoverflow.com/questions/68961667/how-to-display-pydatatable-frame-output-in-streamlit-web-app

**Comment by oleksiyskononenko** [comment]
I have answered this question on SO, however, there is nothing we can do on the datatable side to make it happen. It is more a request to streamlit developers to support datatable frames.
