### ISSUE TITLE
Rename column similar to data.table::setnames(data, old, new)

### ISSUE THREAD

**Issue by AdrianAntico** [h2oai/datatable#3159]
- Describe what feature you would like to see implemented.
I've been flipping through the documents and I can't seem to find a way to rename a column. Is this possible and I'm simply not finding it?

- If possible, give an example of how it may look in the code and what result
  will be produced.
Frame.setnames(old, new)

**Comment by oleksiyskononenko** [comment]
@AdrianAntico, please take a look at this page: https://datatable.readthedocs.io/en/latest/api/frame/names.html Could be found by running a [search](https://datatable.readthedocs.io/en/latest/search.html?q=rename) for "rename" on readthedocs.io.

**Comment by AdrianAntico** [comment]
Thanks. Didn't think to look in the pandas comparison to find an example

**Comment by oleksiyskononenko** [comment]
@AdrianAntico Example is not in the pandas comparison, it is just the pandas comparison that pops up first for the  "rename" search. The [.names](https://datatable.readthedocs.io/en/latest/api/frame/names.html) property is a little bit down the page.
