### ISSUE TITLE
`options.display.max_column_width` has no effect in Jupyter notebooks

### ISSUE THREAD

**Issue by Binger-cn** [h2oai/datatable#3160]
import datatable as dt
dt.options.display.max_column_width=99
dt.Frame('col1 \n '+'1234567890-'*11)

this does take effect in  ipython, while not in jupyter, either browser or vscode-jupyter

![image](https://user-images.githubusercontent.com/87395223/132612490-3131962c-2660-42fd-ac4e-795003e41347.png)

**Comment by oleksiyskononenko** [comment]
When I count number of characters printed out in jupyter, it is exactly 99 (7*10+7*4+1) as you request with `max_column_width`. So what is the problem here?

**Comment by Binger-cn** [comment]
> When I count number of characters printed out in jupyter, it is exactly 99 (= 7 * 10 + 7 * 4 + 1) as you request with `max_column_width`. So what is the problem here?

That's in ipython.  See my picture, upper is Jupyter, lower is ipython.
It's OK in ipython, but fails in Jupyter, in which it shows only the default 50 chars.

**Comment by oleksiyskononenko** [comment]
Ah, I see. You just mentioned ipython / jupyter, but then posted screenshots as jupyter / ipython. Yes, looks like a bug then.

**Comment by Binger-cn** [comment]
Haha, I'm sorry for that misleading...




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月9日(星期四) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [h2oai/datatable] options.display.max_column_width  seems to have no effect in jupyter, release 1.0.0 (#3160)





 
Ah, I see. You just mentioned ipython / jupyter, but then posted screenshots as jupyter / ipython. Yes, looks like a bug then.
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Binger-cn** [comment]
BTW, I hope this fixed together with another enhancement:
max_columns&nbsp; &nbsp;(#3051)


Thanks in advance!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月9日(星期四) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [h2oai/datatable] options.display.max_column_width  seems to have no effect in jupyter, release 1.0.0 (#3160)





 
Ah, I see. You just mentioned ipython / jupyter, but then posted screenshots as jupyter / ipython. Yes, looks like a bug then.
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
