### ISSUE TITLE
Replace doesn't support numpy scalars

### ISSUE THREAD

**Issue by maximocrv** [h2oai/datatable#3164]
Hi, I am trying to replace the entries in two columns of my data frame with values contained in a very large dictionary. No errors come up but nothing actually happens with the data frame. I have tested it with a toy dictionary containing only two key-value pairs, and in this case it works well. Is it possible that the error arises due to the fact that the dictionary has ~20M entries? Here is some mock up code that you can reproduce the issue with:

```
import numpy as np
import datatable as dt

a = np.random.randint(0, 100000000, (40000000, 2))
df = dt.Frame(a)
unique_values = np.unique(a)
mapping = dict(zip(unique_values, np.arange(len(unique_values))))

df.replace(mapping)
```

As a sidenote, in my code I am actually only replacing two columns, but this worked fine with the toy example I had. Thanks in advance for your time.

**Comment by oleksiyskononenko** [comment]
The issue here is not the dict size. It is actually the way how datatable deals with numpy scalars. For instance:

```python
from datatable import dt
import numpy as np

DT = dt.Frame([1])

DT.replace({np.int64(1) : np.int64(2)})
print(DT)

DT.replace({np.int(1) : np.int(2)})
print(DT)
```

produces 

```
   |   C0
   | int8
-- + ----
 0 |    1
[1 row x 1 column]

   |   C0
   | int8
-- + ----
 0 |    2
[1 row x 1 column]
```

So if the dict contains `np.int*()` values it simply has no effect when replacing datatable values. At the same time `np.int()` works just fine.

**Comment by maximocrv** [comment]
Great, thank you for the clarification!
