### ISSUE TITLE
Row selection when type is obj64

### ISSUE THREAD

**Issue by XiaomoWu** [h2oai/datatable#3166]
Given the DT:

```python
DT = dt.Frame(A = [1, 2], B = [['a'], ['b', 'c']], type=dt.Type.obj64)
```

I'm wondering how can I achieve this:
```python
DT[f.B == ['b', 'c'], :]
```

Currently it's not possible because Operator == is not implemented for obj64. But is there any workaround?

Thank you!

**Comment by oleksiyskononenko** [comment]
I don't think this is currently possible as support for `obj64` columns is very limited.

However, in your example it makes more sense to use the new array type `dt.Type.arr32(dt.Type.str32)` for the column `B`. Even though there is still no way to do a row selection based on array, support will be added at some point.

**Comment by XiaomoWu** [comment]
Thank you @oleksiyskononenko. I'm excited about the Array type! Issue closed.
