### ISSUE TITLE
[BUG] Sort with `reverse`

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#3168]
- Did you find a bug in datatable, or maybe the bug found you?
 It seems sorting with `reverse` doesnt output the right results for multiplecolumns. This is evident where there are duplicate values in the first sorting column.

- How to reproduce the bug?
 ```python
   from datatable import dt
     DT = dt.Frame(
     {
     'OrderID': ['o1','o2','o3','o4','o5'],
    'CustomerID': ['c1','c1','c2','c2','c3'],
     'CustomerRating': [5,1,3, np.NaN,np.NaN]
   
   }
     )     


DT
   | OrderID  CustomerID  CustomerRating
   | str32    str32              float64
-- + -------  ----------  --------------
 0 | o1       c1                       5
 1 | o2       c1                       1
 2 | o3       c2                       3
 3 | o4       c2                      NA
 4 | o5       c3                      NA
[5 rows x 3 columns]


# wrong output : 
DT[:, :, dt.sort('CustomerID', 'OrderID', reverse=[False, True])]
   | OrderID  CustomerID  CustomerRating
   | str32    str32              float64
-- + -------  ----------  --------------
 0 | o1       c1                       5
 1 | o2       c1                       1
 2 | o3       c2                       3
 3 | o4       c2                      NA
 4 | o5       c3                      NA
[5 rows x 3 columns]

# correct output
DT[:, :, dt.sort(f.CustomerID, -f.OrderID)]
   | OrderID  CustomerID  CustomerRating
   | str32    str32              float64
-- + -------  ----------  --------------
 0 | o2       c1                       1
 1 | o1       c1                       5
 2 | o4       c2                      NA
 3 | o3       c2                       3
 4 | o5       c3                      NA
[5 rows x 3 columns]
 ```

- What was the expected behavior?
```python
DT[:, :, dt.sort(f.CustomerID, -f.OrderID)]
   | OrderID  CustomerID  CustomerRating
   | str32    str32              float64
-- + -------  ----------  --------------
 0 | o2       c1                       1
 1 | o1       c1                       5
 2 | o4       c2                      NA
 3 | o3       c2                       3
 4 | o5       c3                      NA
[5 rows x 3 columns]
```

- Your environment?
-  datatable version : datatable-1.1.0a0+build.1631413284
-  python version: 3.9
- OS : linux

**Comment by oleksiyskononenko** [comment]
I guess the issue here is that even though we allow lists/tuples to be provided for `reverse` parameter, [at the end](https://github.com/h2oai/datatable/blob/main/src/core/expr/eval_context.cc#L72) we only use the first element from that list/tuple.

**Comment by pradkrish** [comment]
Shall we assume a default value of `false` for those columns that lack a reverse flag? In the following example 
```python
DT[:, :, dt.sort('CustomerID', 'OrderID', reverse=[True])]
```
reverse flag for OrderID will be `false`.

**Comment by oleksiyskononenko** [comment]
This could be done, of course, though I'm not sure how intuitive it would be. Because then the following two statements
```
DT[:, :, dt.sort('CustomerID', 'OrderID', reverse=True)]
DT[:, :, dt.sort('CustomerID', 'OrderID', reverse=[True])]
```
will sort `OrderID` in different directions, while for a user it would be just the `[]` that was added.

**Comment by pradkrish** [comment]
Otherwise we can raise an error if the user fails to give as many reverse flags as the number of columns to be sorted. In this way, the behaviour of reverse flag list is different from when it takes a singleton.

It's matter of design. Being one of the lead developer of this project, I let you choose @oleksiyskononenko :)

**Comment by pradkrish** [comment]
> > Otherwise we can raise an error if the user fails to give as many reverse flags as the number of columns to be sorted
> 
> Yeah, this check is definitely missing right now.

Having said that, this logic could lead to a tricky situation. If you take the following simple example 

```python
DT[:, :, dt.sort('CustomerID', 'OrderID')]
```
The number of columns to be sorted is 2 and the reverse flag list length is zero and the programme will terminate with the assertion error. With the current implementation the following code should work just fine with the reverse flag set to false for all columns. The first solution where we assume a default value of false for those columns that lack a reverse flag seems to be a better choice given this example.
