### ISSUE TITLE
shift function needs to consider variable related to time

### ISSUE THREAD

**Issue by dazhwu** [h2oai/datatable#3200]
- Describe what feature you would like to see implemented.

Consider the following code:

library(data.table)

DT = data.table(year=c(2010, 2010, 2009, 2011,2011,2011), id=c(1,2,3,1,2,3), value=c(2,5,6,8,2,6))
print(DT)

   year id value
1: 2010  1     2
2: 2010  2     5
3: 2009  3     6
4: 2011  1     8
5: 2011  2     2
6: 2011  3     6

DT[, lag1 := shift(value, 1), by=.(id)]
print(DT)

   year id value lag1
1: 2010  1     2   NA
2: 2010  2     5   NA
3: 2009  3     6   NA
4: 2011  1     8    2
5: 2011  2     2    5
6: 2011  3     6    6

regarding the last record, its lag1 is supposed to be NA, because there is no data for year 2010 for that particular id.

The following code will produce the result correctly:

temp=copy(DT)
temp[, `:=`(year=year+1, lag1=value)]
temp=temp[, .(id, year, lag1)]

DT=merge(DT, temp, by=c("id", "year"), all.x=TRUE)
setorder(DT, id, year)
print(DT)

   id year value lag1
1:  1 2010     2   NA
2:  1 2011     8    2
3:  2 2010     5   NA
4:  2 2011     2    5
5:  3 2009     6   NA
6:  3 2011     6   NA

But it is not very handy.

- If possible, give an example of how it may look in the code and what result
  will be produced.

Please see code examples above.

- Click "Preview" to check that there are no formatting problems, that the
  request is stated clearly, and that it is not overbroad in scope.

- Thanks for contributing. We appreciate your input!

**Comment by oleksiyskononenko** [comment]
@dazhwu Have you intended to submit your issue into the [R data.table repo](https://github.com/Rdatatable/data.table)?

**Comment by dazhwu** [comment]
Sorry, I didn't realize this. Please close this request.
