### ISSUE TITLE
Add support for python `3.10`

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#3210]
According to https://github.com/h2oai/datatable/discussions/3207 we have some issues building datatable for the new python version.

**Comment by lbx15970** [comment]
This is still not working for my python3.10 on raspberry pi now.
![image](https://user-images.githubusercontent.com/54590116/160014970-6db18581-7e43-4a59-a37a-2d3565881cf0.png)

**Comment by oleksiyskononenko** [comment]
How is PyQT6 that you're trying to install is related to datatable?
