### ISSUE TITLE
 [bug]: Data table isn’t  supported  for python 3.9

### ISSUE THREAD

**Issue by KishaniKandasamy** [h2oai/datatable#3213]
- Did you find a bug in datatable, or maybe the bug found you?
I found issues while building datatable for python version 3.9. 
After downgraded to python 3.8 ,It works.

- How to reproduce the bug?
<img width="1792" alt="Screenshot 2021-12-08 at 23 13 33" src="https://user-images.githubusercontent.com/53715187/145262886-503fa7d6-dc77-4900-802d-280d74e5bdf2.png">

<img width="1792" alt="Screenshot 2021-12-08 at 23 20 14" src="https://user-images.githubusercontent.com/53715187/145262983-43e2bdeb-ac91-4ce8-add6-af3e9466804c.png">

- Your environment?
datatable version == 0.11.0
python3 version = 3.9.6
Mac OS

**Comment by samukweku** [comment]
Kindly upgrade your datatable version to 1.0 at least

**Comment by oleksiyskononenko** [comment]
@KishaniKandasamy, datatable `0.11.0` was released on Sep 19, 2020. At that time there was no python `3.9` available, as it was released only on Oct. 5, 2020. 

Is there any particular reason you need `0.11.0`? If not, then, as @samukweku suggests, simply install the latest datatable with `pip install datatable`.

**Comment by KishaniKandasamy** [comment]
Hi @oleksiyskononenko  actually I encountered this issue when I set up mlops wave app locally. Data table 0.11.0 is mentioned in the  requirements.txt there.

**Comment by oleksiyskononenko** [comment]
I see. My feeling is that in this case it makes more sense to upgrade datatable version in the `requirement.txt` for that wave app, rather than to release old versions of datatable for new pythons.

**Comment by KishaniKandasamy** [comment]
Yes That could be the solution..Many Thanks @oleksiyskononenko & @samukweku

**Comment by oleksiyskononenko** [comment]
Closing, as upgrading datatable should solve the issue.
