### ISSUE TITLE
Support caseless match in `dt.re.match()`

### ISSUE THREAD

**Issue by pscholze** [h2oai/datatable#3216]
Hi all,
is there any way to use regex modifiers with re.match()?

Thanks in advance
Peter

**Comment by samukweku** [comment]
@pscholze kindly elaborate on your question with some examples

**Comment by pscholze** [comment]
"(?i)caseless" should match "CASELESS" as well as "caseLESS"

**Comment by samukweku** [comment]
@pscholze the example should be a frame. More importantly, did you try your example? Did it fail? What was the output?

**Comment by samukweku** [comment]
@pscholze I looked it up a bit, and C++ does not support the `?i` syntax for case sensitivity; one way around it is to pass another parameter for `case`. @oleksiyskononenko what's your take on this?

**Comment by pscholze** [comment]
> @pscholze the example should be a frame. More importantly, did you try your example? Did it fail? What was the output?

Traceback (most recent call last):
  D:/workspace/PycharmProjects/datasmelter-services/retest.py:7 in <module>  print(df[(dt.re.match(f['last_name'], **_r"(?i).*meier.*"_**)), :])

ValueError: Invalid regular expression: regex_error(error_syntax)

**Comment by oleksiyskononenko** [comment]
Yes, `std::regex_match()` that we're using on the C++ side doesn't support modifiers in the form of `(?)`. 

However, modifiers are supported in the form of [std::regex_constants::syntax_option_type](https://en.cppreference.com/w/cpp/regex/syntax_option_type), one of which is `icase`. To make it work, we may need to add new parameters to `datatable.re.match()` function as a separate parameter, e.g. `flags`.
