### ISSUE TITLE
Missing functions: cannot import name 'prod' from 'datatable'

### ISSUE THREAD

**Issue by devinliu-rayliant** [h2oai/datatable#3228]
Hi All,

First of all, i have very limited experience openning issues on Github, but I decide to do so because I don't see any related comments.

I installed datatable through pip on Python 3.9.7.

```
C:\Windows\system32>pip install datatable
Collecting datatable
  Downloading datatable-1.0.0-cp39-cp39-win_amd64.whl (4.0 MB)
Installing collected packages: datatable
Successfully installed datatable-1.0.0
```

Everything works fine until I run:

`from datatable import prod`

which gives:

ImportError: cannot import name 'prod' from 'datatable'

The other function I found with same error was datatable.countna(). They are listed here in the docs, but it appears that they are not in .../site-packages/datatable/__init__.py
- https://datatable.readthedocs.io/en/latest/api/index-api.html#

I do see a function named prod_reducer() here:
- https://github.com/h2oai/datatable/blob/7fa37145590e2f68e8b2e9f7d4391c93b134f216/src/core/expr/head_reduce_unary.cc#L190-L201

Is there a way for a quick fix?

Thanks!

**Comment by oleksiyskononenko** [comment]
The `prod` function was implemented only recently, so it was not included in the datatable `1.0.0` that you have installed by using pip. You need to install the most recent dev version to use it.

We should probably update our documentation to reflect that this function will only be available in datatable `1.1.0`. Thanks for letting us know.
