### ISSUE TITLE
Parameter `tempdir` is not honored for memory limited `fread()` operation

### ISSUE THREAD

**Issue by rsensan** [h2oai/datatable#3244]
- Did you find a bug in datatable, or maybe the bug found you?
  tempdir value provided is not used. Instead its using default temp dir /tmp

- How to reproduce the bug?
  df = dt.fread(file_path, na_strings=[''], header=False, **tempdir='/home/scripts/log'**, memory_limit=mem_limit, verbose=True)

- What was the expected behavior?
  dt.fread, should use the giving tempdir path and store the temporary files. 

- Your environment?
datatable version: 1.0.0
python version: 3.6.8 
operating system: CentOS Linux

- `[bug]`

**Code**: 
<img width="822" alt="image" src="https://user-images.githubusercontent.com/351331/157623790-87aa633d-aa92-4c24-8d9d-28f3aaa14969.png">

**Verbose**: 
You can see, instead of creating tmp file under **/home/scripts/log**, its creating under **/tmp** folder
<img width="927" alt="image" src="https://user-images.githubusercontent.com/351331/157621997-0bc402a9-85e7-43e6-9765-977255668a48.png">

**Comment by rsensan** [comment]
Also am getting "**Reading data Segmentation fault**" error when reading 45 GB of data.

**Comment by rsensan** [comment]
Eventhough memory_limit provided, it is comsuming RAM memory and not creating temp file. 
Is this an issue with memory_limit or tempdir? 
Kindly help me

**Comment by oleksiyskononenko** [comment]
`memory_limit` parameter is not enforced strictly, please refer to https://datatable.readthedocs.io/en/latest/api/dt/fread.html#memory_limit

As for the temp dir issue, could you please point me to the data?

**Comment by rsensan** [comment]
Thank you @oleksiyskononenko 

I have two servers. 
In DEV server, 8 GB RAM, its able to read 45 GB of data, **dt.fread(file_path, memory_limit=3GB)**
Here it works as expected, after reaching the memory_limit, its creating files in /tmp path. 

In PROD server, with 64 GB RAM, its not reading the 45 GB file, **dt.fread(file_path, memory_limit=3GB)** even i tried with varions memory limit (10GB, 30GB, 50GB)
Here its not creating any /tmp file, consuming RAM memory without taking the limit and giving the "Reading data Segmentation fault" error. 

Same code, not working in PROD server. 

Kindly help me to solve the issue.

**Comment by oleksiyskononenko** [comment]
@rsensan It's complicated to say without having data, but can you confirm that you have 64GB and the file is only 45? Do you have any other memory consuming applications on your prod server?

**Comment by oleksiyskononenko** [comment]
As for the `tempdir` not working, I believe this parameter only controls a temporary directory for extracting multiple sources from an archive. It is a good idea to make use of it when reading files that are larger than memory or when the `memory_limit` is hit, currently the python temporary directory is used in such cases.

**Comment by rsensan** [comment]
Thanks @oleksiyskononenko  for your inputs. 

I just tried with less memory_limit rather than increasing it. Now it works, able to read more than 45 GB file. 
Earlier I tried with 1GB, 2Gb, 3GB, 10GB, 30GB memory_limit, 
Now when I tried with 1024 byts it works.

**Comment by oleksiyskononenko** [comment]
Thanks for letting me know. However, if you have 64GB of RAM and the file is only 45GB, then I'm not sure why you need to set any `memory_limit` at all.

**Comment by rsensan** [comment]
@oleksiyskononenko  Yes I tried without _**memory_limit**_  in both DEV (8GB RAM) and (64 GB RAM),  
both throws the same error "**Reading data Segmentation fault**"

**Comment by rsensan** [comment]
`tempdir ` is not working as expected. Instead of taking the provided `tempdir ` value, it taking system default teporary directiry (_**/tmp**_). I have to change the default temp dir path using environment variable `printenv TMP=/home/custom/temp`

In DEV (8GB RAM), `memory_limit `is working as expected. After the limiting size, it creating temp file in `tempdir `directory

Whereas in PROD (64 GB RAM), its not creating temp file in `tempdir`, instead consuming RAM memory itself. But with `memory_limit=100` (100 bytes), it works in PROD (64 GB RAM)
