### ISSUE TITLE
Improve documentation for `dt.cut()`

### ISSUE THREAD

**Issue by mvolar** [h2oai/datatable#3247]
Hello,

python version is Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32, the version of datatable is version='1.0.0'.

When using the dt.cut() function when passing a range type I get the following:

```
TypeError: bins parameter must be a list or a tuple, instead got <class 'range'>
```

Then I pass it a tuple of interval ranges which looks like this

```
((1, 1001),
 (10001, 11001),
 (20001, 21001),
 (30001, 31001))
```
and get the following error:

```
Expected a Frame, instead got <class 'tuple'>
```

Then tried passing it a Frame (datatable frame), which is the same tuple, but just put into a Frame:

```
bins parameter must be a list or a tuple, instead got <class 'datatable.Frame'>
```

I looked into the "cut()" source code and "Expected a Frame, instead got <class 'tuple'>" error was not found, so I do not know what else to try to pass to the command call, and the documentation of the function does not provide an example class/type which should be passed into the function call so I am a bit stuck, and don't know whether it's a bug or my error?

In R's data table I am used to using the "cut_width()" function which handles this sort of problems easily and pandas cut function also works flawlessly but is very slow on my large dataset (6 tables of 700mil rows).

Also one additional question I have is wether you plan on implementing advanced regex features (not only match) into the datatable FEexpr system, similar to the pandas.str_extract str_remove syntax or the same system already implemented in R?

**Comment by oleksiyskononenko** [comment]
`bins` should be a list/tuple of single-column frames just as it is written in [documentation](https://datatable.readthedocs.io/en/latest/api/dt/cut.html#bins):

>List/tuple of single-column frames containing interval edges in strictly increasing order

What you are trying to pass is a different kind of structure, that is why you're getting all these errors.

**Comment by mvolar** [comment]
So basically i need a list of frames, where each member of the list corresponds to a single column in the data frame i want to cut. Nice. Coming from years of experience with R data.table this sort of trickery was unexpected and I presumed something was off, and the sentence "tuple of single column frames" just didn't make sense to me. Thanks for the prompt response. Issue is resolved.

**Comment by oleksiyskononenko** [comment]
Yes, we designed it that way to be able to cut several columns at once. Since each column can be cut with different number of bins, we have to provide the bin columns as separate one-column frames.
