### ISSUE TITLE
Unknown stype time64

### ISSUE THREAD

**Issue by naarkhoo** [h2oai/datatable#3252]
I am reading a large .csv file

<img width="560" alt="image" src="https://user-images.githubusercontent.com/224059/161863822-e6460bb5-ab0e-4115-97a9-7a86273b8e5e.png">

but when I try to print the first row or any other operation I get the following error
`RuntimeError: Unknown stype time64
`

<img width="263" alt="image" src="https://user-images.githubusercontent.com/224059/161863913-28ca3f66-78b9-4b15-8eef-a3efcb9c07dd.png">

I am using version '1.0.0a0+build.1622465698.nyt21'

**Comment by oleksiyskononenko** [comment]
Can you share your csv file or may be a portion of it that could be used to reproduce the issue?

**Comment by naarkhoo** [comment]
thanks the file is 3G (and I only read first 100K lines) in gz format :( let me think what I can do - but I guess it has something to do with gzip format - because if I compress and read it it works file.

**Comment by oleksiyskononenko** [comment]
@naarkhoo how did you install datatable? My feeling is that you have built locally some old dev version from source. Try to install it from pypi repo as `pip install datatable`, then it should have a full support for time columns.

**Comment by oleksiyskononenko** [comment]
Closing as not sure what could be done here without data. Feel free to reopen if a repro is available.
