### ISSUE TITLE
Implement cumulative functions

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#3279]
The list of functions to be implemented and the corresponding PR's
- [x] `cumsum()` https://github.com/h2oai/datatable/pull/3257
- [x] `cumprod()` https://github.com/h2oai/datatable/pull/3304
- [x] `cummax()` https://github.com/h2oai/datatable/pull/3288
- [x] `cummin()` https://github.com/h2oai/datatable/pull/3288
- [x] `cumcount()` https://github.com/h2oai/datatable/pull/3310
- [x] `ngroup()` - not strictly cumulative https://github.com/h2oai/datatable/pull/3310
- [x] `fillna()` for forward/backward fill https://github.com/h2oai/datatable/pull/3311
- [x] `fillna()` for filling with a value https://github.com/h2oai/datatable/pull/3344 
~~- [ ] rank~~ continued on #3148 
~~- [ ] rolling aggregations~~    continued on #1500

**Comment by vopani** [comment]
These would be great and long due.

Is there an ETA of when this would be available (next release)?

**Comment by samukweku** [comment]
@vopani currently working on them ... cant specify an ETA though ... contributions are welcome also. You can test the `cumsum` function by downloading the latest dev version

**Comment by vopani** [comment]
I tried out the dev version to implement the [AMEX Default Metric](https://www.kaggle.com/competitions/amex-default-prediction/overview/evaluation) as described here: https://www.kaggle.com/code/rohanrao/amex-competition-metric-implementations#Datatable-Implementation

When I use the native `cumsum` method, it runs much slower compared to converting to `pandas` and using its `cumsum` and converting back to `datatable`.

Here's the entire code for reference: 

```python
# install latest datatable
!pip install git+https://github.com/h2oai/datatable

## import packages
import datatable as dt
import random

## check version
print(dt.__version__)

>>> 
1.1.0a0+build.1653978586.root
>>>

# load data
train_labels = dt.fread('../input/amex-default-prediction/train_labels.csv')['target']
predictions = dt.Frame((train_labels.to_numpy().ravel() / 2.0 + [random.random() for i in range(train_labels.nrows)]) / 2.0)

## amex metric
def amex_metric_old(y_true: dt.Frame, y_pred: dt.Frame) -> float:

    # create datatable frame
    df = dt.Frame(target=y_true, prediction=y_pred)

    # sort by descending prediction values
    df = df[:, :, dt.sort(-dt.f.prediction)]

    # create row weights, its percentage & cumulative sum
    df['weight'] = dt.ifelse(dt.f.target == 0, 20, 1)
    df['weight_perc'] = dt.f.weight /  df['weight'].sum1()
    df['weight_perc_cumsum'] = df['weight_perc'].to_pandas().cumsum()

    # filter the top 4%
    df_four_pct = df[dt.f.weight_perc_cumsum <= 0.04, :]

    # default rate captured at 4%
    d = df_four_pct['target'].sum1() / df['target'].sum1()

    # weighted positives
    total_pos = dt.sum(dt.f.target * dt.f.weight)
    df['pos_found'] = dt.f.target * dt.f.weight

    # weighted gini coefficient
    df['pos_found_cumsum'] = df['pos_found'].to_pandas().cumsum()
    df['lorentz'] = dt.f.pos_found_cumsum / total_pos
    df['gini'] = (dt.f.lorentz - dt.f.weight_perc_cumsum) * dt.f.weight
    
    # base weighted gini coefficient
    df = df[:, :, dt.sort(-dt.f.target)]
    df['weight_perc_cumsum_base'] = df['weight_perc'].to_pandas().cumsum()
    df['pos_found_cumsum_base'] = df['pos_found'].to_pandas().cumsum()
    df['lorentz_base'] = dt.f.pos_found_cumsum_base / total_pos
    df['gini_base'] = (dt.f.lorentz_base - dt.f.weight_perc_cumsum_base) * dt.f.weight

    # normalized weighted gini coefficient
    g = df['gini'].sum1() / df['gini_base'].sum1()

    # amex metric
    m = 0.5 * (g + d)

    return m


def amex_metric_new(y_true: dt.Frame, y_pred: dt.Frame) -> float:

    # create datatable frame
    df = dt.Frame(target=y_true, prediction=y_pred)

    # sort by descending prediction values
    df = df[:, :, dt.sort(-dt.f.prediction)]

    # create row weights, its percentage & cumulative sum
    df['weight'] = dt.ifelse(dt.f.target == 0, 20, 1)
    df['weight_perc'] = dt.f.weight /  df['weight'].sum1()
    df['weight_perc_cumsum'] = dt.f.weight_perc.cumsum()

    # filter the top 4%
    df_four_pct = df[dt.f.weight_perc_cumsum <= 0.04, :]

    # default rate captured at 4%
    d = df_four_pct['target'].sum1() / df['target'].sum1()

    # weighted positives
    total_pos = dt.sum(dt.f.target * dt.f.weight)
    df['pos_found'] = dt.f.target * dt.f.weight

    # weighted gini coefficient
    df['pos_found_cumsum'] = dt.f.pos_found.cumsum()
    df['lorentz'] = dt.f.pos_found_cumsum / total_pos
    df['gini'] = (dt.f.lorentz - dt.f.weight_perc_cumsum) * dt.f.weight
    
    # base weighted gini coefficient
    df = df[:, :, dt.sort(-dt.f.target)]
    df['weight_perc_cumsum_base'] = dt.f.weight_perc.cumsum()
    df['pos_found_cumsum_base'] = dt.f.pos_found.cumsum()
    df['lorentz_base'] = dt.f.pos_found_cumsum_base / total_pos
    df['gini_base'] = (dt.f.lorentz_base - dt.f.weight_perc_cumsum_base) * dt.f.weight

    # normalized weighted gini coefficient
    g = df['gini'].sum1() / df['gini_base'].sum1()

    # amex metric
    m = 0.5 * (g + d)

    return m

## speed comparison
import time

time_old = []
time_new = []

for i in range(100):
    start_old = time.time()
    metric_old = amex_metric_old(train_labels, predictions)
    end_old = time.time()
    time_old.append((end_old-start_old))

    start_new = time.time()
    metric_new = amex_metric_new(train_labels, predictions)
    end_new = time.time()
    time_new.append((end_new-start_new))

print(f'Metric Processing Time (in seconds)\n')
print(f'Old: {sum(time_old) / len(time_old)}')
print(f'New: {sum(time_new) / len(time_new)}')

>>>
Metric Processing Time (in seconds)

Old: 0.540272569656372
New: 0.7209867787361145
>>>
```

Apologies for the long-ish code but the only lines to look at the the four `cumsum` statements in `old` vs `new` and the runtime of `old` being faster than that of `new`.

The dataset used is [here](https://www.kaggle.com/competitions/amex-default-prediction/data?select=train_labels.csv).

**Comment by vopani** [comment]
@samukweku Yeah apologies, let me run some more tests and share better examples / feedback.

Thanks again for these cumulative functions, they are super useful and help in bridging the gap to pandas.

**Comment by samukweku** [comment]
tests comparison with `np.cumsum`:


```py
import numpy as np
from datatable import dt, f

In [12]: a = np.arange(10_000_000)

In [13]: %timeit a.cumsum()
22.2 ms ± 196 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [14]: DT = dt.Frame(a)

In [15]: %timeit DT[:, f.C0.cumsum()]
46.7 ms ± 1.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by oleksiyskononenko** [comment]
@samukweku we need to address https://github.com/h2oai/datatable/issues/3081 to improve performance in the case when there is no group-by context. For grouped frames we're fully parallel now.

**Comment by samukweku** [comment]
thanks @oleksiyskononenko , maybe you can explain more what you mean by parallelisation in terms of the actual data. How is profiling done in C++? by the way, is there any way to do interactive work in C++?

**Comment by samukweku** [comment]
@oleksiyskononenko I was reading up on cumulative sum, and found a possible performance option with Fenwick tree. What are your thoughts on it? is it worth the effort? 

As an aside, when we call get_edit_datatable, does it return a vector? where do I trace this to see its implementation

I'm also thinking of building on your example of templates and convert the cumsum implementation to support cumprod, since they are essentially the same, just the change of the operator.

**Comment by oleksiyskononenko** [comment]
@samukweku 

>maybe you can explain more what you mean by parallelisation in terms of the actual data. 

It means that we parallelize loops to go over the frame rows, currently our parallel loops for cumulative functions/reducers go over the groups.

>How is profiling done in C++? 

To start with you can read couple of threads on SO, something like https://stackoverflow.com/questions/375913/how-can-i-profile-c-code-running-on-linux

>by the way, is there any way to do interactive work in C++?

Probably yes, I don't have experience with that.

>I was reading up on cumulative sum, and found a possible performance option with Fenwick tree. What are your thoughts on it? is it worth the effort?

First, let's looks through the code to see if there are any obvious bottlenecks. 
Second, we should decide if the `cumsum()` performance is acceptable or not. Is it currently x2 slower than numpy? 
Then we could discuss ways to improve performance if needed.

>As an aside, when we call get_edit_datatable, does it return a vector? where do I trace this to see its implementation

We don't have `get_edit_datatable()` method. Perhaps you mean `get_data_editable()`? It returns a pointer to the column's underlying buffers. Implementation depends on the column type. See, for instance:
https://github.com/h2oai/datatable/blob/main/src/core/column/sentinel_fw.cc#L234-L238
https://github.com/h2oai/datatable/blob/main/src/core/column/sentinel_str.cc#L118-L122

>I'm also thinking of building on your example of templates and convert the cumsum implementation to support cumprod, since they are essentially the same, just the change of the operator.

Sounds like a great idea.

**Comment by samukweku** [comment]
@oleksiyskononenko @Peter-Pasta @vopani should we stick to the name `cumcount` or use `row_number`. I bring up `row_number` because of sql. checking to see which one is more intuitive

**Comment by oleksiyskononenko** [comment]
@samukweku What functionality you want to achieve with this function?

**Comment by samukweku** [comment]
@oleksiyskononenko it is essentially row numbers, but it is more helpful when you want the row number per group ... #2892 is the reason behind the cumulative functions. In pandas it is referred to as cumcount, in datatable it can be pulled off with `1..N` or something similar ... in Postgres/sql it is usually referred to as row_number. I hope I explained well enough?

**Comment by vopani** [comment]
`cumcount` is a very natural (and common) term used by Data Scientists.
Which is also why `pandas` uses the same.

**Comment by oleksiyskononenko** [comment]
Actually, in datatable there is already a function called `count()` that is used to 
>Calculate the number of non-missing values for each column

see https://datatable.readthedocs.io/en/latest/api/dt/count.html for more details.

So the function named `cumcount()` is expected to be a cumulative equivalent of `count()`. But it will not be in this case. My feeling is that if we call a function `smthcount()` it is expected to count something, while in reality this function only returns the corresponding row id's that there is no need to count, they're already known internally.

**Comment by vopani** [comment]
The datatable `count()` is very unnatural and unintuitive, which should ideally be renamed :-)
Even SQL `count` means #rows.

But ok, for the benefit of this discussion, maybe using or `cumrows()` or `cumrowcount()` might be suitable. We can also have the `cumcount()` that is the cumulative equivalent of `count()`. It is a useful aggregation but many users might misinterpret its result initially. Hopefully sufficient documentation will help.

**Comment by samukweku** [comment]
> `ROW_NUMBER` function is a SQL ranking function that assigns a sequential rank number to each new record in a partition.  

That's the definition from SQL server

**Comment by samukweku** [comment]
> cumcount - Number each item in each group from 0 to the length of that group - 1.

Definition from pandas

**Comment by oleksiyskononenko** [comment]
Well, I'm not sure why you think it is an unnatural and unintuitive name. The same name/behavior is used in, at least, [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.count.html) and [pyarrow](https://arrow.apache.org/docs/python/generated/pyarrow.compute.count.html). datatable just sticks to the same name and convention. 

What I find unintuitive though, is pandas using the name `count()` to calculate non-missing values and `cumcount()` to produce a simple row counter that doesn't care about the element's validity. 

As for the function name, I'm not sure what could be the good name at this point. We probably need to review what others like pandas, numpy, pyarrow, data.table, etc. are doing to have a good guess.

**Comment by vopani** [comment]
> The same name/behavior is used in, at least, [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.count.html) and [pyarrow](https://arrow.apache.org/docs/python/generated/pyarrow.compute.count.html). datatable just sticks to the same name and convention.

Yes, this complaint is across libraries actually.

> Well, I'm not sure why you think it is an unnatural and unintuitive name.

(Being a teacher) Most of my students keep getting it wrong (without realizing) because it implements `count` with a condition without being explicit.

Anyway, `numpy` doesn't have a direct implementation and is most verbose, though it will likely be implemented in the [count_nonzero ](https://numpy.org/doc/stable/reference/generated/numpy.count_nonzero.html) format. Currently, you'd need to do a `np.count_nonzero(~np.isnan(data))` or use `np.sum()`.

I'd still recommend `cumcount` or `cumrows` for the function name but feel free to explore more options / ideas.

**Comment by oleksiyskononenko** [comment]
I guess it all depends on the definition. If we define `count()` as a function to count values, then obviously it should skip missing values — and then this is not an "implicit condition" anymore. Some people may think that this function should count rows instead, and this is where the confusion comes from. 

The name probably originated from pandas and that's good that we match the name. May be we need to call the new function `cumcount()` for the same reason.

**Comment by samukweku** [comment]
back to the performance and I notice the poor performance extends to other cumulative functions, this is a naive example below for cummax: 

```
py
from datatable import dt, f, by
DT = dt.Frame({"A": [2, None, 5, -1, 0],
               "B": [None, None, None, None, None],
               "C": [5.4, 3, 2.2, 4.323, 3],
               "D": ['a', 'a', 'b', 'b', 'b']})

In [38]: DT = dt.repeat(DT, 10_000)

In [39]: df = DT.to_pandas()

In [40]: %timeit df.groupby('D')[['A','C']].cummax()
2.22 ms ± 34.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [41]: %timeit DT[:, dt.cummax(f[:]), by('D')]
120 ms ± 2.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

I haven't had time to investigate this (I have never profiled a C++ function before, so this is new ground for me). I feel it would be better to look into this before proceeding with the other cumulative functions. I'll make out time to investigate; I would very much love your guidance on this journey @oleksiyskononenko

**Comment by oleksiyskononenko** [comment]
@samukweku I guess

```python
DT[:, dt.cummax(f[:]), by('D')]
```

and

```python
df.groupby('D')[['A','C']].cummax()
```

are doing different things. Just compare the results
```
      | D          A     B        C
      | str32  int32  void  float64
----- + -----  -----  ----  -------
    0 | a          2    NA    5.4  
    1 | a          2    NA    5.4  
    2 | a          2    NA    5.4  
    3 | a          2    NA    5.4  
    4 | a          2    NA    5.4  
    5 | a          2    NA    5.4  
    6 | a          2    NA    5.4  
    7 | a          2    NA    5.4  
    8 | a          2    NA    5.4  
    9 | a          2    NA    5.4  
   10 | a          2    NA    5.4  
   11 | a          2    NA    5.4  
   12 | a          2    NA    5.4  
   13 | a          2    NA    5.4  
   14 | a          2    NA    5.4  
    … | …          …     …        …
49995 | b          5    NA    4.323
49996 | b          5    NA    4.323
49997 | b          5    NA    4.323
49998 | b          5    NA    4.323
49999 | b          5    NA    4.323
[50000 rows x 4 columns]
```

and
```
         A      C
0      2.0  5.400
1      NaN  5.400
2      5.0  2.200
3      5.0  4.323
4      5.0  4.323
...    ...    ...
49995  2.0  5.400
49996  NaN  5.400
49997  5.0  4.323
49998  5.0  4.323
49999  5.0  4.323

[50000 rows x 2 columns]
````

While datatable really calculates `cummax()` within `a` and `b` groups, pandas is doing something different.

**Comment by samukweku** [comment]
Thanks @oleksiyskononenko . How can I tell what mode I'm running it in?  I just ran it in my terminal. What mode should I run it in? How do I switch between modes?

If you don't mind can you add the pandas timeit output as well.

**Comment by oleksiyskononenko** [comment]
@samukweku It depends on how you build the code, you could either do `make build` or `make debug`: https://datatable.readthedocs.io/en/latest/start/install.html#install-datatable-in-editable-mode To test performance, you need to build it in the release mode.

Yes, here is pandas — it is comparable to what you posted:
```python
3.21 ms ± 12 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Anyways, if you look at the output I attached above you will see that the groupby is doing different things in pandas vs dt. In pandas it doesn't re-arrange the rows, but only create groups internally. While in datatable, the result of the group by is a grouped frame with the rows being re-arranged into the corresponding groups. 

What it means is that we're comparing different things here and not purely the `cummax()` performance. The `cummax()` performance could be compared in the case when there is no groupby. On my end I'm getting comparable results with dt being slightly faster.

**Comment by samukweku** [comment]
thanks for the feedback @oleksiyskononenko ... regarding the groupby semantics, is there a ticket for not rearranging the groups, as I believe it will give more performance?

**Comment by oleksiyskononenko** [comment]
@samukweku I guess there is a ticket https://github.com/h2oai/datatable/issues/1070

**Comment by samukweku** [comment]
@oleksiyskononenko pending when you are done with #3333, I might continue with the remaining functions here. At the moment, I'm looking to expand on `fillna` to support scalars, and also the `rank` function. Stuck a bit in my `fillna` progress; I will create a PR for you to have a look at. For the `rank` function, which function can I use to get the groups and order when sort is applied? Do you mind pointing me in the right direction? Thanks

**Comment by oleksiyskononenko** [comment]
@samukweku Yeah, let me take a look at #3333. As for the 

>which function can I use to get the groups and order when sort is applied?

Not sure what you mean. There is a `Groupby::get_group()` method, is it what you need?

**Comment by samukweku** [comment]
@oleksiyskononenko for sorting, I believe groups are created, with a numbering (guessing). Example: 

```py
DT = dt.range([2,2,3,4,4])
```

if `DT` is sorted, it should have 3 groups : `2, 3, 4`, and the numbering order should be `0,0,1,2,2`. The same idea applies if a groupby is present, but the numbering order is within each group, and restarts for each group. Is there somewhere in evalcontext where this is available after sorting is called on the dataframe? I was hoping to just reuse that instead. I want to use that to implement the `rank` function, and make it similar in API as SQL's (which I deem to be simple enough to grasp)

**Comment by oleksiyskononenko** [comment]
Sorting will only return you the `RowIndex` and grouping will return both the `RowIndex` and the group information, see https://github.com/h2oai/datatable/blob/main/src/core/sort.cc#L1411-L1495

You can use this information to implement the `rank()` function. First, you need to group the column (if not already grouped) and then calculate rank based on the returned grouping information.

**Comment by oleksiyskononenko** [comment]
My feeling is that before jumping into the `rank()` implementation, you need to go through implementation details of a groupby: rowindex, offsets, etc. Once you understand their purpose and implementation, it won't be difficult to implement the `rank()`.

**Comment by oleksiyskononenko** [comment]
@samukweku What if we add parameter `reverse` to `dt.cummin()`, `dt.cummax()`, `dt.cumsum()` and `dt.cumprod()`, just like we did for `dt.fillna()` and `dt.cumcount()`?

**Comment by oleksiyskononenko** [comment]
I see, so this is basically some moving windows calculations. Then, may be we open a new issue with listing all the rolling aggregations you have in mind?

**Comment by oleksiyskononenko** [comment]
As for the `reverse` parameter, it is still possible to do this with the current implementation:
- reversing a frame;
- applying `cum*()` function;
- reversing the frame again.

But having a `reverse` parameter will make it cleaner and slightly faster, as the user won't need to reverse the frame twice.

**Comment by samukweku** [comment]
I'll make out some time to add the reverse parameter to the existing functions. Still looking forward to you help on the rowall/rowany for the [nth function](https://github.com/h2oai/datatable/pull/3346#issuecomment-1288182884); i cant get around the FExpr_Rowall/rowany

**Comment by oleksiyskononenko** [comment]
@samukweku Yeah, sure. I will take a look at it.

**Comment by samukweku** [comment]
All functions here have been implemented; safe to close.

**Comment by samukweku** [comment]
reopened; will be closed after implementation of `reverse` parameter for cummin, cummax, cumsum, cumprod
