### ISSUE TITLE
Equivalent of R data.table's setorder() --- inplace sorting

### ISSUE THREAD

**Issue by cca32** [h2oai/datatable#3292]
I was wondering if it were possible to do inplace sorting. I understand there is:
```
DT.sort("A")
DT[:, :, sort(f.A)]
```
which is equivalent to something like this in R:
```
DT[order(A)]
```
but was wondering if there was python equivalent of:
```
setorder(DT, A)
```
or in `pandas`:
```
DT.sort_values('A', inplace=True)
```

**Comment by oleksiyskononenko** [comment]
We don't have an `inplace` option for `sort()`, but you can always do something like `DT = DT.sort("A")`.
