### ISSUE TITLE
Inconsistent column types returned by `sum()` 

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#3293]
```python
>>> from datatable import dt
>>> DT = dt.Frame([1, 2])
>>> DT.sum()
   |      C0
   | float64
-- + -------
 0 |       3
[1 row x 1 column]
>>> DT[:, dt.sum(f[0])]
   |    C0
   | int64
-- + -----
 0 |     3
[1 row x 1 column]
```

Note, that in the first case the returned column type is `float64` while in the second case it is `int64`. It would be nice to return the same column type in the both cases.

**Comment by samukweku** [comment]
I raised an issue here : #2904

**Comment by oleksiyskononenko** [comment]
Ah, yes, couldn’t find it. Probably we just need more minimalistic example and the topic should mention `sum()`.

**Comment by oleksiyskononenko** [comment]
Duplicate of #2904
