### ISSUE TITLE
Fillna function

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#3300]
-  implement fillna, similar to pandas fillna

- `DT[:, dt.fillna(f[:])]`

**Comment by oleksiyskononenko** [comment]
What about just using `DT.replace(None, some_value)`?

**Comment by samukweku** [comment]
Yea, I was thinking more of it as a function. I am also thinking of forward and backward fill, similar to that in pandas

**Comment by samukweku** [comment]
Moving the conversation to #3139

**Comment by oleksiyskononenko** [comment]
Sorry, I didn't get that you want to implement forward and backward fill here. Don't hesitate to re-open this issue.
