### ISSUE TITLE
`dt.fread()` should support reading from S3 path 

### ISSUE THREAD

**Issue by mflevine** [h2oai/datatable#3302]
It would be really nice if `fread` supported s3 urls to be able to read data from Amazon buckets.

Example would be like
```python
import datatable as dt
dt.fread("s3://tcga-2-open/000000f5-8270-43b0-9b05-59d1c90a61e1/5d9fb1f2-45d8-4af0-9c53-fa76162706f5.methylation_array.sesame.level3betas.txt")
```

**Comment by samukweku** [comment]
@mflevine do you have any suggestions on the implementation? I think it is a good idea and if you have an idea it would be welcome, or maybe even a PR

**Comment by samukweku** [comment]
At the very least boto3 becomes a dependency

**Comment by oleksiyskononenko** [comment]
We are currently using [urllib](https://docs.python.org/3/library/urllib.html) to read URL-like resources with `fread()`. So if you convert your S3 path to URL, it will work out of the box:

```
from datatable import dt
DT = dt.fread("https://tcga-2-open.s3.amazonaws.com/000000f5-8270-43b0-9b05-59d1c90a61e1/5d9fb1f2-45d8-4af0-9c53-fa76162706f5.methylation_array.sesame.level3betas.txt")
```

If you want to be able to specify S3 path directly, you can take a look at this package: https://pypi.org/project/urllib-s3/. Once installed and configured it claims to work as an S3 handler for `urllib`.
