### ISSUE TITLE
Error when run pip install git+https://github.com/h2oai/datatable

### ISSUE THREAD

**Issue by thongfam** [h2oai/datatable#3305]
Hi,

I have the latest version of Python and trying to install datatable but keep getting error :

Collecting git+https://github.com/h2oai/datatable.git
  Cloning https://github.com/h2oai/datatable.git to c:\users\thongfam\appdata\local\temp\pip-req-build-ik36rv91
  Running command git clone --filter=blob:none --quiet https://github.com/h2oai/datatable.git 'C:\Users\thongfam\AppData\Local\Temp\pip-req-build-ik36rv91'
  Resolved https://github.com/h2oai/datatable.git to commit 029646f21c45576290f18272795e9fd6229415eb
  Getting requirements to build wheel ... done
  **Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.**
  │ exit code: 1

Saw some reference posting on this and have proceed to try installing from github using : 

pip install git+https://github.com/h2oai/datatable

However, the error persists and when scroll further down, I can see another error with "msvc_path" 👍 

    **% msvc_path)
      NameError: name 'msvc_path' is not defined
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed**

Can anyone help on this and appreciate your advise, thanks.

**Comment by oleksiyskononenko** [comment]
In order to help you, could you please provide the following information:
- your python version;
- your OS version;
- command you run to install datatable.

**Comment by oleksiyskononenko** [comment]
We've added support for python 3.10 only recently, so there is no wheels for it in the pypi repo. Try to install the latest dev build of datatable as
```
pip install https://ci.appveyor.com/api/buildjobs/c96ju869ettj3ysy/artifacts/dist/datatable-1.1.0a2157-cp310-cp310-win_amd64.whl
```

**Comment by thongfam** [comment]
Hi,

Really thanks for the prompt reply. It finally works with the latest dev build of the database :)
