### ISSUE TITLE
How to read Azure blob file into datatable?

### ISSUE THREAD

**Issue by sumithrasw** [h2oai/datatable#3326]
Hi,
I wanted to know how to read a file from azure blob into datatable using the azure blob connection details.
I couldnt find any documentation regarding the same.
Thanks in advance

**Comment by oleksiyskononenko** [comment]
I guess you can do something similar to what documentation suggests here: https://docs.microsoft.com/en-us/azure/architecture/data-science-process/explore-data-blob

Just replace the step #2 with
```python
import datatable as dt
DT = dt.fread(LOCALFILENAME)
```

**Comment by sumithrasw** [comment]
Hi,

Thank you so much for your response. it worked!
I am trying to read more than 18million records from csv and parquet files in Azure blob. and 18 million is taking lot of time to get downloaded. I wanted to know if there is a way to read it directly into datatable without downloading.

**Comment by oleksiyskononenko** [comment]
@sumithrasw Unfortunately, I don't think there is a way around it. Since datatable runs locally, you need to get data locally to read it with datatable.

**Comment by sumithrasw** [comment]
got it, thank you :)
