### ISSUE TITLE
skip computation for grouped column

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#3330]
- related to the cumulative functions #3279 , with the idea from @oleksiyskononenko https://github.com/h2oai/datatable/pull/3311#discussion_r939595404
- grouped columns should be skipped since there is really nothing to do there
- cummax()
- cummin()

**Comment by oleksiyskononenko** [comment]
I guess we should list the functions for which they could be skipped. For instance `cummax()` and `cummin()` could skip them, as the cumulative max/min is essentially the constant element in the group. However, for `cumprod()` and `cumsum()` they can't be skipped, may be the computation could be simplified, but I doubt it is worth to add a separate path in this case.
