### ISSUE TITLE
How to roll up duplicate observation in pydatatable?

### ISSUE THREAD

**Issue by myamullaciencia** [h2oai/datatable#3339]
Could someone please take a look at this and answer it on SO?

[How to roll up duplicate observation in pydatatable?](https://stackoverflow.com/questions/73382830/how-to-roll-up-duplicate-observation-in-pydatatable)

Since it is an urgent request i'm posting it on github to get a quicker reply.

**Comment by samukweku** [comment]
Once string functions are implemented (probably dependent on progress on the array type) we should revisit this. At the moment though, it is not possible to do the string join part of the question

**Comment by oleksiyskononenko** [comment]
Yeah, currently there is no reducer to concatenate strings. To remove duplicates, one can simply group by the columns in question though.

**Comment by myamullaciencia** [comment]
OK THANKS FOR YOUR INFORMATION. CLOSING IT NOW;
