### ISSUE TITLE
Cumulative functions crash when applied to some reducers

### ISSUE THREAD

**Issue by samukweku** [h2oai/datatable#3345]
- Did you find a bug in datatable, or maybe the bug found you?
Method chaining fails in some cases - I have noticed it for reducing vs non-reducing aggregations.

- How to reproduce the bug?
```py
from datatable import dt, f
DT = dt.Frame({"A": [1, 1, 2, 1, 2],
               "B": [None, 2, 3, 4, None],
               "C":[True, False, False, True, True]})
DT
   |     A      B      C
   | int32  int32  bool8
-- + -----  -----  -----
 0 |     1     NA      1
 1 |     1      2      0
 2 |     2      3      0
 3 |     1      4      1
 4 |     2     NA      1
[5 rows x 3 columns]


# this works
DT[:, f[:].cumsum().sum(), 'A']
Out[159]:
   |     A      B      C
   | int32  int64  int64
-- + -----  -----  -----
 0 |     1      8      4
 1 |     2      6      1
[2 rows x 3 columns]

# this fails
In [161]: DT[:, f[:].sum().cumsum(), 'A']
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [161], in <cell line: 1>()
----> 1 DT[:, f[:].sum().cumsum(), 'A']

In [160]: DT[:, f[:].sum(), 'A']
Out[160]:
   |     A      B      C
   | int32  int64  int64
-- + -----  -----  -----
 0 |     1      6      2
 1 |     2      3      1
[2 rows x 3 columns]

In [163]: DT[:, dt.cumsum(f[:].sum()), 'A']
[3]    50175 segmentation fault  ipython
```

- What was the expected behavior?
  In case it is not obvious, please tell us what result should your code
  produce.

- Your environment?
  datatable version - 1.1.0
python version - 3.9.12
operating system - mac monterrey

**Comment by oleksiyskononenko** [comment]
The first error is due to the fact reducers still use the old `Expr` architecture and need to be converted to `FExpr`: https://github.com/h2oai/datatable/issues/2562 As you're trying to invoke an `FExpr` method on an `Expr` object, it produces an error. Btw, it seems that the error is missing in ipython, on my side it throws

```python
AttributeError: 'Expr' object has no attribute 'cumsum'
```

So it is not really a bug, just WIP.

The second error looks like a real bug. In the debug version of the most recent dt, it hits
```cpp
AssertionError: Assertion 'num_threads_in_team() == 0' failed in src/core/column/latent.cc, line 104
```

For release, it does segfault.

**Comment by oleksiyskononenko** [comment]
It actually segfaults for `dt.cummin()`, `dt.cummax()`, `dt.cumsum()` and `dt.cumprod()` due to the incorrect usage of the latent columns.

MRE:
```python
from datatable import dt, f
DT = dt.Frame([[0, 1], ["a", "b"]])
DT[:, dt.cummin(f.C0.min()), f.C1] # segfault
```
