### ISSUE TITLE
Installation error on Ubuntu 20.04, python 3.10

### ISSUE THREAD

**Issue by teneon** [h2oai/datatable#3350]
Hi there,

i tried to install datatable in venv:

installation command used: **pip install datatable**
python version: **Python 3.10.7**
OS version: **Ubuntu 20.04**

I am getting the following error:

**pip install datatable**
```
Collecting datatable
  Downloading datatable-1.0.0.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 7.9 MB/s eta 0:00:00
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]

....
....
....

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Could you please help?

best regards,
Jim

**Comment by teneon** [comment]
I believe i've found it:

pip install https://h2o-release.s3.amazonaws.com/datatable/dev/datatable-1.1.0a2186/datatable-1.1.0a2186-cp310-cp310-manylinux_2_17_x86_64.whl

Is this a way to go?

**Comment by oleksiyskononenko** [comment]
@teneon yeah, that's the way to go. For the moment we don't have a datatable pypi release for python 3.10, but we support python 3.10 and you can install the most recent datatable dev version from our repo here: https://h2o-release.s3.amazonaws.com/datatable/index.html
