### ISSUE TITLE
`to_numpy(type='obj')` conversion results in seg fault

### ISSUE THREAD

**Issue by pramitchoudhary** [h2oai/datatable#3352]
datatable version: `1.0.0`
dataset: [adult_census.csv](https://github.com/h2oai/datatable/files/9601419/adult_census.csv)

Conversion of mixed type to `to_numpy(type=dt.obj64)` fails with Segmentation fault but `to_pandas().values` or `to_pandas().to_numpy` works. 
Could there be another workaround without converting to `pandas`?  Is it possible to convert `to_list` not column-wise but instead row-wise? 

Note: `to_numpy(type='str)` works fine probably bcauz of type restriction.

```
import datatable as dt

input_X = dt.fread("./adult_census.csv")
input_X.to_numpy(type=dt.obj64) --> Segfault
input_X.to_numpy(type='obj') --> Segfault

# Works fine.
input_X.to_pandas().values 
input_X.to_pandas().to_numpy() 
```

**Comment by oleksiyskononenko** [comment]
What version of datatable you are using and what is the system/python version? The most recent dt doesn't segfault for me on macOS.

**Comment by oleksiyskononenko** [comment]
I confirm that `1.0.0` segfaults for the data you posted, but the most recent dev already has a fix and works just fine.

**Comment by pramitchoudhary** [comment]
python version: `3.7.10`

**Comment by pramitchoudhary** [comment]
> but the most recent dev already has a fix and works fine.

Nice! will upgrade. Thanks! 🙏
