### ISSUE TITLE
how to use iread to read a list of csv

### ISSUE THREAD

**Issue by nankaimy** [h2oai/datatable#3353]
how to use iread to read a list of csv,giving the csvs path

**Comment by samukweku** [comment]
@nankaimy `iread` returns an iterator of the csvs, you can then combine them into one Frame. Have a look at an example on this [blog](https://samukweku.github.io/data-wrangling-blog/python/pydatatable/pandas/2020/11/05/Read-Multiple-Csv-Files-into-one-Table-in-Python.html#Via-iread) I wrote - hope it helps. 

Thinking about it, it won't be a bad idea to add this to the [fread user guide](https://datatable.readthedocs.io/en/latest/manual/fread_examples.html)

**Comment by nankaimy** [comment]
thanks
