### ISSUE TITLE
Fread can support what format files

### ISSUE THREAD

**Issue by nankaimy** [h2oai/datatable#3354]
from the https://datatable.readthedocs.io/en/latest/manual/fread_examples.html ,Fread support  csv xlsx
can support other format files,such as h5 ,parquet  etc

**Comment by oleksiyskononenko** [comment]
Not sure what is your question?

**Comment by oleksiyskononenko** [comment]
If you need a list of formats `fread()` can support, you can get it from documentation:

> The recognized formats are: CSV, Jay, XLSX, and plain text. In addition, the data may be inside an archive such as .tar, .gz, .zip, .gz2, and .tgz.

https://datatable.readthedocs.io/en/latest/api/dt/fread.html

**Comment by nankaimy** [comment]
CSV, Jay, XLSX  thanks
