### ISSUE TITLE
does jay files support append

### ISSUE THREAD

**Issue by nankaimy** [h2oai/datatable#3355]
does jay files support append

“.jay” for the file. If the file exists, it will be overwritten

if the .jay file is very big,and need to append new data,I need to fread rbind and datatable.Frame.to_jay(),when .to_jay(),it will cost much memory, Does it exist method like pandas_to_hdf(,mode=‘a’') ,not need to cost much memory

**Comment by oleksiyskononenko** [comment]
We don't have an append function for Jay files, but when you open a jay file — it will be memory mapped, so won't cost you any memory. Also note, that there is a `memory_limit` parameter in `fread()`: https://datatable.readthedocs.io/en/latest/api/dt/fread.html#memory_limit

**Comment by nankaimy** [comment]
when I open a jay file — it  won't cost  any memory，but when .to_jay(),it will cost much memory

**Comment by oleksiyskononenko** [comment]
Well, it depends on the nature of the frame to be saved. If the frame is already materialized in the memory, then `to_jay()` shouldn't use much memory as it will only write to disk. If the frame has some virtual columns (could be created with `rbind`), it will need to materialize them before saving to jay, and this is where dt may consume some memory.

Anyways, the data in the jay format are stored column-wise, so there is no easy way to append data to the columns. However, for CSV files the data are saved row-wise, so there is an [append](https://datatable.readthedocs.io/en/latest/api/frame/to_csv.html?highlight=append#append) option.

**Comment by nankaimy** [comment]
thanks
