### ISSUE TITLE
fread  how to deal one column is all na

### ISSUE THREAD

**Issue by nankaimy** [h2oai/datatable#3356]
use fread to read the data 
data = """
       ID|Charges|Payment_Method
       634-VHG|28|
       365-DQC|33.5|
       264-PPR|631|
       845-AJO|42.3|
       789-KPO|56.9|
       """

df=dtable.fread(data, na_strings=['--', ''])
df=df.to_pandas()

![image](https://user-images.githubusercontent.com/7699602/192129773-9e793ac7-598a-4aab-9bfe-1da58ab1677e.png)
ID	Charges	Payment_Method
634-VHG	28.0	b''
365-DQC	33.5	b''
264-PPR	631.0	b''
845-AJO	42.300000000000004	b''
789-KPO	56.900000000000006	b''

use pandas.read_csv  read the data 

df=pd.read_csv(txt_pth,na_filter=True)
ID	Charges	Payment_Method
634-VHG	28.0	nan
365-DQC	33.5	nan
264-PPR	631.0	nan
845-AJO	42.300000000000004	nan
789-KPO	56.900000000000006	nan

does it exist like na_filter=True to deal columns(Payment_Method) is all na,and when fread be replaced with nan like pandas.read_csv na_filter=True

na_strings=['--', ''] will work when columns(Payment_Method) is not all na,but all na it will  display	b''

**Comment by oleksiyskononenko** [comment]
This "b-issue" has been fixed some time ago, you just need [to install the latest dev](https://datatable.readthedocs.io/en/latest/start/install.html#install-latest-dev-version) to get the void columns working:
```python
>>> from datatable import dt
>>> data = """
... ID|Charges|Payment_Method
... 634-VHG|28|
... 365-DQC|33.5|
... 264-PPR|631|
... 845-AJO|42.3|
... 789-KPO|56.9|
... """
>>> DT = dt.fread(data)
>>> DT
   | ID       Charges  Payment_Method
   | str32    float64            void
-- + -------  -------  --------------
 0 | 634-VHG     28                NA
 1 | 365-DQC     33.5              NA
 2 | 264-PPR    631                NA
 3 | 845-AJO     42.3              NA
 4 | 789-KPO     56.9              NA
[5 rows x 3 columns]
>>> DT.to_pandas()
        ID  Charges Payment_Method
0  634-VHG     28.0           None
1  365-DQC     33.5           None
2  264-PPR    631.0           None
3  845-AJO     42.3           None
4  789-KPO     56.9           None
```

**Comment by nankaimy** [comment]
does it exist a cp37 wheel?
![image](https://user-images.githubusercontent.com/7699602/192148488-d70c00e4-11c6-46e8-a6d9-1a8d111e09e6.png)

**Comment by oleksiyskononenko** [comment]
@nankaimy You're right, we are missing 3.7 Windows wheels on AppVeyor. Let me fix it.

**Comment by oleksiyskononenko** [comment]
Btw, you're looking at the PR builds (note "Pull request #3346" in the caption and "pr" in the wheel's names), but what you should install is the `main` build. Those builds won't be marked as "Pull requests", here is the latest one, for instance: https://ci.appveyor.com/project/h2oops/datatable/builds/44826282/job/o7m6kh6416atugsf/artifacts
