### ISSUE TITLE
`columns` parameter is not honored when freading jay files?

### ISSUE THREAD

**Issue by nankaimy** [h2oai/datatable#3360]
```python
import datatable as dt
a=dt.fread(r"E:\b.csv",columns={'weight','trade_dt'}).to_pandas()
```

![image](https://user-images.githubusercontent.com/7699602/192285930-056db9fc-827c-4ee9-91e1-9245c5d03ddf.png)

but
```python
a=dt.fread(r"E:\b.csv").to_jay(r"E:\b.jay")
a=dt.fread(r"E:\b.jay",columns={'weight','trade_dt'}).to_pandas()
```

then
![image](https://user-images.githubusercontent.com/7699602/192286318-33708d9d-e3ca-4ca5-aa78-6a5b2259d463.png)

Attaching the file in question: [b.csv](https://github.com/h2oai/datatable/files/9646476/b.csv)

**Comment by oleksiyskononenko** [comment]
Yeah, the `columns` parameter is for reading CSV files only. The thing is that for CSV, when you only need particular columns, you can save some time by not parsing the other columns. 

However, when you open a Jay file, the whole file is memory mapped immediately, so there is no sense to skip particular columns.  

If you only need particular columns from your Jay file, simply add a j-filter
```python
a=dt.fread(r"E:\b.jay")[:, ['weight', 'trade_dt']).to_pandas()
```

**Comment by nankaimy** [comment]
thanks
