### ISSUE TITLE
Outdated pypi package

### ISSUE THREAD

**Issue by 372046933** [h2oai/datatable#3369]
- Describe what feature you would like to see implemented.
Will pypi host latest package?
- If possible, give an example of how it may look in the code and what result
  will be produced.
`datatable` on pypi is released: Jul 2, 2021.  Taking this example. `datatable.Frame.to_csv` `hex` parammeter does not exist on pypi

- Click "Preview" to check that there are no formatting problems, that the
  request is stated clearly, and that it is not overbroad in scope.

- Thanks for contributing. We appreciate your input!

**Comment by oleksiyskononenko** [comment]
It will be released when we implement all the planned features. Meanwhile, you can install the latest dev version: https://datatable.readthedocs.io/en/latest/start/install.html#install-latest-dev-version
