### ISSUE TITLE
macos12 + python3.10 not support

### ISSUE THREAD

**Issue by yutaolife** [h2oai/datatable#3380]
macos 12 + python3.10 could not install successfully. even if i used "pip install YOUR_WHEEL_URL". 
from the "YOUR_WHEEL_URL" list, i also not find the macos12 whl file. 

ERROR: datatable-1.1.0a2203-cp310-cp310-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

**Comment by oleksiyskononenko** [comment]
Please kindly provide some details.

- are you using `venv`?
- do you have an intel or apple CPU?

**Comment by yutaolife** [comment]
are you using venv?
No
do you have an Intel or Apple CPU?
My 

> Please kindly provide some details.
> 
> * are you using `venv`?
> * do you have an Intel or Apple CPU?
* are you using `venv`?
No
 * do you have an Intel or Apple CPU?
Apple M2

**Comment by oleksiyskononenko** [comment]
@yutaolife We do not provide ARM64 wheels for the moment. For some workarounds, please see https://github.com/h2oai/datatable/issues/3222

Duplicate of https://github.com/h2oai/datatable/issues/3222
