### ISSUE TITLE
`dt.prod()` calculates sum instead of a product for the grouped columns

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#3390]
```python
>>> from datatable import dt, f
>>> DT = dt.Frame([1, 1])
>>> DT[:, dt.prod(f.C0)]
   |    C0
   | int64
-- + -----
 0 |     1
[1 row x 1 column]
>>> DT[:, dt.prod(f.C0), by(f.C0)]
   |   C0     C1
   | int8  int64
-- + ----  -----
 0 |    1      2
[1 row x 2 columns]
```

Note, the product on the grouped column should still be `1`, i.e. the correct result for the last example is
```python
   |   C0     C1
   | int8  int64
-- + ----  -----
 0 |    1      1
[1 row x 2 columns]
```

**Comment by oleksiyskononenko** [comment]
@samukweku I still wonder why this bug was not caught by our tests, even though you've got a test for `prod()` on the grouped columns. Do you have time to look at this test and adjust it if necessary?

**Comment by samukweku** [comment]
@oleksiyskononenko sure I'll have a look
