### ISSUE TITLE
`dt.median()` errors when used on void columns in a groupby context

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#3411]
Using `dt.median()` reducer in a groupby context
```python
from datatable import dt, median, by
DT = dt.Frame([[None, None], [1, 2]])
DT[:, median(f.C0), by(f.C1)] 
```

triggers
```python
AssertionError: Assertion 'col && col.nrows() == nrows_' failed in src/core/datatable.cc, line 66
```

Doing
```python
DT[:, median(f.C1), by(f.C0)]
```

also triggers
```python
AssertionError: Assertion '!col.is_virtual()' failed in src/core/sort.cc, line 562
```

The reason these were never caught by the unit tests are [several typos](https://github.com/h2oai/datatable/blob/main/tests/test-reduce.py#L459-L474) in the `test-reduce.py` resulting in testing `dt.mean()` instead of `dt.median()`.

**Comment by samukweku** [comment]
I'll try and fix this when I create the FExpr for median

**Comment by samukweku** [comment]
Should I fix this when creating FExpr for median?

**Comment by oleksiyskononenko** [comment]
@samukweku There is already `Median_ColumnImpl` class for `dt.median()` that has couple of bugs, I've already fixed them and will push the changes soon. When converting to `FExpr`, you can simple reuse that existing class.
