### ISSUE TITLE
Error when building with gcc on `arm64`

### ISSUE THREAD

**Issue by hallmeier** [h2oai/datatable#3430]
I read the related issues, but my error is not included. I can install the development version of datatable just fine (Chip: Apple M1 Max, OS: Ventura 13.1), except in docker (`FROM python:3.11`):

```
gcc: error: unrecognized command-line option ‘-m64’
```

clang understands this command line option, but gcc does not. That is why installation works on the system, but not in docker. The fix for me is simple, just remove the [option](https://github.com/h2oai/datatable/blob/main/ci/ext.py#L297):

```
RUN git clone https://github.com/h2oai/datatable datatable
RUN sed -i "/m64/d" datatable/ci/ext.py
RUN pip install datatable/.
```

But I assume the option has some purpose, so it should ideally be wrapped with an appropiate if-clause. I don't know what that would be, though.

**Comment by oleksiyskononenko** [comment]
Yeah, for the moment we didn’t port datatable to Apple CPUs. Even though you can build it, some tests are failing. We can work on a fix, however, our Jenkins/AppVeyor don’t have machines with Apple CPUs to test the changes.

**Comment by oleksiyskononenko** [comment]
@hallmeier btw, what was the docker operating system and gcc version?

**Comment by hallmeier** [comment]
The docker base image is python:3.11(.2-bullseye), so the operating system inside docker is Linux and the gcc version is gcc (Debian 10.2.1-6) 10.2.1 20210110.

**Comment by hallmeier** [comment]
Thanks for addressing this, and we're almost there! But I found on my ARM64 machine `platform.machine()` returns `"aarch64"` (an alias) instead of `"arm64"`. So the [line](https://github.com/h2oai/datatable/blob/32ccfae70ebc361f3a6cef60f34586d1e414b23e/ci/ext.py#L210) `arm64 = (arch == "arm64")` needs to be changed to `arm64 = (arch == "aarch64")` or `arm64 = (arch in ["arm64", "aarch64"])` (I don't know if `"arm64"` is returned on some machines) and it would work.

**Comment by oleksiyskononenko** [comment]
Yes, on my M1 machine it returns `arm64`. Thanks for letting me know, I will push a fix.
