### ISSUE TITLE
`dt.countna()` returns wrong results for grouped columns 

### ISSUE THREAD

**Issue by oleksiyskononenko** [h2oai/datatable#3441]
```python
>>> DT = dt.Frame([None])
>>> DT[:, dt.countna(f.C0), dt.by(f.C0)]
   |   C0     C1
   | void  int64
-- + ----  -----
 0 |   NA      0
[1 row x 2 columns]
```

The result should actually be
```python
   |   C0     C1
   | void  int64
-- + ----  -----
 0 |   NA      1
[1 row x 2 columns]
```

**Comment by samukweku** [comment]
@oleksiyskononenko this is resolved in #3440

**Comment by oleksiyskononenko** [comment]
@samukweku Then we need to add a corresponding test and update PR description saying "Closes #3441".

**Comment by oleksiyskononenko** [comment]
So the issue here is that we've been reading from the void column, just like it has `int8_t` values:
https://github.com/h2oai/datatable/blob/main/src/core/expr/head_reduce_unary.cc#L388-L390

**Comment by oleksiyskononenko** [comment]
So the issue here is that we've been returning `0` for `void` columns, no matter if we calculate missing or non-missing values:
https://github.com/h2oai/datatable/blob/main/src/core/expr/head_reduce_unary.cc#L457-L460

We had to take into account the `NA` value to make it work properly.
