### ISSUE TITLE
datatable.fread read csv and auto transfer 0/1 to bool8

### ISSUE THREAD

**Issue by heyhpython** [h2oai/datatable#3478]
- Did you find a bug in datatable, or maybe the bug found you?
  Tell us what it is.
I have a csv file with a column named hit_rule,which value like 1,1,1,1,1,0,0 ，when i try to datatable.fread('file_path'),
- How to reproduce the bug?
  **This part is the most important**. Please provide a code snippet which, when
  executed in console, demonstrates the problem. If necessary, attach any data
  files to the issue.
![image](https://github.com/h2oai/datatable/assets/36200210/17b92792-f89d-4370-946b-e130e839bcbd)
dt1 is DataFrame read with pandas 
dt2 is  datatable.Frame read with datatable 
the image tell the difference
- What was the expected behavior?
  In case it is not obvious, please tell us what result should your code
  produce.
i expect datable do not transfer the origin datatype 
- Your environment?
  What is your datatable version, python version, and operating system?
windows11 
- Tag the issue with `[bug]` or `[segfault]` (depending on whether it crashes
  Python or not).
[bug]
- Thank you for contributing, and sorry for the inconvenience.

**Comment by arnocandel** [comment]
This is intentional since bools are just 0/1 integers internally. You can do dt[:, bool] = int to convert them to int8.
