### ISSUE TITLE
Implement sorting in reverse order

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#792]
Expected API:
```
# sort by A column in descending order
df.sort("A", descending=True)
df.sort(-f.A)
# sort by A descending, and B ascending
df.sort("A", "B", descending=[True, False])
df.sort(-f.A, f.B)
```
Note that `-f.A` should work even if `A` is a string column; and even if it is numeric, the intermediate column `-f.A` should not be computed.

**Comment by jangorecki** [comment]
removed `low` tag as it is probably required to compute q8 in groupby benchmark, which is also compactly described in https://stackoverflow.com/questions/54128229/top-n-rows-by-group-using-python-datatable

**Comment by st-pasha** [comment]
Tag `[low]` means something that is nice to have but nobody really wants it just yet. Since now you do need this feature, the tag ought to be removed.
