### ISSUE TITLE
Allow deleting rows from an unsorted array

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#805]
Currently we can delete rows, using an array of integers as a selector. However that array must be sorted, otherwise an exception will be thrown. This issue asks to support deleting an unsorted list of rows too -- probably by sorting and de-duplicating them.

**Comment by pradkrish** [comment]
This requires all selector arrays to be sorted before sending it to row slicing. Could it be beneficial to add an option so user can indicate whether the user provided array is already sorted or not. In this way we need not waste computations sorting an already sorted array. The default behaviour can always be sort before delete.

**Comment by st-pasha** [comment]
We need to convert from a python list of integers into C++ vector anyways, so can check for sortedness at that time.

**Comment by pradkrish** [comment]
Yeah, that's a good point. I guess we read the data here `src/core/expr/fexpr_list.cc:271`. Since we know the size of the args, do you think it's optimal to sort while reading in the data for arrays of size<64?

**Comment by st-pasha** [comment]
In order to delete rows, we need to construct a vector of indices of all remaining rows. Thus, if you're removing `[2, 5, 4, 0, 4]` from a frame with 1K rows, then you need to construct a list of indices `[1, 3, 6, 7, 8, ..., 999]` (for a typical use case the number of rows to delete is much smaller than the number of rows). In order to construct this "negated list" it's inefficient to look at each index in turn and ask "is this index in the list of indices to remove?". Instead, we start at 0 and then ask "which index is next to remove", then we fill the array with all indices up to that. 

All you need for this algorithm to work is to have a sorted list of indices to remove. It can even have duplicates.

Using a map (or set) is both more expensive in terms of construction, and then also when we need to create the "negated list".

**Comment by pradkrish** [comment]
As you said, a typical use case will have much smaller number of rows to delete, would it be enough to use `std::sort` for this or should we use datatable's implementation of radix sort?  The number of rows to delete could be a large number as well.
