### ISSUE TITLE
Publish results from internal Jenkins publicly

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#808]
To simplify contribution from external contributors, we need to make sure, that we make Jenkins results available.

There are 3 solutions:
  1. Publish results as static pages into S3
  2. Move internal Jenkins to AWS
  3. Make a tunnel into internal network to view Jenkins results

Right now, the fastest solution seems to be **no 1**, but we need to figure out best strategy for our OSS projects (CC: @michal-raska )

**Comment by mmalohlava** [comment]
Done via GH releases.

**Comment by mmalohlava** [comment]
We need to publish internal tests reports.

**Comment by mmalohlava** [comment]
After research with @abal5 we found this one: https://wiki.jenkins.io/display/JENKINS/Build+Publisher+Plugin - we will have public RO version of Jenkins running, synchronized with internal jenkins.

**Comment by oleksiyskononenko** [comment]
This issue doesn't seem to be relevant anymore. Since #3042 we brought both Linux and macOS builds to AppVeyor, that is accessible for anyone.
