### ISSUE TITLE
In fread add ability to select only a certain columns from the file

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#83]
Two parameters should be added:
* `dropcols` (hidden alias: `drop`) of type `slice | [int] | [str]`
* `usecols` (hidden alias: `select`) of type `slice | [int] | [str] | (str)->U[bool,str] | (int,str)->U[bool,str]`

The parameters are exclusive: they cannot be used simultaneously. Use `dropcols` to request that a list/slice of columns was removed from the datatable. Use `usecols` to specify that only a certain set of columns in the input file should be included in the result. This parameter can also accept a callable, which may have one of 2 forms: either taking a single argument (this will be the name of the column), or two arguments (the index and the name of the column). The function then should return either `True`/`False` indicating whether the column ought to be kept/dropped, or a string containing the name of the column that will be produced.

**Comment by anhtholee** [comment]
How to use `select`/`usecols` or `drop`/`dropcols` parameters? I got the following error when trying to use any of them in fread ( `datatable 0.10.0`):
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed exec> in <module>

/usr/local/lib64/python3.6/site-packages/datatable/fread.py in fread(anysource, file, text, cmd, url, columns, sep, dec, max_nrows, header, na_strings, verbose, fill, encoding, skip_to_string, skip_to_line, skip_blank_lines, strip_whitespace, quotechar, save_to, nthreads, logger, **extra)
     58     params = {**locals(), **extra}
     59     del params["extra"]
---> 60     freader = GenericReader(**params)
     61     return freader.read()
     62 

/usr/local/lib64/python3.6/site-packages/datatable/fread.py in __init__(self, anysource, file, text, url, cmd, columns, sep, max_nrows, header, na_strings, verbose, fill, encoding, dec, skip_to_string, skip_to_line, save_to, nthreads, logger, skip_blank_lines, strip_whitespace, quotechar, **args)
    107         if args:
    108             raise TTypeError("Unknown argument(s) %r in FReader(...)"
--> 109                              % list(args.keys()))
    110 
    111 

TypeError: Unknown argument(s) ['drop'] in FReader(...)
```

**Comment by st-pasha** [comment]
@anhtholee The argument is called `columns`, see examples at https://github.com/h2oai/datatable/blob/master/tests/fread/test_fread_api.py#L389
