### ISSUE TITLE
Relocate as many build files as possible into ci/ directory

### ISSUE THREAD

**Issue by st-pasha** [h2oai/datatable#951]
This is a minor cleanup task: move build-related files into the dedicated folder.

**Comment by mmalohlava** [comment]
@abal5 Can you please help here as well? Just move all Jenkinsfile and Dockerfiles into `ci` folder and make sure that you change all references in makefile and Jenkinsfile.

**Comment by st-pasha** [comment]
2 files still remain: `clang++_wrapper.sh` and `llvm-gcov.sh`.
