### ISSUE TITLE
Dockerfile-centos7.in - switch from using `conda` to `pip`

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#982]
Right now, `Dockerfile-centos7.in` is using conda to install numpy into test environment.

This is causing SEGABRT because of incompatible libomp libraries.

Solution: use pip to install dependencies in `Dockerfile-centos7.in`

**Comment by mmalohlava** [comment]
@michal-raska do you remember reason of using conda to install dependencies: https://github.com/h2oai/datatable/blob/master/Dockerfile-centos7.in#L27-L43 ?

**Comment by st-pasha** [comment]
We only use `psutil` in one place, and we can make that place optional.
So this dependency is removable.
