### ISSUE TITLE
Create Py-DataTable Cheatsheet

### ISSUE THREAD

**Issue by meganjkurka** [h2oai/datatable#989]
The Cheatsheet will have two sides:

- R side: https://pbs.twimg.com/media/DVxtBi5VQAARRY4.jpg
- Python side: same as R but for Python
    - should show what is and is not available in PyDataTable

**Comment by st-pasha** [comment]
Megan, could you please explain what process are using for creating the Cheatsheet?
Do you have some kind of source code (eg. LaTeX or similar) which is being compiled into a JPEG, or is it created manually? What is the process for updating it when we add new functionality (or make changes to existing one)?

**Comment by meganjkurka** [comment]
@st-pasha the cheatsheet is created manually using Powerpoint (it will then be converted to PDF).  If a new functionality is added you can update the Powerpoint.

**Comment by statquant** [comment]
@meganjkurka you seem to say that you have a cheatsheet completed, would that be possible to get it ? I'd be happy to test all recipes.

**Comment by st-pasha** [comment]
@statquant 
[datatable_cheatsheet.pptx](https://github.com/h2oai/datatable/files/2114053/datatable_cheatsheet.pptx)

**Comment by st-pasha** [comment]
[datatable_cheatsheet.pdf](https://github.com/h2oai/datatable/files/2120330/datatable_cheatsheet.pdf)
