### ISSUE TITLE
Change the way how docker images are created

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#990]
We need to:
   - assign a version for each build docker image which we are pushing into docker registry
       -  this will enable to have to reference a specific build image in Jenkinsfile even it is on PR branch
   - Modify Jenkinsfile to use version (aka tag) to reference Docker image instead of SHA
  - Make http://mr-0xc1:8080/view/DataTable/job/datatable-docker-image-build/ as multi-branch pipeline

**Comment by mmalohlava** [comment]
Right now, the publication of images is blocked on:
```
file:/home/jenkins/jobs/datatable-docker-image-build/builds/10/libs/test-shared-library/src/ai/h2o/ci/buildsummary/BuildSummary.groovy: 4: unable to resolve class org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildSummaryAction
 @ line 4, column 1.
   import org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildSummaryAction
```

**Comment by abal5** [comment]
`GroovyPostbuildSummaryAction` issue is resolved for now
