### ISSUE TITLE
Modify Jenkinsfile to support Makefile builds

### ISSUE THREAD

**Issue by mmalohlava** [h2oai/datatable#992]
The goal is to move preparation of environment from Jenkinsfile into Makefile and have targets like:

```
make build_in_centos7
```

**Comment by michal-raska** [comment]
I think it might be easier to reproduce it manually but it might introduce some duplicate code. But we need to be able to build datatable manually, so I think it's definitely worth it. I can take a look if you want.

**Comment by mmalohlava** [comment]
Done
